import { Toaster } from "@omniflow/ui/toast";
import { GeistMono } from "geist/font/mono";
import { GeistSans } from "geist/font/sans";
import type { Metadata } from "next";
import { NextIntlClientProvider } from "next-intl";
import { getLocale, getMessages } from "next-intl/server";
import type { ReactNode } from "react";

import { Measurement } from "@/components/analytics/measurement";
import { ThemeProvider } from "@/components/theme-provider";
import { readAnalytics } from "@/lib/analytics";
import { readBranding } from "@/lib/branding";
import "./globals.css";

/**
 * The tab title and icon follow whatever the installation calls itself.
 *
 * It is generated rather than static because an operator selling under their
 * own brand should not have somebody else's name in the browser tab, and the
 * tab is the one piece of chrome no amount of in-page theming reaches.
 */
export async function generateMetadata(): Promise<Metadata> {
  const branding = await readBranding();
  const name = branding.serviceName.trim() || "Omniflow";
  return {
    title: { default: name, template: `%s · ${name}` },
    description: "VPN subscriptions, customer self-service, and service operations.",
    icons: branding.assets.favicon ? { icon: branding.assets.favicon } : undefined,
  };
}

export default async function RootLayout({ children }: Readonly<{ children: ReactNode }>) {
  const [locale, messages, branding, analytics] = await Promise.all([
    getLocale(),
    getMessages(),
    readBranding(),
    readAnalytics(),
  ]);

  return (
    /*
     * `suppressHydrationWarning` is required on <html> because next-themes
     * writes the resolved theme class before React hydrates, so the server and
     * client markup differ by design on this element only.
     */
    <html
      className={`${GeistSans.variable} ${GeistMono.variable}`}
      lang={locale}
      suppressHydrationWarning
    >
      <head>
        {/*
         * Webmaster verification tags. They set no cookie, load no script, and
         * observe nobody, so they are rendered for every visitor and every
         * anonymous fetch — a verification that only appeared after somebody
         * consented would verify nothing, because the fetcher is a tool rather
         * than a person. The name comes from an allowlist and the content from
         * a token pattern; see `internal/adtracking`.
         */}
        {analytics.verifications?.map((verification) => (
          <meta content={verification.content} key={verification.name} name={verification.name} />
        ))}
        {/*
         * The operator's palette, inlined so it applies on first paint. The
         * string is generated by the API from an allowlist of token names and a
         * hex-only colour parser — see `internal/branding` — which is what
         * makes injecting it here safe: its alphabet cannot contain a brace, a
         * semicolon, or the sequence that would close this element.
         */}
        {branding.css ? (
          // biome-ignore lint/security/noDangerouslySetInnerHtml: server-generated CSS from a validated allowlist; see internal/branding
          <style dangerouslySetInnerHTML={{ __html: branding.css }} id="omniflow-brand" />
        ) : null}
      </head>
      <body>
        <ThemeProvider allowedThemes={branding.allowedThemes} defaultTheme={branding.defaultTheme}>
          <NextIntlClientProvider messages={messages}>
            {children}
            {/* Renders nothing at all unless the operator configured a counter,
                and nothing until the visitor has agreed to it. */}
            <Measurement analytics={analytics} />
            <Toaster />
          </NextIntlClientProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
