// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: admin_operations.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const archivePlan = `-- name: ArchivePlan :one
UPDATE plans
SET archived_at = CASE WHEN $1::boolean THEN COALESCE(archived_at, now()) ELSE NULL END,
    visible = CASE WHEN $1::boolean THEN false ELSE visible END
WHERE id = $2
RETURNING id, code, kind, visible, sort_order, created_at, archived_at, max_concurrent_per_customer
`

type ArchivePlanParams struct {
	Archived bool        `json:"archived"`
	PlanID   pgtype.UUID `json:"plan_id"`
}

func (q *Queries) ArchivePlan(ctx context.Context, arg ArchivePlanParams) (Plan, error) {
	row := q.db.QueryRow(ctx, archivePlan, arg.Archived, arg.PlanID)
	var i Plan
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Kind,
		&i.Visible,
		&i.SortOrder,
		&i.CreatedAt,
		&i.ArchivedAt,
		&i.MaxConcurrentPerCustomer,
	)
	return i, err
}

const cancelBulkOperation = `-- name: CancelBulkOperation :one
UPDATE bulk_operations
SET status = 'cancelled', completed_at = now(), updated_at = now()
WHERE id = $1 AND status IN ('previewing', 'ready')
RETURNING id, kind, status, requested_by, reason, parameters, total_count, succeeded_count, failed_count, skipped_count, idempotency_key, created_at, updated_at, completed_at
`

func (q *Queries) CancelBulkOperation(ctx context.Context, operationID pgtype.UUID) (BulkOperation, error) {
	row := q.db.QueryRow(ctx, cancelBulkOperation, operationID)
	var i BulkOperation
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.Status,
		&i.RequestedBy,
		&i.Reason,
		&i.Parameters,
		&i.TotalCount,
		&i.SucceededCount,
		&i.FailedCount,
		&i.SkippedCount,
		&i.IdempotencyKey,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const cancelFulfillmentOperation = `-- name: CancelFulfillmentOperation :one
UPDATE fulfillment_operations
SET status = 'cancelled', completed_at = now(), updated_at = now()
WHERE id = $1 AND status IN ('pending', 'retrying', 'failed')
RETURNING id, entitlement_id, operation, status, idempotency_key, correlation_id, desired_state, attempt_count, next_attempt_at, last_error_code, created_at, updated_at, completed_at
`

// Only an operation that has not yet succeeded may be cancelled, so a completed
// provisioning can never be retracted by a panel click.
func (q *Queries) CancelFulfillmentOperation(ctx context.Context, operationID pgtype.UUID) (FulfillmentOperation, error) {
	row := q.db.QueryRow(ctx, cancelFulfillmentOperation, operationID)
	var i FulfillmentOperation
	err := row.Scan(
		&i.ID,
		&i.EntitlementID,
		&i.Operation,
		&i.Status,
		&i.IdempotencyKey,
		&i.CorrelationID,
		&i.DesiredState,
		&i.AttemptCount,
		&i.NextAttemptAt,
		&i.LastErrorCode,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const completeBulkOperationItem = `-- name: CompleteBulkOperationItem :one
UPDATE bulk_operation_items
SET status = $1, error_code = $2, processed_at = now()
WHERE operation_id = $3
  AND position = $4
  AND status = 'pending'
RETURNING operation_id, position, target_type, target_id, status, error_code, processed_at
`

type CompleteBulkOperationItemParams struct {
	Status      string      `json:"status"`
	ErrorCode   pgtype.Text `json:"error_code"`
	OperationID pgtype.UUID `json:"operation_id"`
	Position    int32       `json:"position"`
}

func (q *Queries) CompleteBulkOperationItem(ctx context.Context, arg CompleteBulkOperationItemParams) (BulkOperationItem, error) {
	row := q.db.QueryRow(ctx, completeBulkOperationItem,
		arg.Status,
		arg.ErrorCode,
		arg.OperationID,
		arg.Position,
	)
	var i BulkOperationItem
	err := row.Scan(
		&i.OperationID,
		&i.Position,
		&i.TargetType,
		&i.TargetID,
		&i.Status,
		&i.ErrorCode,
		&i.ProcessedAt,
	)
	return i, err
}

const createBulkOperation = `-- name: CreateBulkOperation :one

INSERT INTO bulk_operations (kind, requested_by, reason, parameters, idempotency_key)
VALUES (
  $1, $2, $3,
  $4, $5
)
ON CONFLICT (idempotency_key) DO NOTHING
RETURNING id, kind, status, requested_by, reason, parameters, total_count, succeeded_count, failed_count, skipped_count, idempotency_key, created_at, updated_at, completed_at
`

type CreateBulkOperationParams struct {
	Kind           string      `json:"kind"`
	RequestedBy    pgtype.UUID `json:"requested_by"`
	Reason         string      `json:"reason"`
	Parameters     []byte      `json:"parameters"`
	IdempotencyKey string      `json:"idempotency_key"`
}

// ---------------------------------------------------------------------------
// Bulk operator actions
// ---------------------------------------------------------------------------
func (q *Queries) CreateBulkOperation(ctx context.Context, arg CreateBulkOperationParams) (BulkOperation, error) {
	row := q.db.QueryRow(ctx, createBulkOperation,
		arg.Kind,
		arg.RequestedBy,
		arg.Reason,
		arg.Parameters,
		arg.IdempotencyKey,
	)
	var i BulkOperation
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.Status,
		&i.RequestedBy,
		&i.Reason,
		&i.Parameters,
		&i.TotalCount,
		&i.SucceededCount,
		&i.FailedCount,
		&i.SkippedCount,
		&i.IdempotencyKey,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const dashboardCustomerTotals = `-- name: DashboardCustomerTotals :one

SELECT
  count(*) FILTER (WHERE status = 'active')::bigint AS active_customers,
  count(*) FILTER (WHERE status = 'suspended')::bigint AS suspended_customers,
  count(*) FILTER (WHERE status = 'deleted')::bigint AS deleted_customers,
  count(*) FILTER (WHERE created_at >= now() - $1::interval)::bigint AS new_customers
FROM users
`

type DashboardCustomerTotalsRow struct {
	ActiveCustomers    int64 `json:"active_customers"`
	SuspendedCustomers int64 `json:"suspended_customers"`
	DeletedCustomers   int64 `json:"deleted_customers"`
	NewCustomers       int64 `json:"new_customers"`
}

// ---------------------------------------------------------------------------
// Dashboard
// ---------------------------------------------------------------------------
// Every count carries its own definition, which the panel repeats beside the
// number: "active" is a customer record that is neither suspended nor deleted,
// not one with a live subscription.
func (q *Queries) DashboardCustomerTotals(ctx context.Context, lookback pgtype.Interval) (DashboardCustomerTotalsRow, error) {
	row := q.db.QueryRow(ctx, dashboardCustomerTotals, lookback)
	var i DashboardCustomerTotalsRow
	err := row.Scan(
		&i.ActiveCustomers,
		&i.SuspendedCustomers,
		&i.DeletedCustomers,
		&i.NewCustomers,
	)
	return i, err
}

const dashboardDriftTotals = `-- name: DashboardDriftTotals :one
SELECT
  count(*) FILTER (WHERE status = 'open')::bigint AS open_drifts,
  count(*) FILTER (WHERE status = 'open' AND kind = 'missing_remote')::bigint AS missing_remote
FROM entitlement_drifts
`

type DashboardDriftTotalsRow struct {
	OpenDrifts    int64 `json:"open_drifts"`
	MissingRemote int64 `json:"missing_remote"`
}

func (q *Queries) DashboardDriftTotals(ctx context.Context) (DashboardDriftTotalsRow, error) {
	row := q.db.QueryRow(ctx, dashboardDriftTotals)
	var i DashboardDriftTotalsRow
	err := row.Scan(&i.OpenDrifts, &i.MissingRemote)
	return i, err
}

const dashboardJobHealth = `-- name: DashboardJobHealth :one
SELECT
  count(*) FILTER (WHERE status IN ('pending', 'retrying'))::bigint AS queued,
  count(*) FILTER (WHERE status = 'failed')::bigint AS failed,
  count(*) FILTER (
    WHERE status IN ('pending', 'retrying') AND next_attempt_at < now() - $1::interval
  )::bigint AS overdue
FROM fulfillment_operations
`

type DashboardJobHealthRow struct {
	Queued  int64 `json:"queued"`
	Failed  int64 `json:"failed"`
	Overdue int64 `json:"overdue"`
}

func (q *Queries) DashboardJobHealth(ctx context.Context, lateAfter pgtype.Interval) (DashboardJobHealthRow, error) {
	row := q.db.QueryRow(ctx, dashboardJobHealth, lateAfter)
	var i DashboardJobHealthRow
	err := row.Scan(&i.Queued, &i.Failed, &i.Overdue)
	return i, err
}

const dashboardOutboxLag = `-- name: DashboardOutboxLag :one
SELECT
  count(*)::bigint AS unpublished,
  COALESCE(extract(epoch FROM now() - min(occurred_at)), 0)::bigint AS oldest_age_seconds
FROM outbox_events
WHERE published_at IS NULL
`

type DashboardOutboxLagRow struct {
	Unpublished      int64 `json:"unpublished"`
	OldestAgeSeconds int64 `json:"oldest_age_seconds"`
}

// The oldest unpublished event is the honest measure of lag: a queue with a
// thousand fresh events is healthy, and one with a single event from an hour
// ago is not.
func (q *Queries) DashboardOutboxLag(ctx context.Context) (DashboardOutboxLagRow, error) {
	row := q.db.QueryRow(ctx, dashboardOutboxLag)
	var i DashboardOutboxLagRow
	err := row.Scan(&i.Unpublished, &i.OldestAgeSeconds)
	return i, err
}

const dashboardPaymentHealth = `-- name: DashboardPaymentHealth :one
SELECT
  count(*) FILTER (WHERE i.status = 'succeeded')::bigint AS succeeded,
  count(*) FILTER (WHERE i.status IN ('pending', 'requires_action', 'processing'))::bigint AS in_flight,
  count(*) FILTER (WHERE i.status = 'failed')::bigint AS failed,
  count(*) FILTER (
    WHERE i.status IN ('pending', 'requires_action', 'processing')
      AND i.updated_at < now() - $1::interval
  )::bigint AS stuck
FROM payment_intents i
WHERE i.created_at >= now() - $2::interval
`

type DashboardPaymentHealthParams struct {
	StuckAfter pgtype.Interval `json:"stuck_after"`
	Lookback   pgtype.Interval `json:"lookback"`
}

type DashboardPaymentHealthRow struct {
	Succeeded int64 `json:"succeeded"`
	InFlight  int64 `json:"in_flight"`
	Failed    int64 `json:"failed"`
	Stuck     int64 `json:"stuck"`
}

func (q *Queries) DashboardPaymentHealth(ctx context.Context, arg DashboardPaymentHealthParams) (DashboardPaymentHealthRow, error) {
	row := q.db.QueryRow(ctx, dashboardPaymentHealth, arg.StuckAfter, arg.Lookback)
	var i DashboardPaymentHealthRow
	err := row.Scan(
		&i.Succeeded,
		&i.InFlight,
		&i.Failed,
		&i.Stuck,
	)
	return i, err
}

const dashboardRevenue = `-- name: DashboardRevenue :many
SELECT
  o.currency,
  COALESCE(sum(o.paid_minor), 0)::bigint AS paid_minor,
  COALESCE(sum(o.wallet_minor), 0)::bigint AS wallet_minor,
  COALESCE(sum(o.refunded_minor), 0)::bigint AS refunded_minor,
  count(*)::bigint AS order_count
FROM orders o
WHERE o.state IN ('paid', 'fulfilled', 'partially_refunded', 'refunded')
  AND o.updated_at >= now() - $1::interval
GROUP BY o.currency
ORDER BY o.currency
`

type DashboardRevenueRow struct {
	Currency      string `json:"currency"`
	PaidMinor     int64  `json:"paid_minor"`
	WalletMinor   int64  `json:"wallet_minor"`
	RefundedMinor int64  `json:"refunded_minor"`
	OrderCount    int64  `json:"order_count"`
}

// Deliberately three separate figures rather than one "revenue": money taken
// through a provider, wallet credit spent, and money returned are different
// questions, and adding them together answers none of them.
func (q *Queries) DashboardRevenue(ctx context.Context, lookback pgtype.Interval) ([]DashboardRevenueRow, error) {
	rows, err := q.db.Query(ctx, dashboardRevenue, lookback)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DashboardRevenueRow{}
	for rows.Next() {
		var i DashboardRevenueRow
		if err := rows.Scan(
			&i.Currency,
			&i.PaidMinor,
			&i.WalletMinor,
			&i.RefundedMinor,
			&i.OrderCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const dashboardSubscriptionTotals = `-- name: DashboardSubscriptionTotals :one
SELECT
  count(*) FILTER (WHERE e.status = 'active' AND e.ends_at > now())::bigint AS active_entitlements,
  count(*) FILTER (WHERE e.status = 'limited')::bigint AS limited_entitlements,
  count(*) FILTER (WHERE e.status IN ('active', 'limited') AND e.ends_at <= now())::bigint AS lapsed_entitlements,
  count(*) FILTER (
    WHERE e.status = 'active' AND e.ends_at BETWEEN now() AND now() + $1::interval
  )::bigint AS renewals_due,
  COALESCE(sum((s.observed_state->>'usedTrafficBytes')::bigint), 0)::bigint AS observed_traffic_bytes
FROM entitlements e
LEFT JOIN subscriptions s ON s.id = e.subscription_id
`

type DashboardSubscriptionTotalsRow struct {
	ActiveEntitlements   int64 `json:"active_entitlements"`
	LimitedEntitlements  int64 `json:"limited_entitlements"`
	LapsedEntitlements   int64 `json:"lapsed_entitlements"`
	RenewalsDue          int64 `json:"renewals_due"`
	ObservedTrafficBytes int64 `json:"observed_traffic_bytes"`
}

func (q *Queries) DashboardSubscriptionTotals(ctx context.Context, lookback pgtype.Interval) (DashboardSubscriptionTotalsRow, error) {
	row := q.db.QueryRow(ctx, dashboardSubscriptionTotals, lookback)
	var i DashboardSubscriptionTotalsRow
	err := row.Scan(
		&i.ActiveEntitlements,
		&i.LimitedEntitlements,
		&i.LapsedEntitlements,
		&i.RenewalsDue,
		&i.ObservedTrafficBytes,
	)
	return i, err
}

const dashboardSupportTotals = `-- name: DashboardSupportTotals :one
SELECT
  count(*) FILTER (WHERE status = 'open')::bigint AS open_tickets,
  count(*) FILTER (
    WHERE status = 'open' AND last_message_at < now() - $1::interval
  )::bigint AS stale_tickets
FROM support_tickets
`

type DashboardSupportTotalsRow struct {
	OpenTickets  int64 `json:"open_tickets"`
	StaleTickets int64 `json:"stale_tickets"`
}

func (q *Queries) DashboardSupportTotals(ctx context.Context, staleAfter pgtype.Interval) (DashboardSupportTotalsRow, error) {
	row := q.db.QueryRow(ctx, dashboardSupportTotals, staleAfter)
	var i DashboardSupportTotalsRow
	err := row.Scan(&i.OpenTickets, &i.StaleTickets)
	return i, err
}

const dashboardWebhookHealth = `-- name: DashboardWebhookHealth :one
SELECT
  count(*) FILTER (WHERE status = 'received')::bigint AS unprocessed,
  count(*) FILTER (WHERE status = 'failed')::bigint AS failed,
  count(*) FILTER (WHERE NOT signature_valid)::bigint AS unverified
FROM provider_webhook_events
WHERE received_at >= now() - $1::interval
`

type DashboardWebhookHealthRow struct {
	Unprocessed int64 `json:"unprocessed"`
	Failed      int64 `json:"failed"`
	Unverified  int64 `json:"unverified"`
}

func (q *Queries) DashboardWebhookHealth(ctx context.Context, lookback pgtype.Interval) (DashboardWebhookHealthRow, error) {
	row := q.db.QueryRow(ctx, dashboardWebhookHealth, lookback)
	var i DashboardWebhookHealthRow
	err := row.Scan(&i.Unprocessed, &i.Failed, &i.Unverified)
	return i, err
}

const exportFinanceRows = `-- name: ExportFinanceRows :many
SELECT
  o.id AS order_id,
  o.created_at,
  o.updated_at,
  o.user_id,
  o.state,
  o.operation,
  o.currency,
  o.subtotal_minor,
  o.discount_minor,
  o.wallet_minor,
  o.external_minor,
  o.paid_minor,
  o.refunded_minor,
  (
    SELECT string_agg(DISTINCT i.provider, '|' ORDER BY i.provider)
    FROM payment_intents i WHERE i.order_id = o.id
  ) AS providers
FROM orders o
WHERE ($1::timestamptz IS NULL OR o.created_at >= $1)
  AND ($2::timestamptz IS NULL OR o.created_at < $2)
  AND ($3::text IS NULL OR o.state = $3)
  AND (
    $4::timestamptz IS NULL
    OR (o.created_at, o.id) < ($4::timestamptz, $5::uuid)
  )
ORDER BY o.created_at DESC, o.id DESC
LIMIT $6
`

type ExportFinanceRowsParams struct {
	CreatedFrom     pgtype.Timestamptz `json:"created_from"`
	CreatedTo       pgtype.Timestamptz `json:"created_to"`
	State           pgtype.Text        `json:"state"`
	CursorCreatedAt pgtype.Timestamptz `json:"cursor_created_at"`
	CursorID        pgtype.UUID        `json:"cursor_id"`
	PageSize        int32              `json:"page_size"`
}

type ExportFinanceRowsRow struct {
	OrderID       pgtype.UUID        `json:"order_id"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
	UserID        pgtype.UUID        `json:"user_id"`
	State         string             `json:"state"`
	Operation     string             `json:"operation"`
	Currency      string             `json:"currency"`
	SubtotalMinor int64              `json:"subtotal_minor"`
	DiscountMinor int64              `json:"discount_minor"`
	WalletMinor   int64              `json:"wallet_minor"`
	ExternalMinor int64              `json:"external_minor"`
	PaidMinor     int64              `json:"paid_minor"`
	RefundedMinor int64              `json:"refunded_minor"`
	Providers     []byte             `json:"providers"`
}

// The CSV export's source. Column order here is the column order in the file,
// and the schema is stable: a new column is appended, never inserted, so a
// spreadsheet or importer built against an older export keeps working.
func (q *Queries) ExportFinanceRows(ctx context.Context, arg ExportFinanceRowsParams) ([]ExportFinanceRowsRow, error) {
	rows, err := q.db.Query(ctx, exportFinanceRows,
		arg.CreatedFrom,
		arg.CreatedTo,
		arg.State,
		arg.CursorCreatedAt,
		arg.CursorID,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ExportFinanceRowsRow{}
	for rows.Next() {
		var i ExportFinanceRowsRow
		if err := rows.Scan(
			&i.OrderID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.UserID,
			&i.State,
			&i.Operation,
			&i.Currency,
			&i.SubtotalMinor,
			&i.DiscountMinor,
			&i.WalletMinor,
			&i.ExternalMinor,
			&i.PaidMinor,
			&i.RefundedMinor,
			&i.Providers,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getBulkOperation = `-- name: GetBulkOperation :one
SELECT id, kind, status, requested_by, reason, parameters, total_count, succeeded_count, failed_count, skipped_count, idempotency_key, created_at, updated_at, completed_at FROM bulk_operations WHERE id = $1
`

func (q *Queries) GetBulkOperation(ctx context.Context, id pgtype.UUID) (BulkOperation, error) {
	row := q.db.QueryRow(ctx, getBulkOperation, id)
	var i BulkOperation
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.Status,
		&i.RequestedBy,
		&i.Reason,
		&i.Parameters,
		&i.TotalCount,
		&i.SucceededCount,
		&i.FailedCount,
		&i.SkippedCount,
		&i.IdempotencyKey,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const getBulkOperationByIdempotency = `-- name: GetBulkOperationByIdempotency :one
SELECT id, kind, status, requested_by, reason, parameters, total_count, succeeded_count, failed_count, skipped_count, idempotency_key, created_at, updated_at, completed_at FROM bulk_operations WHERE idempotency_key = $1
`

func (q *Queries) GetBulkOperationByIdempotency(ctx context.Context, idempotencyKey string) (BulkOperation, error) {
	row := q.db.QueryRow(ctx, getBulkOperationByIdempotency, idempotencyKey)
	var i BulkOperation
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.Status,
		&i.RequestedBy,
		&i.Reason,
		&i.Parameters,
		&i.TotalCount,
		&i.SucceededCount,
		&i.FailedCount,
		&i.SkippedCount,
		&i.IdempotencyKey,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const getCommerceSettings = `-- name: GetCommerceSettings :one


SELECT singleton, topup_enabled, topup_currency, topup_presets_minor, topup_minimum_minor, topup_maximum_minor, topup_window_seconds, topup_window_limit_minor, multi_subscription_enabled, max_subscriptions_per_customer, updated_at, updated_by FROM commerce_settings WHERE singleton
`

// Operator panel queries for v0.7: settings, dashboard, customer and finance
// operations, fulfillment and job diagnostics, and bulk actions.
//
// Everything here is read or operated by an authenticated operator whose
// permissions were already checked in `internal/rbac`. The queries carry no
// authorization of their own precisely so there is only one place that decides
// what a role may do.
// ---------------------------------------------------------------------------
// Commerce settings
// ---------------------------------------------------------------------------
func (q *Queries) GetCommerceSettings(ctx context.Context) (CommerceSetting, error) {
	row := q.db.QueryRow(ctx, getCommerceSettings)
	var i CommerceSetting
	err := row.Scan(
		&i.Singleton,
		&i.TopupEnabled,
		&i.TopupCurrency,
		&i.TopupPresetsMinor,
		&i.TopupMinimumMinor,
		&i.TopupMaximumMinor,
		&i.TopupWindowSeconds,
		&i.TopupWindowLimitMinor,
		&i.MultiSubscriptionEnabled,
		&i.MaxSubscriptionsPerCustomer,
		&i.UpdatedAt,
		&i.UpdatedBy,
	)
	return i, err
}

const getCustomerOverview = `-- name: GetCustomerOverview :one
SELECT
  u.id, u.status, u.locale, u.created_at, u.updated_at, u.timezone, u.suspended_at, u.deleted_at, u.anonymized_at, u.retention_until,
  r.telegram_id,
  (SELECT count(*) FROM subscriptions s WHERE s.user_id = u.id AND s.status = 'active')::bigint AS active_subscriptions,
  (SELECT count(*) FROM orders o WHERE o.user_id = u.id)::bigint AS order_count,
  (SELECT count(*) FROM support_tickets t WHERE t.user_id = u.id AND t.status = 'open')::bigint AS open_tickets,
  (SELECT count(*) FROM referral_attributions a WHERE a.referrer_user_id = u.id)::bigint AS referral_count,
  (SELECT count(*) FROM blocklist_matches m WHERE m.user_id = u.id AND m.status IN ('open', 'appealed'))::bigint AS open_flags,
  EXISTS (SELECT 1 FROM blocklist_allowlist a WHERE a.user_id = u.id) AS allowlisted
FROM users u
LEFT JOIN remnawave_users r ON r.user_id = u.id
WHERE u.id = $1
`

type GetCustomerOverviewRow struct {
	User                User        `json:"user"`
	TelegramID          pgtype.Int8 `json:"telegram_id"`
	ActiveSubscriptions int64       `json:"active_subscriptions"`
	OrderCount          int64       `json:"order_count"`
	OpenTickets         int64       `json:"open_tickets"`
	ReferralCount       int64       `json:"referral_count"`
	OpenFlags           int64       `json:"open_flags"`
	Allowlisted         bool        `json:"allowlisted"`
}

// One round trip for the profile header: the customer, their Telegram mapping,
// and the counts the page shows before any tab is opened.
func (q *Queries) GetCustomerOverview(ctx context.Context, id pgtype.UUID) (GetCustomerOverviewRow, error) {
	row := q.db.QueryRow(ctx, getCustomerOverview, id)
	var i GetCustomerOverviewRow
	err := row.Scan(
		&i.User.ID,
		&i.User.Status,
		&i.User.Locale,
		&i.User.CreatedAt,
		&i.User.UpdatedAt,
		&i.User.Timezone,
		&i.User.SuspendedAt,
		&i.User.DeletedAt,
		&i.User.AnonymizedAt,
		&i.User.RetentionUntil,
		&i.TelegramID,
		&i.ActiveSubscriptions,
		&i.OrderCount,
		&i.OpenTickets,
		&i.ReferralCount,
		&i.OpenFlags,
		&i.Allowlisted,
	)
	return i, err
}

const getFulfillmentOperation = `-- name: GetFulfillmentOperation :one
SELECT id, entitlement_id, operation, status, idempotency_key, correlation_id, desired_state, attempt_count, next_attempt_at, last_error_code, created_at, updated_at, completed_at FROM fulfillment_operations WHERE id = $1
`

func (q *Queries) GetFulfillmentOperation(ctx context.Context, id pgtype.UUID) (FulfillmentOperation, error) {
	row := q.db.QueryRow(ctx, getFulfillmentOperation, id)
	var i FulfillmentOperation
	err := row.Scan(
		&i.ID,
		&i.EntitlementID,
		&i.Operation,
		&i.Status,
		&i.IdempotencyKey,
		&i.CorrelationID,
		&i.DesiredState,
		&i.AttemptCount,
		&i.NextAttemptAt,
		&i.LastErrorCode,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const getPaymentProviderSettings = `-- name: GetPaymentProviderSettings :one
SELECT provider, merchant_id, enabled, display_order, credentials_ciphertext, webhook_secret_ciphertext, recurring_enabled, recurring_test_status, recurring_tested_at, connection_status, connection_checked_at, connection_error_code, webhook_status, webhook_last_event_at, webhook_last_error_code, created_at, updated_at, updated_by FROM payment_provider_settings
WHERE provider = $1 AND merchant_id = $2
`

type GetPaymentProviderSettingsParams struct {
	Provider   string `json:"provider"`
	MerchantID string `json:"merchant_id"`
}

func (q *Queries) GetPaymentProviderSettings(ctx context.Context, arg GetPaymentProviderSettingsParams) (PaymentProviderSetting, error) {
	row := q.db.QueryRow(ctx, getPaymentProviderSettings, arg.Provider, arg.MerchantID)
	var i PaymentProviderSetting
	err := row.Scan(
		&i.Provider,
		&i.MerchantID,
		&i.Enabled,
		&i.DisplayOrder,
		&i.CredentialsCiphertext,
		&i.WebhookSecretCiphertext,
		&i.RecurringEnabled,
		&i.RecurringTestStatus,
		&i.RecurringTestedAt,
		&i.ConnectionStatus,
		&i.ConnectionCheckedAt,
		&i.ConnectionErrorCode,
		&i.WebhookStatus,
		&i.WebhookLastEventAt,
		&i.WebhookLastErrorCode,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UpdatedBy,
	)
	return i, err
}

const getPlanAdmin = `-- name: GetPlanAdmin :one
SELECT id, code, kind, visible, sort_order, created_at, archived_at, max_concurrent_per_customer FROM plans WHERE id = $1
`

func (q *Queries) GetPlanAdmin(ctx context.Context, id pgtype.UUID) (Plan, error) {
	row := q.db.QueryRow(ctx, getPlanAdmin, id)
	var i Plan
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Kind,
		&i.Visible,
		&i.SortOrder,
		&i.CreatedAt,
		&i.ArchivedAt,
		&i.MaxConcurrentPerCustomer,
	)
	return i, err
}

const getPromotionAdmin = `-- name: GetPromotionAdmin :one
SELECT id, code, kind, value, currency, starts_at, ends_at, redemption_limit, per_customer_limit, eligibility, active, created_at, stackable, precedence FROM promotions WHERE id = $1
`

func (q *Queries) GetPromotionAdmin(ctx context.Context, id pgtype.UUID) (Promotion, error) {
	row := q.db.QueryRow(ctx, getPromotionAdmin, id)
	var i Promotion
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Kind,
		&i.Value,
		&i.Currency,
		&i.StartsAt,
		&i.EndsAt,
		&i.RedemptionLimit,
		&i.PerCustomerLimit,
		&i.Eligibility,
		&i.Active,
		&i.CreatedAt,
		&i.Stackable,
		&i.Precedence,
	)
	return i, err
}

const getWebhookEventForReplay = `-- name: GetWebhookEventForReplay :one
SELECT id, provider, provider_event_id, signature_valid, body_sha256, raw_body, headers, status, error_code, received_at, processed_at, retain_until FROM provider_webhook_events WHERE id = $1
`

func (q *Queries) GetWebhookEventForReplay(ctx context.Context, id pgtype.UUID) (ProviderWebhookEvent, error) {
	row := q.db.QueryRow(ctx, getWebhookEventForReplay, id)
	var i ProviderWebhookEvent
	err := row.Scan(
		&i.ID,
		&i.Provider,
		&i.ProviderEventID,
		&i.SignatureValid,
		&i.BodySha256,
		&i.RawBody,
		&i.Headers,
		&i.Status,
		&i.ErrorCode,
		&i.ReceivedAt,
		&i.ProcessedAt,
		&i.RetainUntil,
	)
	return i, err
}

const insertBulkOperationItem = `-- name: InsertBulkOperationItem :exec
INSERT INTO bulk_operation_items (operation_id, position, target_type, target_id)
VALUES ($1, $2, $3, $4)
ON CONFLICT (operation_id, position) DO NOTHING
`

type InsertBulkOperationItemParams struct {
	OperationID pgtype.UUID `json:"operation_id"`
	Position    int32       `json:"position"`
	TargetType  string      `json:"target_type"`
	TargetID    pgtype.UUID `json:"target_id"`
}

func (q *Queries) InsertBulkOperationItem(ctx context.Context, arg InsertBulkOperationItemParams) error {
	_, err := q.db.Exec(ctx, insertBulkOperationItem,
		arg.OperationID,
		arg.Position,
		arg.TargetType,
		arg.TargetID,
	)
	return err
}

const listAddonPrices = `-- name: ListAddonPrices :many
SELECT addon_version_id, currency, amount_minor FROM addon_prices WHERE addon_version_id = $1 ORDER BY currency
`

func (q *Queries) ListAddonPrices(ctx context.Context, addonVersionID pgtype.UUID) ([]AddonPrice, error) {
	rows, err := q.db.Query(ctx, listAddonPrices, addonVersionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AddonPrice{}
	for rows.Next() {
		var i AddonPrice
		if err := rows.Scan(&i.AddonVersionID, &i.Currency, &i.AmountMinor); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAddonVersions = `-- name: ListAddonVersions :many
SELECT id, addon_id, version, traffic_bytes, device_slots, remnawave_squad_ids, max_quantity, proration, created_at, retired_at FROM addon_versions WHERE addon_id = $1 ORDER BY version DESC
`

func (q *Queries) ListAddonVersions(ctx context.Context, addonID pgtype.UUID) ([]AddonVersion, error) {
	rows, err := q.db.Query(ctx, listAddonVersions, addonID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AddonVersion{}
	for rows.Next() {
		var i AddonVersion
		if err := rows.Scan(
			&i.ID,
			&i.AddonID,
			&i.Version,
			&i.TrafficBytes,
			&i.DeviceSlots,
			&i.RemnawaveSquadIds,
			&i.MaxQuantity,
			&i.Proration,
			&i.CreatedAt,
			&i.RetiredAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAddonsAdmin = `-- name: ListAddonsAdmin :many
SELECT
  a.id, a.code, a.kind, a.visible, a.sort_order, a.created_at, a.archived_at,
  (SELECT max(version) FROM addon_versions v WHERE v.addon_id = a.id)::integer AS latest_version
FROM addons a
ORDER BY a.sort_order, a.code
`

type ListAddonsAdminRow struct {
	Addon         Addon `json:"addon"`
	LatestVersion int32 `json:"latest_version"`
}

func (q *Queries) ListAddonsAdmin(ctx context.Context) ([]ListAddonsAdminRow, error) {
	rows, err := q.db.Query(ctx, listAddonsAdmin)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAddonsAdminRow{}
	for rows.Next() {
		var i ListAddonsAdminRow
		if err := rows.Scan(
			&i.Addon.ID,
			&i.Addon.Code,
			&i.Addon.Kind,
			&i.Addon.Visible,
			&i.Addon.SortOrder,
			&i.Addon.CreatedAt,
			&i.Addon.ArchivedAt,
			&i.LatestVersion,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBulkOperationItems = `-- name: ListBulkOperationItems :many
SELECT operation_id, position, target_type, target_id, status, error_code, processed_at FROM bulk_operation_items
WHERE operation_id = $1
ORDER BY position
LIMIT $2
`

type ListBulkOperationItemsParams struct {
	OperationID pgtype.UUID `json:"operation_id"`
	PageSize    int32       `json:"page_size"`
}

func (q *Queries) ListBulkOperationItems(ctx context.Context, arg ListBulkOperationItemsParams) ([]BulkOperationItem, error) {
	rows, err := q.db.Query(ctx, listBulkOperationItems, arg.OperationID, arg.PageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BulkOperationItem{}
	for rows.Next() {
		var i BulkOperationItem
		if err := rows.Scan(
			&i.OperationID,
			&i.Position,
			&i.TargetType,
			&i.TargetID,
			&i.Status,
			&i.ErrorCode,
			&i.ProcessedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBulkOperations = `-- name: ListBulkOperations :many
SELECT id, kind, status, requested_by, reason, parameters, total_count, succeeded_count, failed_count, skipped_count, idempotency_key, created_at, updated_at, completed_at FROM bulk_operations ORDER BY created_at DESC LIMIT $1
`

func (q *Queries) ListBulkOperations(ctx context.Context, pageSize int32) ([]BulkOperation, error) {
	rows, err := q.db.Query(ctx, listBulkOperations, pageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BulkOperation{}
	for rows.Next() {
		var i BulkOperation
		if err := rows.Scan(
			&i.ID,
			&i.Kind,
			&i.Status,
			&i.RequestedBy,
			&i.Reason,
			&i.Parameters,
			&i.TotalCount,
			&i.SucceededCount,
			&i.FailedCount,
			&i.SkippedCount,
			&i.IdempotencyKey,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CompletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCustomerConsents = `-- name: ListCustomerConsents :many
SELECT DISTINCT ON (purpose) id, user_id, purpose, granted, policy_version, source, occurred_at, request_id
FROM consent_records
WHERE user_id = $1
ORDER BY purpose, occurred_at DESC
`

func (q *Queries) ListCustomerConsents(ctx context.Context, userID pgtype.UUID) ([]ConsentRecord, error) {
	rows, err := q.db.Query(ctx, listCustomerConsents, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ConsentRecord{}
	for rows.Next() {
		var i ConsentRecord
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Purpose,
			&i.Granted,
			&i.PolicyVersion,
			&i.Source,
			&i.OccurredAt,
			&i.RequestID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCustomerLedgerEntries = `-- name: ListCustomerLedgerEntries :many
SELECT e.id, e.transaction_id, e.account_type, e.user_id, e.currency, e.amount_minor, e.expires_at, e.created_at, t.type, t.reference_type, t.reference_id, t.reason
FROM ledger_entries e
JOIN ledger_transactions t ON t.id = e.transaction_id
WHERE e.account_type = 'customer_wallet' AND e.user_id = $1
ORDER BY e.created_at DESC
LIMIT $2
`

type ListCustomerLedgerEntriesParams struct {
	UserID   pgtype.UUID `json:"user_id"`
	PageSize int32       `json:"page_size"`
}

type ListCustomerLedgerEntriesRow struct {
	LedgerEntry   LedgerEntry `json:"ledger_entry"`
	Type          string      `json:"type"`
	ReferenceType string      `json:"reference_type"`
	ReferenceID   string      `json:"reference_id"`
	Reason        pgtype.Text `json:"reason"`
}

func (q *Queries) ListCustomerLedgerEntries(ctx context.Context, arg ListCustomerLedgerEntriesParams) ([]ListCustomerLedgerEntriesRow, error) {
	rows, err := q.db.Query(ctx, listCustomerLedgerEntries, arg.UserID, arg.PageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCustomerLedgerEntriesRow{}
	for rows.Next() {
		var i ListCustomerLedgerEntriesRow
		if err := rows.Scan(
			&i.LedgerEntry.ID,
			&i.LedgerEntry.TransactionID,
			&i.LedgerEntry.AccountType,
			&i.LedgerEntry.UserID,
			&i.LedgerEntry.Currency,
			&i.LedgerEntry.AmountMinor,
			&i.LedgerEntry.ExpiresAt,
			&i.LedgerEntry.CreatedAt,
			&i.Type,
			&i.ReferenceType,
			&i.ReferenceID,
			&i.Reason,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCustomerOrders = `-- name: ListCustomerOrders :many
SELECT id, user_id, state, operation, currency, subtotal_minor, discount_minor, wallet_minor, external_minor, paid_minor, refunded_minor, idempotency_key, expires_at, created_at, updated_at, subscription_id, selected_squad_ids FROM orders
WHERE user_id = $1
ORDER BY created_at DESC
LIMIT $2
`

type ListCustomerOrdersParams struct {
	UserID   pgtype.UUID `json:"user_id"`
	PageSize int32       `json:"page_size"`
}

func (q *Queries) ListCustomerOrders(ctx context.Context, arg ListCustomerOrdersParams) ([]Order, error) {
	rows, err := q.db.Query(ctx, listCustomerOrders, arg.UserID, arg.PageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Order{}
	for rows.Next() {
		var i Order
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.State,
			&i.Operation,
			&i.Currency,
			&i.SubtotalMinor,
			&i.DiscountMinor,
			&i.WalletMinor,
			&i.ExternalMinor,
			&i.PaidMinor,
			&i.RefundedMinor,
			&i.IdempotencyKey,
			&i.ExpiresAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.SubscriptionID,
			&i.SelectedSquadIds,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCustomerSubscriptionsDetailed = `-- name: ListCustomerSubscriptionsDetailed :many
SELECT
  s.id, s.user_id, s.slot, s.label, s.status, s.remnawave_user_id, s.remnawave_username, s.observed_state, s.reconciled_at, s.created_at, s.updated_at, s.closed_at,
  e.id AS entitlement_id,
  e.status AS entitlement_status,
  e.starts_at AS entitlement_starts_at,
  e.ends_at AS entitlement_ends_at,
  e.traffic_allowance_bytes,
  e.device_limit,
  e.remnawave_squad_ids,
  p.code AS plan_code,
  v.version AS plan_version
FROM subscriptions s
LEFT JOIN LATERAL (
  SELECT en.id, en.user_id, en.order_id, en.plan_version_id, en.status, en.starts_at, en.ends_at, en.traffic_allowance_bytes, en.device_limit, en.remnawave_squad_ids, en.remnawave_user_id, en.observed_state, en.reconciled_at, en.created_at, en.updated_at, en.subscription_id FROM entitlements en
  WHERE en.subscription_id = s.id AND en.status IN ('pending', 'active', 'limited', 'disabled')
  ORDER BY en.ends_at DESC
  LIMIT 1
) e ON true
LEFT JOIN plan_versions v ON v.id = e.plan_version_id
LEFT JOIN plans p ON p.id = v.plan_id
WHERE s.user_id = $1
ORDER BY s.slot
`

type ListCustomerSubscriptionsDetailedRow struct {
	Subscription          Subscription       `json:"subscription"`
	EntitlementID         pgtype.UUID        `json:"entitlement_id"`
	EntitlementStatus     string             `json:"entitlement_status"`
	EntitlementStartsAt   pgtype.Timestamptz `json:"entitlement_starts_at"`
	EntitlementEndsAt     pgtype.Timestamptz `json:"entitlement_ends_at"`
	TrafficAllowanceBytes pgtype.Int8        `json:"traffic_allowance_bytes"`
	DeviceLimit           pgtype.Int4        `json:"device_limit"`
	RemnawaveSquadIds     []pgtype.UUID      `json:"remnawave_squad_ids"`
	PlanCode              pgtype.Text        `json:"plan_code"`
	PlanVersion           pgtype.Int4        `json:"plan_version"`
}

// Every concurrent subscription with the entitlement currently governing it, so
// the panel can offer independent lifecycle actions per subscription rather
// than assuming one per customer.
//
// The entitlement columns are selected individually rather than embedded: a
// subscription that has never been provisioned has no entitlement at all, and
// an embedded struct would have to scan those nulls into non-nullable fields.
func (q *Queries) ListCustomerSubscriptionsDetailed(ctx context.Context, userID pgtype.UUID) ([]ListCustomerSubscriptionsDetailedRow, error) {
	rows, err := q.db.Query(ctx, listCustomerSubscriptionsDetailed, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCustomerSubscriptionsDetailedRow{}
	for rows.Next() {
		var i ListCustomerSubscriptionsDetailedRow
		if err := rows.Scan(
			&i.Subscription.ID,
			&i.Subscription.UserID,
			&i.Subscription.Slot,
			&i.Subscription.Label,
			&i.Subscription.Status,
			&i.Subscription.RemnawaveUserID,
			&i.Subscription.RemnawaveUsername,
			&i.Subscription.ObservedState,
			&i.Subscription.ReconciledAt,
			&i.Subscription.CreatedAt,
			&i.Subscription.UpdatedAt,
			&i.Subscription.ClosedAt,
			&i.EntitlementID,
			&i.EntitlementStatus,
			&i.EntitlementStartsAt,
			&i.EntitlementEndsAt,
			&i.TrafficAllowanceBytes,
			&i.DeviceLimit,
			&i.RemnawaveSquadIds,
			&i.PlanCode,
			&i.PlanVersion,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCustomerSupportTickets = `-- name: ListCustomerSupportTickets :many
SELECT id, user_id, status, created_at, updated_at, subject, priority, last_message_at, customer_unread_count, closed_at FROM support_tickets WHERE user_id = $1 ORDER BY updated_at DESC LIMIT $2
`

type ListCustomerSupportTicketsParams struct {
	UserID   pgtype.UUID `json:"user_id"`
	PageSize int32       `json:"page_size"`
}

func (q *Queries) ListCustomerSupportTickets(ctx context.Context, arg ListCustomerSupportTicketsParams) ([]SupportTicket, error) {
	rows, err := q.db.Query(ctx, listCustomerSupportTickets, arg.UserID, arg.PageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SupportTicket{}
	for rows.Next() {
		var i SupportTicket
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Subject,
			&i.Priority,
			&i.LastMessageAt,
			&i.CustomerUnreadCount,
			&i.ClosedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFulfillmentHistoryForOperation = `-- name: ListFulfillmentHistoryForOperation :many
SELECT id, operation_id, status, correlation_id, request_summary, response_summary, error_code, occurred_at FROM fulfillment_history WHERE operation_id = $1 ORDER BY occurred_at
`

func (q *Queries) ListFulfillmentHistoryForOperation(ctx context.Context, operationID pgtype.UUID) ([]FulfillmentHistory, error) {
	rows, err := q.db.Query(ctx, listFulfillmentHistoryForOperation, operationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FulfillmentHistory{}
	for rows.Next() {
		var i FulfillmentHistory
		if err := rows.Scan(
			&i.ID,
			&i.OperationID,
			&i.Status,
			&i.CorrelationID,
			&i.RequestSummary,
			&i.ResponseSummary,
			&i.ErrorCode,
			&i.OccurredAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOpenDriftsDetailed = `-- name: ListOpenDriftsDetailed :many
SELECT d.id, d.entitlement_id, d.kind, d.expected, d.observed, d.status, d.detected_at, d.resolved_at, e.user_id, e.subscription_id, e.remnawave_user_id
FROM entitlement_drifts d
JOIN entitlements e ON e.id = d.entitlement_id
WHERE d.status = 'open'
ORDER BY d.detected_at DESC
LIMIT $1
`

type ListOpenDriftsDetailedRow struct {
	EntitlementDrift EntitlementDrift `json:"entitlement_drift"`
	UserID           pgtype.UUID      `json:"user_id"`
	SubscriptionID   pgtype.UUID      `json:"subscription_id"`
	RemnawaveUserID  pgtype.Int8      `json:"remnawave_user_id"`
}

func (q *Queries) ListOpenDriftsDetailed(ctx context.Context, pageSize int32) ([]ListOpenDriftsDetailedRow, error) {
	rows, err := q.db.Query(ctx, listOpenDriftsDetailed, pageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListOpenDriftsDetailedRow{}
	for rows.Next() {
		var i ListOpenDriftsDetailedRow
		if err := rows.Scan(
			&i.EntitlementDrift.ID,
			&i.EntitlementDrift.EntitlementID,
			&i.EntitlementDrift.Kind,
			&i.EntitlementDrift.Expected,
			&i.EntitlementDrift.Observed,
			&i.EntitlementDrift.Status,
			&i.EntitlementDrift.DetectedAt,
			&i.EntitlementDrift.ResolvedAt,
			&i.UserID,
			&i.SubscriptionID,
			&i.RemnawaveUserID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrderPaymentIntents = `-- name: ListOrderPaymentIntents :many
SELECT id, order_id, provider, status, amount_minor, currency, provider_reference, checkout_url, idempotency_key, capabilities, receipt_metadata, created_at, updated_at FROM payment_intents WHERE order_id = $1 ORDER BY created_at
`

func (q *Queries) ListOrderPaymentIntents(ctx context.Context, orderID pgtype.UUID) ([]PaymentIntent, error) {
	rows, err := q.db.Query(ctx, listOrderPaymentIntents, orderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PaymentIntent{}
	for rows.Next() {
		var i PaymentIntent
		if err := rows.Scan(
			&i.ID,
			&i.OrderID,
			&i.Provider,
			&i.Status,
			&i.AmountMinor,
			&i.Currency,
			&i.ProviderReference,
			&i.CheckoutUrl,
			&i.IdempotencyKey,
			&i.Capabilities,
			&i.ReceiptMetadata,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPaymentEventsForIntent = `-- name: ListPaymentEventsForIntent :many
SELECT id, payment_intent_id, type, previous_status, status, amount_minor, currency, provider_event_id, details, occurred_at FROM payment_events WHERE payment_intent_id = $1 ORDER BY occurred_at
`

func (q *Queries) ListPaymentEventsForIntent(ctx context.Context, paymentIntentID pgtype.UUID) ([]PaymentEvent, error) {
	rows, err := q.db.Query(ctx, listPaymentEventsForIntent, paymentIntentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PaymentEvent{}
	for rows.Next() {
		var i PaymentEvent
		if err := rows.Scan(
			&i.ID,
			&i.PaymentIntentID,
			&i.Type,
			&i.PreviousStatus,
			&i.Status,
			&i.AmountMinor,
			&i.Currency,
			&i.ProviderEventID,
			&i.Details,
			&i.OccurredAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPaymentProviderSettings = `-- name: ListPaymentProviderSettings :many

SELECT provider, merchant_id, enabled, display_order, credentials_ciphertext, webhook_secret_ciphertext, recurring_enabled, recurring_test_status, recurring_tested_at, connection_status, connection_checked_at, connection_error_code, webhook_status, webhook_last_event_at, webhook_last_error_code, created_at, updated_at, updated_by FROM payment_provider_settings ORDER BY display_order, provider, merchant_id
`

// ---------------------------------------------------------------------------
// Payment provider configuration
// ---------------------------------------------------------------------------
func (q *Queries) ListPaymentProviderSettings(ctx context.Context) ([]PaymentProviderSetting, error) {
	rows, err := q.db.Query(ctx, listPaymentProviderSettings)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PaymentProviderSetting{}
	for rows.Next() {
		var i PaymentProviderSetting
		if err := rows.Scan(
			&i.Provider,
			&i.MerchantID,
			&i.Enabled,
			&i.DisplayOrder,
			&i.CredentialsCiphertext,
			&i.WebhookSecretCiphertext,
			&i.RecurringEnabled,
			&i.RecurringTestStatus,
			&i.RecurringTestedAt,
			&i.ConnectionStatus,
			&i.ConnectionCheckedAt,
			&i.ConnectionErrorCode,
			&i.WebhookStatus,
			&i.WebhookLastEventAt,
			&i.WebhookLastErrorCode,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.UpdatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPendingBulkOperationItems = `-- name: ListPendingBulkOperationItems :many
SELECT operation_id, position, target_type, target_id, status, error_code, processed_at FROM bulk_operation_items
WHERE operation_id = $1 AND status = 'pending'
ORDER BY position
LIMIT $2
`

type ListPendingBulkOperationItemsParams struct {
	OperationID pgtype.UUID `json:"operation_id"`
	PageSize    int32       `json:"page_size"`
}

func (q *Queries) ListPendingBulkOperationItems(ctx context.Context, arg ListPendingBulkOperationItemsParams) ([]BulkOperationItem, error) {
	rows, err := q.db.Query(ctx, listPendingBulkOperationItems, arg.OperationID, arg.PageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BulkOperationItem{}
	for rows.Next() {
		var i BulkOperationItem
		if err := rows.Scan(
			&i.OperationID,
			&i.Position,
			&i.TargetType,
			&i.TargetID,
			&i.Status,
			&i.ErrorCode,
			&i.ProcessedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPlanLocalizations = `-- name: ListPlanLocalizations :many
SELECT plan_id, locale, name, description FROM plan_localizations WHERE plan_id = $1 ORDER BY locale
`

func (q *Queries) ListPlanLocalizations(ctx context.Context, planID pgtype.UUID) ([]PlanLocalization, error) {
	rows, err := q.db.Query(ctx, listPlanLocalizations, planID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PlanLocalization{}
	for rows.Next() {
		var i PlanLocalization
		if err := rows.Scan(
			&i.PlanID,
			&i.Locale,
			&i.Name,
			&i.Description,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPlanPrices = `-- name: ListPlanPrices :many
SELECT plan_version_id, currency, amount_minor FROM plan_prices WHERE plan_version_id = $1 ORDER BY currency
`

func (q *Queries) ListPlanPrices(ctx context.Context, planVersionID pgtype.UUID) ([]PlanPrice, error) {
	rows, err := q.db.Query(ctx, listPlanPrices, planVersionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PlanPrice{}
	for rows.Next() {
		var i PlanPrice
		if err := rows.Scan(&i.PlanVersionID, &i.Currency, &i.AmountMinor); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPlanVersions = `-- name: ListPlanVersions :many
SELECT id, plan_id, version, billing_period, duration_seconds, traffic_allowance_bytes, device_limit, remnawave_squad_ids, upgrade_policy, downgrade_policy, cancellation_policy, recurring_capable, created_at, retired_at, grace_period_seconds, trial_eligibility, squad_selection, min_selectable_squads, max_selectable_squads FROM plan_versions WHERE plan_id = $1 ORDER BY version DESC
`

func (q *Queries) ListPlanVersions(ctx context.Context, planID pgtype.UUID) ([]PlanVersion, error) {
	rows, err := q.db.Query(ctx, listPlanVersions, planID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PlanVersion{}
	for rows.Next() {
		var i PlanVersion
		if err := rows.Scan(
			&i.ID,
			&i.PlanID,
			&i.Version,
			&i.BillingPeriod,
			&i.DurationSeconds,
			&i.TrafficAllowanceBytes,
			&i.DeviceLimit,
			&i.RemnawaveSquadIds,
			&i.UpgradePolicy,
			&i.DowngradePolicy,
			&i.CancellationPolicy,
			&i.RecurringCapable,
			&i.CreatedAt,
			&i.RetiredAt,
			&i.GracePeriodSeconds,
			&i.TrialEligibility,
			&i.SquadSelection,
			&i.MinSelectableSquads,
			&i.MaxSelectableSquads,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPlansAdmin = `-- name: ListPlansAdmin :many

SELECT
  p.id, p.code, p.kind, p.visible, p.sort_order, p.created_at, p.archived_at, p.max_concurrent_per_customer,
  (SELECT max(version) FROM plan_versions v WHERE v.plan_id = p.id)::integer AS latest_version,
  (SELECT count(*) FROM order_lines l WHERE l.plan_id = p.id)::bigint AS order_line_count
FROM plans p
ORDER BY p.sort_order, p.code
`

type ListPlansAdminRow struct {
	Plan           Plan  `json:"plan"`
	LatestVersion  int32 `json:"latest_version"`
	OrderLineCount int64 `json:"order_line_count"`
}

// ---------------------------------------------------------------------------
// Catalogue administration
// ---------------------------------------------------------------------------
// The catalogue as an operator sees it: archived plans included, with the
// current version and how many orders reference the plan, so archiving
// something in active use is a visible decision rather than a surprise.
func (q *Queries) ListPlansAdmin(ctx context.Context) ([]ListPlansAdminRow, error) {
	rows, err := q.db.Query(ctx, listPlansAdmin)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPlansAdminRow{}
	for rows.Next() {
		var i ListPlansAdminRow
		if err := rows.Scan(
			&i.Plan.ID,
			&i.Plan.Code,
			&i.Plan.Kind,
			&i.Plan.Visible,
			&i.Plan.SortOrder,
			&i.Plan.CreatedAt,
			&i.Plan.ArchivedAt,
			&i.Plan.MaxConcurrentPerCustomer,
			&i.LatestVersion,
			&i.OrderLineCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPromoCodesForPromotion = `-- name: ListPromoCodesForPromotion :many
SELECT
  c.id, c.promotion_id, c.normalized_code, c.redemption_limit, c.active, c.created_at,
  (SELECT count(*) FROM promo_redemptions r WHERE r.promo_code_id = c.id)::bigint AS redemption_count
FROM promo_codes c
WHERE c.promotion_id = $1
ORDER BY c.created_at DESC
`

type ListPromoCodesForPromotionRow struct {
	PromoCode       PromoCode `json:"promo_code"`
	RedemptionCount int64     `json:"redemption_count"`
}

func (q *Queries) ListPromoCodesForPromotion(ctx context.Context, promotionID pgtype.UUID) ([]ListPromoCodesForPromotionRow, error) {
	rows, err := q.db.Query(ctx, listPromoCodesForPromotion, promotionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPromoCodesForPromotionRow{}
	for rows.Next() {
		var i ListPromoCodesForPromotionRow
		if err := rows.Scan(
			&i.PromoCode.ID,
			&i.PromoCode.PromotionID,
			&i.PromoCode.NormalizedCode,
			&i.PromoCode.RedemptionLimit,
			&i.PromoCode.Active,
			&i.PromoCode.CreatedAt,
			&i.RedemptionCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPromotionPlans = `-- name: ListPromotionPlans :many
SELECT p.id, p.code, p.kind, p.visible, p.sort_order, p.created_at, p.archived_at, p.max_concurrent_per_customer FROM promotion_plans j JOIN plans p ON p.id = j.plan_id
WHERE j.promotion_id = $1
ORDER BY p.code
`

func (q *Queries) ListPromotionPlans(ctx context.Context, promotionID pgtype.UUID) ([]Plan, error) {
	rows, err := q.db.Query(ctx, listPromotionPlans, promotionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Plan{}
	for rows.Next() {
		var i Plan
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Kind,
			&i.Visible,
			&i.SortOrder,
			&i.CreatedAt,
			&i.ArchivedAt,
			&i.MaxConcurrentPerCustomer,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecentMaintenanceEvents = `-- name: ListRecentMaintenanceEvents :many
SELECT id, action, source, reason, actor_type, actor_id, occurred_at FROM maintenance_events ORDER BY occurred_at DESC LIMIT $1
`

func (q *Queries) ListRecentMaintenanceEvents(ctx context.Context, pageSize int32) ([]MaintenanceEvent, error) {
	rows, err := q.db.Query(ctx, listRecentMaintenanceEvents, pageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MaintenanceEvent{}
	for rows.Next() {
		var i MaintenanceEvent
		if err := rows.Scan(
			&i.ID,
			&i.Action,
			&i.Source,
			&i.Reason,
			&i.ActorType,
			&i.ActorID,
			&i.OccurredAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRefundsForOrder = `-- name: ListRefundsForOrder :many
SELECT r.id, r.payment_intent_id, r.status, r.amount_minor, r.currency, r.provider_reference, r.reason, r.idempotency_key, r.receipt_metadata, r.created_at, r.updated_at FROM refunds r
JOIN payment_intents i ON i.id = r.payment_intent_id
WHERE i.order_id = $1
ORDER BY r.created_at
`

func (q *Queries) ListRefundsForOrder(ctx context.Context, orderID pgtype.UUID) ([]Refund, error) {
	rows, err := q.db.Query(ctx, listRefundsForOrder, orderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Refund{}
	for rows.Next() {
		var i Refund
		if err := rows.Scan(
			&i.ID,
			&i.PaymentIntentID,
			&i.Status,
			&i.AmountMinor,
			&i.Currency,
			&i.ProviderReference,
			&i.Reason,
			&i.IdempotencyKey,
			&i.ReceiptMetadata,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStuckPaymentIntents = `-- name: ListStuckPaymentIntents :many
SELECT i.id, i.order_id, i.provider, i.status, i.amount_minor, i.currency, i.provider_reference, i.checkout_url, i.idempotency_key, i.capabilities, i.receipt_metadata, i.created_at, i.updated_at, o.user_id, o.operation
FROM payment_intents i
JOIN orders o ON o.id = i.order_id
WHERE i.status IN ('pending', 'requires_action', 'processing')
  AND i.updated_at < now() - $1::interval
ORDER BY i.updated_at
LIMIT $2
`

type ListStuckPaymentIntentsParams struct {
	StuckAfter pgtype.Interval `json:"stuck_after"`
	PageSize   int32           `json:"page_size"`
}

type ListStuckPaymentIntentsRow struct {
	PaymentIntent PaymentIntent `json:"payment_intent"`
	UserID        pgtype.UUID   `json:"user_id"`
	Operation     string        `json:"operation"`
}

// Intents that have been in flight longer than a provider should take. The
// panel offers reconciliation and retry from this list; neither mutates money
// directly, both go through the existing idempotent payment service.
func (q *Queries) ListStuckPaymentIntents(ctx context.Context, arg ListStuckPaymentIntentsParams) ([]ListStuckPaymentIntentsRow, error) {
	rows, err := q.db.Query(ctx, listStuckPaymentIntents, arg.StuckAfter, arg.PageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListStuckPaymentIntentsRow{}
	for rows.Next() {
		var i ListStuckPaymentIntentsRow
		if err := rows.Scan(
			&i.PaymentIntent.ID,
			&i.PaymentIntent.OrderID,
			&i.PaymentIntent.Provider,
			&i.PaymentIntent.Status,
			&i.PaymentIntent.AmountMinor,
			&i.PaymentIntent.Currency,
			&i.PaymentIntent.ProviderReference,
			&i.PaymentIntent.CheckoutUrl,
			&i.PaymentIntent.IdempotencyKey,
			&i.PaymentIntent.Capabilities,
			&i.PaymentIntent.ReceiptMetadata,
			&i.PaymentIntent.CreatedAt,
			&i.PaymentIntent.UpdatedAt,
			&i.UserID,
			&i.Operation,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUnpublishedOutboxEvents = `-- name: ListUnpublishedOutboxEvents :many
SELECT id, topic, occurred_at FROM outbox_events
WHERE published_at IS NULL
ORDER BY occurred_at
LIMIT $1
`

type ListUnpublishedOutboxEventsRow struct {
	ID         pgtype.UUID        `json:"id"`
	Topic      string             `json:"topic"`
	OccurredAt pgtype.Timestamptz `json:"occurred_at"`
}

func (q *Queries) ListUnpublishedOutboxEvents(ctx context.Context, pageSize int32) ([]ListUnpublishedOutboxEventsRow, error) {
	rows, err := q.db.Query(ctx, listUnpublishedOutboxEvents, pageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUnpublishedOutboxEventsRow{}
	for rows.Next() {
		var i ListUnpublishedOutboxEventsRow
		if err := rows.Scan(&i.ID, &i.Topic, &i.OccurredAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markWebhookEventForReplay = `-- name: MarkWebhookEventForReplay :one
UPDATE provider_webhook_events
SET status = 'received', error_code = NULL, processed_at = NULL
WHERE id = $1 AND status IN ('failed', 'ignored')
RETURNING id, provider, provider_event_id, signature_valid, body_sha256, raw_body, headers, status, error_code, received_at, processed_at, retain_until
`

// Reprocessing is replay-safe because the downstream handlers are keyed on the
// provider event identifier, so a second pass over the same body reaches the
// same terminal state instead of applying twice.
func (q *Queries) MarkWebhookEventForReplay(ctx context.Context, eventID pgtype.UUID) (ProviderWebhookEvent, error) {
	row := q.db.QueryRow(ctx, markWebhookEventForReplay, eventID)
	var i ProviderWebhookEvent
	err := row.Scan(
		&i.ID,
		&i.Provider,
		&i.ProviderEventID,
		&i.SignatureValid,
		&i.BodySha256,
		&i.RawBody,
		&i.Headers,
		&i.Status,
		&i.ErrorCode,
		&i.ReceivedAt,
		&i.ProcessedAt,
		&i.RetainUntil,
	)
	return i, err
}

const recordProviderConnectionCheck = `-- name: RecordProviderConnectionCheck :one
UPDATE payment_provider_settings
SET connection_status = $1,
    connection_error_code = $2,
    connection_checked_at = now(),
    updated_at = now()
WHERE provider = $3 AND merchant_id = $4
RETURNING provider, merchant_id, enabled, display_order, credentials_ciphertext, webhook_secret_ciphertext, recurring_enabled, recurring_test_status, recurring_tested_at, connection_status, connection_checked_at, connection_error_code, webhook_status, webhook_last_event_at, webhook_last_error_code, created_at, updated_at, updated_by
`

type RecordProviderConnectionCheckParams struct {
	ConnectionStatus    string      `json:"connection_status"`
	ConnectionErrorCode pgtype.Text `json:"connection_error_code"`
	Provider            string      `json:"provider"`
	MerchantID          string      `json:"merchant_id"`
}

func (q *Queries) RecordProviderConnectionCheck(ctx context.Context, arg RecordProviderConnectionCheckParams) (PaymentProviderSetting, error) {
	row := q.db.QueryRow(ctx, recordProviderConnectionCheck,
		arg.ConnectionStatus,
		arg.ConnectionErrorCode,
		arg.Provider,
		arg.MerchantID,
	)
	var i PaymentProviderSetting
	err := row.Scan(
		&i.Provider,
		&i.MerchantID,
		&i.Enabled,
		&i.DisplayOrder,
		&i.CredentialsCiphertext,
		&i.WebhookSecretCiphertext,
		&i.RecurringEnabled,
		&i.RecurringTestStatus,
		&i.RecurringTestedAt,
		&i.ConnectionStatus,
		&i.ConnectionCheckedAt,
		&i.ConnectionErrorCode,
		&i.WebhookStatus,
		&i.WebhookLastEventAt,
		&i.WebhookLastErrorCode,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UpdatedBy,
	)
	return i, err
}

const recordProviderWebhookHealth = `-- name: RecordProviderWebhookHealth :one
UPDATE payment_provider_settings
SET webhook_status = $1,
    webhook_last_error_code = $2,
    webhook_last_event_at = CASE
      WHEN $1::text = 'healthy' THEN now()
      ELSE webhook_last_event_at
    END,
    updated_at = now()
WHERE provider = $3 AND merchant_id = $4
RETURNING provider, merchant_id, enabled, display_order, credentials_ciphertext, webhook_secret_ciphertext, recurring_enabled, recurring_test_status, recurring_tested_at, connection_status, connection_checked_at, connection_error_code, webhook_status, webhook_last_event_at, webhook_last_error_code, created_at, updated_at, updated_by
`

type RecordProviderWebhookHealthParams struct {
	WebhookStatus        string      `json:"webhook_status"`
	WebhookLastErrorCode pgtype.Text `json:"webhook_last_error_code"`
	Provider             string      `json:"provider"`
	MerchantID           string      `json:"merchant_id"`
}

func (q *Queries) RecordProviderWebhookHealth(ctx context.Context, arg RecordProviderWebhookHealthParams) (PaymentProviderSetting, error) {
	row := q.db.QueryRow(ctx, recordProviderWebhookHealth,
		arg.WebhookStatus,
		arg.WebhookLastErrorCode,
		arg.Provider,
		arg.MerchantID,
	)
	var i PaymentProviderSetting
	err := row.Scan(
		&i.Provider,
		&i.MerchantID,
		&i.Enabled,
		&i.DisplayOrder,
		&i.CredentialsCiphertext,
		&i.WebhookSecretCiphertext,
		&i.RecurringEnabled,
		&i.RecurringTestStatus,
		&i.RecurringTestedAt,
		&i.ConnectionStatus,
		&i.ConnectionCheckedAt,
		&i.ConnectionErrorCode,
		&i.WebhookStatus,
		&i.WebhookLastEventAt,
		&i.WebhookLastErrorCode,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UpdatedBy,
	)
	return i, err
}

const recountBulkOperation = `-- name: RecountBulkOperation :one
UPDATE bulk_operations b
SET succeeded_count = c.succeeded,
    failed_count = c.failed,
    skipped_count = c.skipped,
    status = CASE
      WHEN c.pending > 0 THEN b.status
      WHEN c.failed = c.total AND c.total > 0 THEN 'failed'
      ELSE 'completed'
    END,
    completed_at = CASE WHEN c.pending > 0 THEN NULL ELSE now() END,
    updated_at = now()
FROM (
  SELECT
    count(*)::integer AS total,
    count(*) FILTER (WHERE status = 'pending')::integer AS pending,
    count(*) FILTER (WHERE status = 'succeeded')::integer AS succeeded,
    count(*) FILTER (WHERE status = 'failed')::integer AS failed,
    count(*) FILTER (WHERE status = 'skipped')::integer AS skipped
  FROM bulk_operation_items WHERE operation_id = $1
) c
WHERE b.id = $1
RETURNING b.id, b.kind, b.status, b.requested_by, b.reason, b.parameters, b.total_count, b.succeeded_count, b.failed_count, b.skipped_count, b.idempotency_key, b.created_at, b.updated_at, b.completed_at
`

// Counters are recomputed from the items rather than incremented, so a retried
// worker cannot double-count an outcome it already recorded.
func (q *Queries) RecountBulkOperation(ctx context.Context, operationID pgtype.UUID) (BulkOperation, error) {
	row := q.db.QueryRow(ctx, recountBulkOperation, operationID)
	var i BulkOperation
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.Status,
		&i.RequestedBy,
		&i.Reason,
		&i.Parameters,
		&i.TotalCount,
		&i.SucceededCount,
		&i.FailedCount,
		&i.SkippedCount,
		&i.IdempotencyKey,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const removePromotionPlan = `-- name: RemovePromotionPlan :exec
DELETE FROM promotion_plans WHERE promotion_id = $1 AND plan_id = $2
`

type RemovePromotionPlanParams struct {
	PromotionID pgtype.UUID `json:"promotion_id"`
	PlanID      pgtype.UUID `json:"plan_id"`
}

func (q *Queries) RemovePromotionPlan(ctx context.Context, arg RemovePromotionPlanParams) error {
	_, err := q.db.Exec(ctx, removePromotionPlan, arg.PromotionID, arg.PlanID)
	return err
}

const requeueFulfillmentOperation = `-- name: RequeueFulfillmentOperation :one
UPDATE fulfillment_operations
SET status = 'pending', next_attempt_at = now(), last_error_code = NULL, updated_at = now()
WHERE id = $1 AND status IN ('failed', 'retrying')
RETURNING id, entitlement_id, operation, status, idempotency_key, correlation_id, desired_state, attempt_count, next_attempt_at, last_error_code, created_at, updated_at, completed_at
`

// An operator retry only ever moves a terminal-looking row back into the queue.
// It cannot skip the idempotency key, so the retried attempt is the same
// operation the worker already knows how to make exactly once.
func (q *Queries) RequeueFulfillmentOperation(ctx context.Context, operationID pgtype.UUID) (FulfillmentOperation, error) {
	row := q.db.QueryRow(ctx, requeueFulfillmentOperation, operationID)
	var i FulfillmentOperation
	err := row.Scan(
		&i.ID,
		&i.EntitlementID,
		&i.Operation,
		&i.Status,
		&i.IdempotencyKey,
		&i.CorrelationID,
		&i.DesiredState,
		&i.AttemptCount,
		&i.NextAttemptAt,
		&i.LastErrorCode,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const retirePlanVersion = `-- name: RetirePlanVersion :one
UPDATE plan_versions
SET retired_at = now()
WHERE id = $1 AND retired_at IS NULL
RETURNING id, plan_id, version, billing_period, duration_seconds, traffic_allowance_bytes, device_limit, remnawave_squad_ids, upgrade_policy, downgrade_policy, cancellation_policy, recurring_capable, created_at, retired_at, grace_period_seconds, trial_eligibility, squad_selection, min_selectable_squads, max_selectable_squads
`

func (q *Queries) RetirePlanVersion(ctx context.Context, planVersionID pgtype.UUID) (PlanVersion, error) {
	row := q.db.QueryRow(ctx, retirePlanVersion, planVersionID)
	var i PlanVersion
	err := row.Scan(
		&i.ID,
		&i.PlanID,
		&i.Version,
		&i.BillingPeriod,
		&i.DurationSeconds,
		&i.TrafficAllowanceBytes,
		&i.DeviceLimit,
		&i.RemnawaveSquadIds,
		&i.UpgradePolicy,
		&i.DowngradePolicy,
		&i.CancellationPolicy,
		&i.RecurringCapable,
		&i.CreatedAt,
		&i.RetiredAt,
		&i.GracePeriodSeconds,
		&i.TrialEligibility,
		&i.SquadSelection,
		&i.MinSelectableSquads,
		&i.MaxSelectableSquads,
	)
	return i, err
}

const searchCustomers = `-- name: SearchCustomers :many

SELECT u.id, u.status, u.locale, u.created_at, u.updated_at, u.timezone, u.suspended_at, u.deleted_at, u.anonymized_at, u.retention_until, r.telegram_id, r.remnawave_id
FROM users u
LEFT JOIN remnawave_users r ON r.user_id = u.id
WHERE (
    $1::timestamptz IS NULL
    OR (u.created_at, u.id) < ($1::timestamptz, $2::uuid)
  )
  AND ($3::text IS NULL OR u.status = $3)
  AND ($4::uuid IS NULL OR u.id = $4)
  AND ($5::bigint IS NULL OR r.telegram_id = $5)
  AND (
    $6::text IS NULL
    OR EXISTS (
      SELECT 1 FROM subscriptions s
      WHERE s.user_id = u.id AND s.remnawave_username = $6
    )
  )
  AND (
    $7::text IS NULL
    OR ($7 = 'subscribed' AND EXISTS (
          SELECT 1 FROM entitlements e
          WHERE e.user_id = u.id AND e.status IN ('active', 'limited') AND e.ends_at > now()))
    OR ($7 = 'lapsed' AND NOT EXISTS (
          SELECT 1 FROM entitlements e
          WHERE e.user_id = u.id AND e.status IN ('active', 'limited') AND e.ends_at > now())
        AND EXISTS (SELECT 1 FROM entitlements e WHERE e.user_id = u.id))
    OR ($7 = 'never_purchased' AND NOT EXISTS (
          SELECT 1 FROM orders o WHERE o.user_id = u.id AND o.state IN ('paid', 'fulfilled')))
    OR ($7 = 'flagged' AND EXISTS (
          SELECT 1 FROM blocklist_matches m
          WHERE m.user_id = u.id AND m.status IN ('open', 'appealed')))
  )
ORDER BY u.created_at DESC, u.id DESC
LIMIT $8
`

type SearchCustomersParams struct {
	CursorCreatedAt pgtype.Timestamptz `json:"cursor_created_at"`
	CursorID        pgtype.UUID        `json:"cursor_id"`
	Status          pgtype.Text        `json:"status"`
	CustomerID      pgtype.UUID        `json:"customer_id"`
	TelegramID      pgtype.Int8        `json:"telegram_id"`
	Username        pgtype.Text        `json:"username"`
	Segment         pgtype.Text        `json:"segment"`
	PageSize        int32              `json:"page_size"`
}

type SearchCustomersRow struct {
	User        User        `json:"user"`
	TelegramID  pgtype.Int8 `json:"telegram_id"`
	RemnawaveID pgtype.Int8 `json:"remnawave_id"`
}

// ---------------------------------------------------------------------------
// Customer search and profile
// ---------------------------------------------------------------------------
// Search is by identifiers an operator may safely be handed: the Omniflow
// customer identifier, a Telegram identifier, and a Remnawave username. There
// is deliberately no free-text search over contact values — those are stored as
// ciphertext and a fingerprint precisely so they cannot be trawled.
func (q *Queries) SearchCustomers(ctx context.Context, arg SearchCustomersParams) ([]SearchCustomersRow, error) {
	rows, err := q.db.Query(ctx, searchCustomers,
		arg.CursorCreatedAt,
		arg.CursorID,
		arg.Status,
		arg.CustomerID,
		arg.TelegramID,
		arg.Username,
		arg.Segment,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SearchCustomersRow{}
	for rows.Next() {
		var i SearchCustomersRow
		if err := rows.Scan(
			&i.User.ID,
			&i.User.Status,
			&i.User.Locale,
			&i.User.CreatedAt,
			&i.User.UpdatedAt,
			&i.User.Timezone,
			&i.User.SuspendedAt,
			&i.User.DeletedAt,
			&i.User.AnonymizedAt,
			&i.User.RetentionUntil,
			&i.TelegramID,
			&i.RemnawaveID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchFulfillmentOperations = `-- name: SearchFulfillmentOperations :many

SELECT f.id, f.entitlement_id, f.operation, f.status, f.idempotency_key, f.correlation_id, f.desired_state, f.attempt_count, f.next_attempt_at, f.last_error_code, f.created_at, f.updated_at, f.completed_at, e.user_id, e.subscription_id
FROM fulfillment_operations f
JOIN entitlements e ON e.id = f.entitlement_id
WHERE (
    $1::timestamptz IS NULL
    OR (f.created_at, f.id) < ($1::timestamptz, $2::uuid)
  )
  AND ($3::text IS NULL OR f.status = $3)
  AND ($4::text IS NULL OR f.operation = $4)
  AND ($5::uuid IS NULL OR f.entitlement_id = $5)
ORDER BY f.created_at DESC, f.id DESC
LIMIT $6
`

type SearchFulfillmentOperationsParams struct {
	CursorCreatedAt pgtype.Timestamptz `json:"cursor_created_at"`
	CursorID        pgtype.UUID        `json:"cursor_id"`
	Status          pgtype.Text        `json:"status"`
	Operation       pgtype.Text        `json:"operation"`
	EntitlementID   pgtype.UUID        `json:"entitlement_id"`
	PageSize        int32              `json:"page_size"`
}

type SearchFulfillmentOperationsRow struct {
	FulfillmentOperation FulfillmentOperation `json:"fulfillment_operation"`
	UserID               pgtype.UUID          `json:"user_id"`
	SubscriptionID       pgtype.UUID          `json:"subscription_id"`
}

// ---------------------------------------------------------------------------
// Fulfillment and jobs
// ---------------------------------------------------------------------------
func (q *Queries) SearchFulfillmentOperations(ctx context.Context, arg SearchFulfillmentOperationsParams) ([]SearchFulfillmentOperationsRow, error) {
	rows, err := q.db.Query(ctx, searchFulfillmentOperations,
		arg.CursorCreatedAt,
		arg.CursorID,
		arg.Status,
		arg.Operation,
		arg.EntitlementID,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SearchFulfillmentOperationsRow{}
	for rows.Next() {
		var i SearchFulfillmentOperationsRow
		if err := rows.Scan(
			&i.FulfillmentOperation.ID,
			&i.FulfillmentOperation.EntitlementID,
			&i.FulfillmentOperation.Operation,
			&i.FulfillmentOperation.Status,
			&i.FulfillmentOperation.IdempotencyKey,
			&i.FulfillmentOperation.CorrelationID,
			&i.FulfillmentOperation.DesiredState,
			&i.FulfillmentOperation.AttemptCount,
			&i.FulfillmentOperation.NextAttemptAt,
			&i.FulfillmentOperation.LastErrorCode,
			&i.FulfillmentOperation.CreatedAt,
			&i.FulfillmentOperation.UpdatedAt,
			&i.FulfillmentOperation.CompletedAt,
			&i.UserID,
			&i.SubscriptionID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchOrders = `-- name: SearchOrders :many

SELECT id, user_id, state, operation, currency, subtotal_minor, discount_minor, wallet_minor, external_minor, paid_minor, refunded_minor, idempotency_key, expires_at, created_at, updated_at, subscription_id, selected_squad_ids FROM orders
WHERE (
    $1::timestamptz IS NULL
    OR (created_at, id) < ($1::timestamptz, $2::uuid)
  )
  AND ($3::text IS NULL OR state = $3)
  AND ($4::text IS NULL OR operation = $4)
  AND ($5::uuid IS NULL OR user_id = $5)
  AND ($6::text IS NULL OR currency = $6)
  AND ($7::timestamptz IS NULL OR created_at >= $7)
  AND ($8::timestamptz IS NULL OR created_at < $8)
ORDER BY created_at DESC, id DESC
LIMIT $9
`

type SearchOrdersParams struct {
	CursorCreatedAt pgtype.Timestamptz `json:"cursor_created_at"`
	CursorID        pgtype.UUID        `json:"cursor_id"`
	State           pgtype.Text        `json:"state"`
	Operation       pgtype.Text        `json:"operation"`
	UserID          pgtype.UUID        `json:"user_id"`
	Currency        pgtype.Text        `json:"currency"`
	CreatedFrom     pgtype.Timestamptz `json:"created_from"`
	CreatedTo       pgtype.Timestamptz `json:"created_to"`
	PageSize        int32              `json:"page_size"`
}

// ---------------------------------------------------------------------------
// Finance
// ---------------------------------------------------------------------------
func (q *Queries) SearchOrders(ctx context.Context, arg SearchOrdersParams) ([]Order, error) {
	rows, err := q.db.Query(ctx, searchOrders,
		arg.CursorCreatedAt,
		arg.CursorID,
		arg.State,
		arg.Operation,
		arg.UserID,
		arg.Currency,
		arg.CreatedFrom,
		arg.CreatedTo,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Order{}
	for rows.Next() {
		var i Order
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.State,
			&i.Operation,
			&i.Currency,
			&i.SubtotalMinor,
			&i.DiscountMinor,
			&i.WalletMinor,
			&i.ExternalMinor,
			&i.PaidMinor,
			&i.RefundedMinor,
			&i.IdempotencyKey,
			&i.ExpiresAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.SubscriptionID,
			&i.SelectedSquadIds,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchPromotions = `-- name: SearchPromotions :many
SELECT
  p.id, p.code, p.kind, p.value, p.currency, p.starts_at, p.ends_at, p.redemption_limit, p.per_customer_limit, p.eligibility, p.active, p.created_at, p.stackable, p.precedence,
  (SELECT count(*) FROM promo_redemptions r WHERE r.promotion_id = p.id)::bigint AS redemption_count,
  (SELECT COALESCE(sum(r.discount_minor), 0) FROM promo_redemptions r WHERE r.promotion_id = p.id)::bigint AS discount_minor
FROM promotions p
WHERE ($1::boolean IS NULL OR p.active = $1)
  AND ($2::text IS NULL OR p.kind = $2)
ORDER BY p.created_at DESC
LIMIT $3
`

type SearchPromotionsParams struct {
	Active   pgtype.Bool `json:"active"`
	Kind     pgtype.Text `json:"kind"`
	PageSize int32       `json:"page_size"`
}

type SearchPromotionsRow struct {
	Promotion       Promotion `json:"promotion"`
	RedemptionCount int64     `json:"redemption_count"`
	DiscountMinor   int64     `json:"discount_minor"`
}

func (q *Queries) SearchPromotions(ctx context.Context, arg SearchPromotionsParams) ([]SearchPromotionsRow, error) {
	rows, err := q.db.Query(ctx, searchPromotions, arg.Active, arg.Kind, arg.PageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SearchPromotionsRow{}
	for rows.Next() {
		var i SearchPromotionsRow
		if err := rows.Scan(
			&i.Promotion.ID,
			&i.Promotion.Code,
			&i.Promotion.Kind,
			&i.Promotion.Value,
			&i.Promotion.Currency,
			&i.Promotion.StartsAt,
			&i.Promotion.EndsAt,
			&i.Promotion.RedemptionLimit,
			&i.Promotion.PerCustomerLimit,
			&i.Promotion.Eligibility,
			&i.Promotion.Active,
			&i.Promotion.CreatedAt,
			&i.Promotion.Stackable,
			&i.Promotion.Precedence,
			&i.RedemptionCount,
			&i.DiscountMinor,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchWebhookEvents = `-- name: SearchWebhookEvents :many
SELECT id, provider, provider_event_id, signature_valid, status, error_code,
       received_at, processed_at, retain_until
FROM provider_webhook_events
WHERE (
    $1::timestamptz IS NULL
    OR (received_at, id) < ($1::timestamptz, $2::uuid)
  )
  AND ($3::text IS NULL OR provider = $3)
  AND ($4::text IS NULL OR status = $4)
ORDER BY received_at DESC, id DESC
LIMIT $5
`

type SearchWebhookEventsParams struct {
	CursorReceivedAt pgtype.Timestamptz `json:"cursor_received_at"`
	CursorID         pgtype.UUID        `json:"cursor_id"`
	Provider         pgtype.Text        `json:"provider"`
	Status           pgtype.Text        `json:"status"`
	PageSize         int32              `json:"page_size"`
}

type SearchWebhookEventsRow struct {
	ID              pgtype.UUID        `json:"id"`
	Provider        string             `json:"provider"`
	ProviderEventID string             `json:"provider_event_id"`
	SignatureValid  bool               `json:"signature_valid"`
	Status          string             `json:"status"`
	ErrorCode       pgtype.Text        `json:"error_code"`
	ReceivedAt      pgtype.Timestamptz `json:"received_at"`
	ProcessedAt     pgtype.Timestamptz `json:"processed_at"`
	RetainUntil     pgtype.Timestamptz `json:"retain_until"`
}

// The raw body is deliberately not selected: it can contain provider payloads,
// and the panel never needs it to answer "did this arrive and was it accepted".
func (q *Queries) SearchWebhookEvents(ctx context.Context, arg SearchWebhookEventsParams) ([]SearchWebhookEventsRow, error) {
	rows, err := q.db.Query(ctx, searchWebhookEvents,
		arg.CursorReceivedAt,
		arg.CursorID,
		arg.Provider,
		arg.Status,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SearchWebhookEventsRow{}
	for rows.Next() {
		var i SearchWebhookEventsRow
		if err := rows.Scan(
			&i.ID,
			&i.Provider,
			&i.ProviderEventID,
			&i.SignatureValid,
			&i.Status,
			&i.ErrorCode,
			&i.ReceivedAt,
			&i.ProcessedAt,
			&i.RetainUntil,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const seedCommerceSettings = `-- name: SeedCommerceSettings :one
INSERT INTO commerce_settings (
  topup_enabled, topup_currency, topup_presets_minor, topup_minimum_minor,
  topup_maximum_minor, topup_window_seconds, topup_window_limit_minor,
  multi_subscription_enabled, max_subscriptions_per_customer
) VALUES (
  $1, $2, $3,
  $4, $5,
  $6, $7,
  $8, $9
)
ON CONFLICT (singleton) DO NOTHING
RETURNING singleton, topup_enabled, topup_currency, topup_presets_minor, topup_minimum_minor, topup_maximum_minor, topup_window_seconds, topup_window_limit_minor, multi_subscription_enabled, max_subscriptions_per_customer, updated_at, updated_by
`

type SeedCommerceSettingsParams struct {
	TopupEnabled                bool    `json:"topup_enabled"`
	TopupCurrency               string  `json:"topup_currency"`
	TopupPresetsMinor           []int64 `json:"topup_presets_minor"`
	TopupMinimumMinor           int64   `json:"topup_minimum_minor"`
	TopupMaximumMinor           int64   `json:"topup_maximum_minor"`
	TopupWindowSeconds          int64   `json:"topup_window_seconds"`
	TopupWindowLimitMinor       int64   `json:"topup_window_limit_minor"`
	MultiSubscriptionEnabled    bool    `json:"multi_subscription_enabled"`
	MaxSubscriptionsPerCustomer int32   `json:"max_subscriptions_per_customer"`
}

// Written once, from the environment the installation already had. An
// installation upgrading from v0.5 therefore keeps the limits its operator
// configured, and every later change comes from the panel.
func (q *Queries) SeedCommerceSettings(ctx context.Context, arg SeedCommerceSettingsParams) (CommerceSetting, error) {
	row := q.db.QueryRow(ctx, seedCommerceSettings,
		arg.TopupEnabled,
		arg.TopupCurrency,
		arg.TopupPresetsMinor,
		arg.TopupMinimumMinor,
		arg.TopupMaximumMinor,
		arg.TopupWindowSeconds,
		arg.TopupWindowLimitMinor,
		arg.MultiSubscriptionEnabled,
		arg.MaxSubscriptionsPerCustomer,
	)
	var i CommerceSetting
	err := row.Scan(
		&i.Singleton,
		&i.TopupEnabled,
		&i.TopupCurrency,
		&i.TopupPresetsMinor,
		&i.TopupMinimumMinor,
		&i.TopupMaximumMinor,
		&i.TopupWindowSeconds,
		&i.TopupWindowLimitMinor,
		&i.MultiSubscriptionEnabled,
		&i.MaxSubscriptionsPerCustomer,
		&i.UpdatedAt,
		&i.UpdatedBy,
	)
	return i, err
}

const setBulkOperationTotal = `-- name: SetBulkOperationTotal :one
UPDATE bulk_operations
SET total_count = $1, status = 'ready', updated_at = now()
WHERE id = $2 AND status = 'previewing'
RETURNING id, kind, status, requested_by, reason, parameters, total_count, succeeded_count, failed_count, skipped_count, idempotency_key, created_at, updated_at, completed_at
`

type SetBulkOperationTotalParams struct {
	TotalCount  int32       `json:"total_count"`
	OperationID pgtype.UUID `json:"operation_id"`
}

func (q *Queries) SetBulkOperationTotal(ctx context.Context, arg SetBulkOperationTotalParams) (BulkOperation, error) {
	row := q.db.QueryRow(ctx, setBulkOperationTotal, arg.TotalCount, arg.OperationID)
	var i BulkOperation
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.Status,
		&i.RequestedBy,
		&i.Reason,
		&i.Parameters,
		&i.TotalCount,
		&i.SucceededCount,
		&i.FailedCount,
		&i.SkippedCount,
		&i.IdempotencyKey,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const setPromoCodeActive = `-- name: SetPromoCodeActive :one
UPDATE promo_codes SET active = $1 WHERE id = $2 RETURNING id, promotion_id, normalized_code, redemption_limit, active, created_at
`

type SetPromoCodeActiveParams struct {
	Active      bool        `json:"active"`
	PromoCodeID pgtype.UUID `json:"promo_code_id"`
}

func (q *Queries) SetPromoCodeActive(ctx context.Context, arg SetPromoCodeActiveParams) (PromoCode, error) {
	row := q.db.QueryRow(ctx, setPromoCodeActive, arg.Active, arg.PromoCodeID)
	var i PromoCode
	err := row.Scan(
		&i.ID,
		&i.PromotionID,
		&i.NormalizedCode,
		&i.RedemptionLimit,
		&i.Active,
		&i.CreatedAt,
	)
	return i, err
}

const setProviderRecurring = `-- name: SetProviderRecurring :one
UPDATE payment_provider_settings
SET recurring_test_status = $1,
    recurring_enabled = $2,
    recurring_tested_at = now(),
    updated_at = now(),
    updated_by = $3
WHERE provider = $4 AND merchant_id = $5
RETURNING provider, merchant_id, enabled, display_order, credentials_ciphertext, webhook_secret_ciphertext, recurring_enabled, recurring_test_status, recurring_tested_at, connection_status, connection_checked_at, connection_error_code, webhook_status, webhook_last_event_at, webhook_last_error_code, created_at, updated_at, updated_by
`

type SetProviderRecurringParams struct {
	RecurringTestStatus string      `json:"recurring_test_status"`
	RecurringEnabled    bool        `json:"recurring_enabled"`
	UpdatedBy           pgtype.UUID `json:"updated_by"`
	Provider            string      `json:"provider"`
	MerchantID          string      `json:"merchant_id"`
}

// The two writes are one statement on purpose: `recurring_enabled` may only be
// true alongside a passing test, and the table constraint refuses any pair that
// violates it.
func (q *Queries) SetProviderRecurring(ctx context.Context, arg SetProviderRecurringParams) (PaymentProviderSetting, error) {
	row := q.db.QueryRow(ctx, setProviderRecurring,
		arg.RecurringTestStatus,
		arg.RecurringEnabled,
		arg.UpdatedBy,
		arg.Provider,
		arg.MerchantID,
	)
	var i PaymentProviderSetting
	err := row.Scan(
		&i.Provider,
		&i.MerchantID,
		&i.Enabled,
		&i.DisplayOrder,
		&i.CredentialsCiphertext,
		&i.WebhookSecretCiphertext,
		&i.RecurringEnabled,
		&i.RecurringTestStatus,
		&i.RecurringTestedAt,
		&i.ConnectionStatus,
		&i.ConnectionCheckedAt,
		&i.ConnectionErrorCode,
		&i.WebhookStatus,
		&i.WebhookLastEventAt,
		&i.WebhookLastErrorCode,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UpdatedBy,
	)
	return i, err
}

const startBulkOperation = `-- name: StartBulkOperation :one
UPDATE bulk_operations
SET status = 'running', updated_at = now()
WHERE id = $1 AND status = 'ready'
RETURNING id, kind, status, requested_by, reason, parameters, total_count, succeeded_count, failed_count, skipped_count, idempotency_key, created_at, updated_at, completed_at
`

// Only a previewed operation may run. That is what enforces "impact preview
// before bulk change" in the database rather than only in the panel.
func (q *Queries) StartBulkOperation(ctx context.Context, operationID pgtype.UUID) (BulkOperation, error) {
	row := q.db.QueryRow(ctx, startBulkOperation, operationID)
	var i BulkOperation
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.Status,
		&i.RequestedBy,
		&i.Reason,
		&i.Parameters,
		&i.TotalCount,
		&i.SucceededCount,
		&i.FailedCount,
		&i.SkippedCount,
		&i.IdempotencyKey,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const updatePlanOrdering = `-- name: UpdatePlanOrdering :one
UPDATE plans
SET sort_order = $1,
    max_concurrent_per_customer = $2
WHERE id = $3
RETURNING id, code, kind, visible, sort_order, created_at, archived_at, max_concurrent_per_customer
`

type UpdatePlanOrderingParams struct {
	SortOrder                int32       `json:"sort_order"`
	MaxConcurrentPerCustomer pgtype.Int4 `json:"max_concurrent_per_customer"`
	PlanID                   pgtype.UUID `json:"plan_id"`
}

func (q *Queries) UpdatePlanOrdering(ctx context.Context, arg UpdatePlanOrderingParams) (Plan, error) {
	row := q.db.QueryRow(ctx, updatePlanOrdering, arg.SortOrder, arg.MaxConcurrentPerCustomer, arg.PlanID)
	var i Plan
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Kind,
		&i.Visible,
		&i.SortOrder,
		&i.CreatedAt,
		&i.ArchivedAt,
		&i.MaxConcurrentPerCustomer,
	)
	return i, err
}

const updatePromotion = `-- name: UpdatePromotion :one
UPDATE promotions
SET value = $1,
    currency = $2,
    starts_at = $3,
    ends_at = $4,
    redemption_limit = $5,
    per_customer_limit = $6,
    eligibility = $7,
    active = $8,
    stackable = $9,
    precedence = $10
WHERE id = $11
RETURNING id, code, kind, value, currency, starts_at, ends_at, redemption_limit, per_customer_limit, eligibility, active, created_at, stackable, precedence
`

type UpdatePromotionParams struct {
	Value            int64              `json:"value"`
	Currency         pgtype.Text        `json:"currency"`
	StartsAt         pgtype.Timestamptz `json:"starts_at"`
	EndsAt           pgtype.Timestamptz `json:"ends_at"`
	RedemptionLimit  pgtype.Int4        `json:"redemption_limit"`
	PerCustomerLimit int32              `json:"per_customer_limit"`
	Eligibility      []byte             `json:"eligibility"`
	Active           bool               `json:"active"`
	Stackable        bool               `json:"stackable"`
	Precedence       int32              `json:"precedence"`
	PromotionID      pgtype.UUID        `json:"promotion_id"`
}

func (q *Queries) UpdatePromotion(ctx context.Context, arg UpdatePromotionParams) (Promotion, error) {
	row := q.db.QueryRow(ctx, updatePromotion,
		arg.Value,
		arg.Currency,
		arg.StartsAt,
		arg.EndsAt,
		arg.RedemptionLimit,
		arg.PerCustomerLimit,
		arg.Eligibility,
		arg.Active,
		arg.Stackable,
		arg.Precedence,
		arg.PromotionID,
	)
	var i Promotion
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Kind,
		&i.Value,
		&i.Currency,
		&i.StartsAt,
		&i.EndsAt,
		&i.RedemptionLimit,
		&i.PerCustomerLimit,
		&i.Eligibility,
		&i.Active,
		&i.CreatedAt,
		&i.Stackable,
		&i.Precedence,
	)
	return i, err
}

const updateSubscriptionSettings = `-- name: UpdateSubscriptionSettings :one
UPDATE commerce_settings
SET multi_subscription_enabled = $1,
    max_subscriptions_per_customer = $2,
    updated_at = now(),
    updated_by = $3
WHERE singleton
RETURNING singleton, topup_enabled, topup_currency, topup_presets_minor, topup_minimum_minor, topup_maximum_minor, topup_window_seconds, topup_window_limit_minor, multi_subscription_enabled, max_subscriptions_per_customer, updated_at, updated_by
`

type UpdateSubscriptionSettingsParams struct {
	MultiSubscriptionEnabled    bool        `json:"multi_subscription_enabled"`
	MaxSubscriptionsPerCustomer int32       `json:"max_subscriptions_per_customer"`
	UpdatedBy                   pgtype.UUID `json:"updated_by"`
}

func (q *Queries) UpdateSubscriptionSettings(ctx context.Context, arg UpdateSubscriptionSettingsParams) (CommerceSetting, error) {
	row := q.db.QueryRow(ctx, updateSubscriptionSettings, arg.MultiSubscriptionEnabled, arg.MaxSubscriptionsPerCustomer, arg.UpdatedBy)
	var i CommerceSetting
	err := row.Scan(
		&i.Singleton,
		&i.TopupEnabled,
		&i.TopupCurrency,
		&i.TopupPresetsMinor,
		&i.TopupMinimumMinor,
		&i.TopupMaximumMinor,
		&i.TopupWindowSeconds,
		&i.TopupWindowLimitMinor,
		&i.MultiSubscriptionEnabled,
		&i.MaxSubscriptionsPerCustomer,
		&i.UpdatedAt,
		&i.UpdatedBy,
	)
	return i, err
}

const updateTopUpSettings = `-- name: UpdateTopUpSettings :one
UPDATE commerce_settings
SET topup_enabled = $1,
    topup_currency = $2,
    topup_presets_minor = $3,
    topup_minimum_minor = $4,
    topup_maximum_minor = $5,
    topup_window_seconds = $6,
    topup_window_limit_minor = $7,
    updated_at = now(),
    updated_by = $8
WHERE singleton
RETURNING singleton, topup_enabled, topup_currency, topup_presets_minor, topup_minimum_minor, topup_maximum_minor, topup_window_seconds, topup_window_limit_minor, multi_subscription_enabled, max_subscriptions_per_customer, updated_at, updated_by
`

type UpdateTopUpSettingsParams struct {
	TopupEnabled          bool        `json:"topup_enabled"`
	TopupCurrency         string      `json:"topup_currency"`
	TopupPresetsMinor     []int64     `json:"topup_presets_minor"`
	TopupMinimumMinor     int64       `json:"topup_minimum_minor"`
	TopupMaximumMinor     int64       `json:"topup_maximum_minor"`
	TopupWindowSeconds    int64       `json:"topup_window_seconds"`
	TopupWindowLimitMinor int64       `json:"topup_window_limit_minor"`
	UpdatedBy             pgtype.UUID `json:"updated_by"`
}

func (q *Queries) UpdateTopUpSettings(ctx context.Context, arg UpdateTopUpSettingsParams) (CommerceSetting, error) {
	row := q.db.QueryRow(ctx, updateTopUpSettings,
		arg.TopupEnabled,
		arg.TopupCurrency,
		arg.TopupPresetsMinor,
		arg.TopupMinimumMinor,
		arg.TopupMaximumMinor,
		arg.TopupWindowSeconds,
		arg.TopupWindowLimitMinor,
		arg.UpdatedBy,
	)
	var i CommerceSetting
	err := row.Scan(
		&i.Singleton,
		&i.TopupEnabled,
		&i.TopupCurrency,
		&i.TopupPresetsMinor,
		&i.TopupMinimumMinor,
		&i.TopupMaximumMinor,
		&i.TopupWindowSeconds,
		&i.TopupWindowLimitMinor,
		&i.MultiSubscriptionEnabled,
		&i.MaxSubscriptionsPerCustomer,
		&i.UpdatedAt,
		&i.UpdatedBy,
	)
	return i, err
}

const upsertPaymentProviderSettings = `-- name: UpsertPaymentProviderSettings :one
INSERT INTO payment_provider_settings (
  provider, merchant_id, enabled, display_order,
  credentials_ciphertext, webhook_secret_ciphertext, updated_by
) VALUES (
  $1, $2, $3, $4,
  $5, $6, $7
)
ON CONFLICT (provider, merchant_id) DO UPDATE
SET enabled = EXCLUDED.enabled,
    display_order = EXCLUDED.display_order,
    credentials_ciphertext = COALESCE(
      EXCLUDED.credentials_ciphertext, payment_provider_settings.credentials_ciphertext
    ),
    webhook_secret_ciphertext = COALESCE(
      EXCLUDED.webhook_secret_ciphertext, payment_provider_settings.webhook_secret_ciphertext
    ),
    updated_by = EXCLUDED.updated_by,
    updated_at = now()
RETURNING provider, merchant_id, enabled, display_order, credentials_ciphertext, webhook_secret_ciphertext, recurring_enabled, recurring_test_status, recurring_tested_at, connection_status, connection_checked_at, connection_error_code, webhook_status, webhook_last_event_at, webhook_last_error_code, created_at, updated_at, updated_by
`

type UpsertPaymentProviderSettingsParams struct {
	Provider                string      `json:"provider"`
	MerchantID              string      `json:"merchant_id"`
	Enabled                 bool        `json:"enabled"`
	DisplayOrder            int32       `json:"display_order"`
	CredentialsCiphertext   []byte      `json:"credentials_ciphertext"`
	WebhookSecretCiphertext []byte      `json:"webhook_secret_ciphertext"`
	UpdatedBy               pgtype.UUID `json:"updated_by"`
}

// Null ciphertexts mean "keep what is stored". Recurring is written through the
// separate capability-test statement below, never here, so a settings save can
// never quietly enable it without a passing test.
func (q *Queries) UpsertPaymentProviderSettings(ctx context.Context, arg UpsertPaymentProviderSettingsParams) (PaymentProviderSetting, error) {
	row := q.db.QueryRow(ctx, upsertPaymentProviderSettings,
		arg.Provider,
		arg.MerchantID,
		arg.Enabled,
		arg.DisplayOrder,
		arg.CredentialsCiphertext,
		arg.WebhookSecretCiphertext,
		arg.UpdatedBy,
	)
	var i PaymentProviderSetting
	err := row.Scan(
		&i.Provider,
		&i.MerchantID,
		&i.Enabled,
		&i.DisplayOrder,
		&i.CredentialsCiphertext,
		&i.WebhookSecretCiphertext,
		&i.RecurringEnabled,
		&i.RecurringTestStatus,
		&i.RecurringTestedAt,
		&i.ConnectionStatus,
		&i.ConnectionCheckedAt,
		&i.ConnectionErrorCode,
		&i.WebhookStatus,
		&i.WebhookLastEventAt,
		&i.WebhookLastErrorCode,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UpdatedBy,
	)
	return i, err
}
