// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: attribution.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const attributionSummary = `-- name: AttributionSummary :many
SELECT COALESCE(NULLIF(a.utm_source, ''), a.click_source, 'direct') AS channel,
       COALESCE(a.utm_medium, '') AS medium,
       count(*) AS orders,
       count(*) FILTER (WHERE a.click_id IS NOT NULL) AS attributed_clicks,
       o.currency,
       sum(o.paid_minor)::bigint AS paid_minor,
       sum(o.refunded_minor)::bigint AS refunded_minor
FROM orders o
JOIN order_attributions a ON a.order_id = o.id
WHERE o.paid_at >= $1 AND o.paid_at < $2
GROUP BY channel, medium, o.currency
ORDER BY paid_minor DESC, channel
`

type AttributionSummaryParams struct {
	FromTime pgtype.Timestamptz `json:"from_time"`
	ToTime   pgtype.Timestamptz `json:"to_time"`
}

type AttributionSummaryRow struct {
	Channel          string `json:"channel"`
	Medium           string `json:"medium"`
	Orders           int64  `json:"orders"`
	AttributedClicks int64  `json:"attributed_clicks"`
	Currency         string `json:"currency"`
	PaidMinor        int64  `json:"paid_minor"`
	RefundedMinor    int64  `json:"refunded_minor"`
}

// What each channel brought in, which is the question an operator asks before
// they export anything.
func (q *Queries) AttributionSummary(ctx context.Context, arg AttributionSummaryParams) ([]AttributionSummaryRow, error) {
	rows, err := q.db.Query(ctx, attributionSummary, arg.FromTime, arg.ToTime)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AttributionSummaryRow{}
	for rows.Next() {
		var i AttributionSummaryRow
		if err := rows.Scan(
			&i.Channel,
			&i.Medium,
			&i.Orders,
			&i.AttributedClicks,
			&i.Currency,
			&i.PaidMinor,
			&i.RefundedMinor,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const conversionsInPeriod = `-- name: ConversionsInPeriod :many


SELECT o.id AS order_id, o.operation, o.currency, o.paid_minor, o.refunded_minor,
       o.state, o.paid_at,
       COALESCE(a.click_id, '') AS click_id,
       COALESCE(a.click_source, '') AS click_source,
       COALESCE(a.utm_source, '') AS utm_source,
       COALESCE(a.utm_medium, '') AS utm_medium,
       COALESCE(a.utm_campaign, '') AS utm_campaign,
       COALESCE(a.utm_content, '') AS utm_content,
       COALESCE(a.utm_term, '') AS utm_term
FROM orders o
JOIN order_attributions a ON a.order_id = o.id
WHERE o.paid_at >= $1 AND o.paid_at < $2
  AND ($3::text IS NULL OR a.click_source = $3::text)
ORDER BY o.paid_at, o.id
LIMIT $4
`

type ConversionsInPeriodParams struct {
	FromTime    pgtype.Timestamptz `json:"from_time"`
	ToTime      pgtype.Timestamptz `json:"to_time"`
	ClickSource pgtype.Text        `json:"click_source"`
	PageSize    int32              `json:"page_size"`
}

type ConversionsInPeriodRow struct {
	OrderID       pgtype.UUID        `json:"order_id"`
	Operation     string             `json:"operation"`
	Currency      string             `json:"currency"`
	PaidMinor     int64              `json:"paid_minor"`
	RefundedMinor int64              `json:"refunded_minor"`
	State         string             `json:"state"`
	PaidAt        pgtype.Timestamptz `json:"paid_at"`
	ClickID       string             `json:"click_id"`
	ClickSource   string             `json:"click_source"`
	UtmSource     string             `json:"utm_source"`
	UtmMedium     string             `json:"utm_medium"`
	UtmCampaign   string             `json:"utm_campaign"`
	UtmContent    string             `json:"utm_content"`
	UtmTerm       string             `json:"utm_term"`
}

// Advertising attribution and the offline-conversion export.
// The write lives in `internal/accountcheckout` beside the rest of the purchase
// path rather than here: that package owns its own SQL, and the ownership check
// the write is gated on is a checkout concern rather than a reporting one.
// The offline-conversion export: settled orders that came from an advertisement.
//
// Keyed on `paid_at`, not `created_at`. An advertising platform is being told
// when the money arrived so it can attribute the click it sold; the date an
// abandoned draft was created answers a different question.
//
// Refunded orders are included with their refunded amount reported separately
// rather than being dropped. A platform that optimised bidding on a sale that
// was later returned is being taught the wrong thing, and an operator can only
// correct for that if the export says it happened.
func (q *Queries) ConversionsInPeriod(ctx context.Context, arg ConversionsInPeriodParams) ([]ConversionsInPeriodRow, error) {
	rows, err := q.db.Query(ctx, conversionsInPeriod,
		arg.FromTime,
		arg.ToTime,
		arg.ClickSource,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ConversionsInPeriodRow{}
	for rows.Next() {
		var i ConversionsInPeriodRow
		if err := rows.Scan(
			&i.OrderID,
			&i.Operation,
			&i.Currency,
			&i.PaidMinor,
			&i.RefundedMinor,
			&i.State,
			&i.PaidAt,
			&i.ClickID,
			&i.ClickSource,
			&i.UtmSource,
			&i.UtmMedium,
			&i.UtmCampaign,
			&i.UtmContent,
			&i.UtmTerm,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
