// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: branding.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteBrandingAsset = `-- name: DeleteBrandingAsset :execrows
DELETE FROM branding_assets WHERE kind = $1
`

func (q *Queries) DeleteBrandingAsset(ctx context.Context, kind string) (int64, error) {
	result, err := q.db.Exec(ctx, deleteBrandingAsset, kind)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getBrandingAsset = `-- name: GetBrandingAsset :one
SELECT kind, content_type, bytes, checksum, updated_at
FROM branding_assets
WHERE kind = $1
`

type GetBrandingAssetRow struct {
	Kind        string             `json:"kind"`
	ContentType string             `json:"content_type"`
	Bytes       []byte             `json:"bytes"`
	Checksum    string             `json:"checksum"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetBrandingAsset(ctx context.Context, kind string) (GetBrandingAssetRow, error) {
	row := q.db.QueryRow(ctx, getBrandingAsset, kind)
	var i GetBrandingAssetRow
	err := row.Scan(
		&i.Kind,
		&i.ContentType,
		&i.Bytes,
		&i.Checksum,
		&i.UpdatedAt,
	)
	return i, err
}

const listBrandingAssets = `-- name: ListBrandingAssets :many

SELECT kind, content_type, octet_length(bytes)::bigint AS byte_size, checksum,
       updated_at, updated_by
FROM branding_assets
ORDER BY kind
`

type ListBrandingAssetsRow struct {
	Kind        string             `json:"kind"`
	ContentType string             `json:"content_type"`
	ByteSize    int64              `json:"byte_size"`
	Checksum    string             `json:"checksum"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	UpdatedBy   pgtype.UUID        `json:"updated_by"`
}

// Brand images.
//
// The bytes are selected only by the route that serves them. Every other query
// reads the metadata, so listing the slots on a settings screen cannot pull a
// quarter of a megabyte per row into a response type that has nowhere to put it.
func (q *Queries) ListBrandingAssets(ctx context.Context) ([]ListBrandingAssetsRow, error) {
	rows, err := q.db.Query(ctx, listBrandingAssets)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListBrandingAssetsRow{}
	for rows.Next() {
		var i ListBrandingAssetsRow
		if err := rows.Scan(
			&i.Kind,
			&i.ContentType,
			&i.ByteSize,
			&i.Checksum,
			&i.UpdatedAt,
			&i.UpdatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertBrandingAsset = `-- name: UpsertBrandingAsset :one
INSERT INTO branding_assets (kind, content_type, bytes, checksum, updated_by)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (kind) DO UPDATE
SET content_type = EXCLUDED.content_type,
    bytes = EXCLUDED.bytes,
    checksum = EXCLUDED.checksum,
    updated_at = now(),
    updated_by = EXCLUDED.updated_by
RETURNING kind, content_type, octet_length(bytes)::bigint AS byte_size, checksum,
          updated_at, updated_by
`

type UpsertBrandingAssetParams struct {
	Kind        string      `json:"kind"`
	ContentType string      `json:"content_type"`
	Bytes       []byte      `json:"bytes"`
	Checksum    string      `json:"checksum"`
	UpdatedBy   pgtype.UUID `json:"updated_by"`
}

type UpsertBrandingAssetRow struct {
	Kind        string             `json:"kind"`
	ContentType string             `json:"content_type"`
	ByteSize    int64              `json:"byte_size"`
	Checksum    string             `json:"checksum"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	UpdatedBy   pgtype.UUID        `json:"updated_by"`
}

func (q *Queries) UpsertBrandingAsset(ctx context.Context, arg UpsertBrandingAssetParams) (UpsertBrandingAssetRow, error) {
	row := q.db.QueryRow(ctx, upsertBrandingAsset,
		arg.Kind,
		arg.ContentType,
		arg.Bytes,
		arg.Checksum,
		arg.UpdatedBy,
	)
	var i UpsertBrandingAssetRow
	err := row.Scan(
		&i.Kind,
		&i.ContentType,
		&i.ByteSize,
		&i.Checksum,
		&i.UpdatedAt,
		&i.UpdatedBy,
	)
	return i, err
}
