// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: channel_enforcement.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const listEntitlementsForChannelEnforcement = `-- name: ListEntitlementsForChannelEnforcement :many

SELECT id, status
FROM entitlements
WHERE user_id = $1
  AND status IN ('pending', 'active', 'limited', 'disabled')
  AND ends_at > now()
ORDER BY created_at
`

type ListEntitlementsForChannelEnforcementRow struct {
	ID     pgtype.UUID `json:"id"`
	Status string      `json:"status"`
}

// Channel enforcement: what a membership lapse takes away and a rejoin gives
// back.
//
// Only entitlements still inside their paid period are listed. An expired or
// superseded one has nothing to suspend, and a paused one is already off by an
// operator's decision that a rejoin must not undo.
func (q *Queries) ListEntitlementsForChannelEnforcement(ctx context.Context, userID pgtype.UUID) ([]ListEntitlementsForChannelEnforcementRow, error) {
	rows, err := q.db.Query(ctx, listEntitlementsForChannelEnforcement, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListEntitlementsForChannelEnforcementRow{}
	for rows.Next() {
		var i ListEntitlementsForChannelEnforcementRow
		if err := rows.Scan(&i.ID, &i.Status); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
