// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: channels.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const channelGateSettings = `-- name: ChannelGateSettings :one
SELECT channel_grace_seconds, channel_recheck_seconds FROM commerce_settings WHERE singleton
`

type ChannelGateSettingsRow struct {
	ChannelGraceSeconds   int64 `json:"channel_grace_seconds"`
	ChannelRecheckSeconds int64 `json:"channel_recheck_seconds"`
}

func (q *Queries) ChannelGateSettings(ctx context.Context) (ChannelGateSettingsRow, error) {
	row := q.db.QueryRow(ctx, channelGateSettings)
	var i ChannelGateSettingsRow
	err := row.Scan(&i.ChannelGraceSeconds, &i.ChannelRecheckSeconds)
	return i, err
}

const deleteRequiredChannel = `-- name: DeleteRequiredChannel :exec
DELETE FROM required_channels WHERE id = $1
`

func (q *Queries) DeleteRequiredChannel(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteRequiredChannel, id)
	return err
}

const getChannelEnforcement = `-- name: GetChannelEnforcement :one
SELECT user_id, state, warned_at, grace_until, suspended_at, restored_at, updated_at FROM channel_enforcement WHERE user_id = $1
`

func (q *Queries) GetChannelEnforcement(ctx context.Context, userID pgtype.UUID) (ChannelEnforcement, error) {
	row := q.db.QueryRow(ctx, getChannelEnforcement, userID)
	var i ChannelEnforcement
	err := row.Scan(
		&i.UserID,
		&i.State,
		&i.WarnedAt,
		&i.GraceUntil,
		&i.SuspendedAt,
		&i.RestoredAt,
		&i.UpdatedAt,
	)
	return i, err
}

const grantChannelExemption = `-- name: GrantChannelExemption :one
INSERT INTO channel_exemptions (user_id, reason, granted_by, expires_at)
VALUES ($1, $2, $3, $4)
ON CONFLICT (user_id) DO UPDATE SET
  reason = EXCLUDED.reason, granted_by = EXCLUDED.granted_by,
  granted_at = now(), expires_at = EXCLUDED.expires_at
RETURNING user_id, reason, granted_by, granted_at, expires_at
`

type GrantChannelExemptionParams struct {
	UserID    pgtype.UUID        `json:"user_id"`
	Reason    string             `json:"reason"`
	GrantedBy pgtype.UUID        `json:"granted_by"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) GrantChannelExemption(ctx context.Context, arg GrantChannelExemptionParams) (ChannelExemption, error) {
	row := q.db.QueryRow(ctx, grantChannelExemption,
		arg.UserID,
		arg.Reason,
		arg.GrantedBy,
		arg.ExpiresAt,
	)
	var i ChannelExemption
	err := row.Scan(
		&i.UserID,
		&i.Reason,
		&i.GrantedBy,
		&i.GrantedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const isChannelExempt = `-- name: IsChannelExempt :one
SELECT EXISTS (
  SELECT 1 FROM channel_exemptions
  WHERE user_id = $1 AND (expires_at IS NULL OR expires_at > now())
) AS exempt
`

func (q *Queries) IsChannelExempt(ctx context.Context, userID pgtype.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, isChannelExempt, userID)
	var exempt bool
	err := row.Scan(&exempt)
	return exempt, err
}

const listChannelEnforcementDue = `-- name: ListChannelEnforcementDue :many
SELECT e.user_id, r.telegram_id
FROM channel_enforcement e
JOIN remnawave_users r ON r.user_id = e.user_id
WHERE e.state = 'warned' AND e.grace_until IS NOT NULL AND e.grace_until <= now()
ORDER BY e.grace_until
LIMIT $1
`

type ListChannelEnforcementDueRow struct {
	UserID     pgtype.UUID `json:"user_id"`
	TelegramID pgtype.Int8 `json:"telegram_id"`
}

// Warned customers whose grace has run out.
func (q *Queries) ListChannelEnforcementDue(ctx context.Context, pageSize int32) ([]ListChannelEnforcementDueRow, error) {
	rows, err := q.db.Query(ctx, listChannelEnforcementDue, pageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListChannelEnforcementDueRow{}
	for rows.Next() {
		var i ListChannelEnforcementDueRow
		if err := rows.Scan(&i.UserID, &i.TelegramID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listChannelExemptions = `-- name: ListChannelExemptions :many
SELECT x.user_id, x.reason, x.granted_by, x.granted_at, x.expires_at, COALESCE(a.display_name, '') AS granted_by_name
FROM channel_exemptions x
LEFT JOIN admin_users a ON a.id = x.granted_by
ORDER BY x.granted_at DESC
LIMIT $1
`

type ListChannelExemptionsRow struct {
	UserID        pgtype.UUID        `json:"user_id"`
	Reason        string             `json:"reason"`
	GrantedBy     pgtype.UUID        `json:"granted_by"`
	GrantedAt     pgtype.Timestamptz `json:"granted_at"`
	ExpiresAt     pgtype.Timestamptz `json:"expires_at"`
	GrantedByName string             `json:"granted_by_name"`
}

func (q *Queries) ListChannelExemptions(ctx context.Context, pageSize int32) ([]ListChannelExemptionsRow, error) {
	rows, err := q.db.Query(ctx, listChannelExemptions, pageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListChannelExemptionsRow{}
	for rows.Next() {
		var i ListChannelExemptionsRow
		if err := rows.Scan(
			&i.UserID,
			&i.Reason,
			&i.GrantedBy,
			&i.GrantedAt,
			&i.ExpiresAt,
			&i.GrantedByName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCustomerMemberships = `-- name: ListCustomerMemberships :many
SELECT user_id, channel_id, state, checked_at, left_at FROM channel_memberships WHERE user_id = $1
`

func (q *Queries) ListCustomerMemberships(ctx context.Context, userID pgtype.UUID) ([]ChannelMembership, error) {
	rows, err := q.db.Query(ctx, listCustomerMemberships, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ChannelMembership{}
	for rows.Next() {
		var i ChannelMembership
		if err := rows.Scan(
			&i.UserID,
			&i.ChannelID,
			&i.State,
			&i.CheckedAt,
			&i.LeftAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCustomersForChannelRecheck = `-- name: ListCustomersForChannelRecheck :many
SELECT DISTINCT r.user_id, r.telegram_id
FROM remnawave_users r
JOIN users u ON u.id = r.user_id AND u.status = 'active'
WHERE r.telegram_id IS NOT NULL
  AND NOT EXISTS (SELECT 1 FROM channel_exemptions x
    WHERE x.user_id = r.user_id AND (x.expires_at IS NULL OR x.expires_at > now()))
  AND (
    NOT EXISTS (SELECT 1 FROM channel_memberships m WHERE m.user_id = r.user_id)
    OR EXISTS (SELECT 1 FROM channel_memberships m
      WHERE m.user_id = r.user_id AND m.checked_at < $1)
  )
ORDER BY r.user_id
LIMIT $2
`

type ListCustomersForChannelRecheckParams struct {
	StaleBefore pgtype.Timestamptz `json:"stale_before"`
	PageSize    int32              `json:"page_size"`
}

type ListCustomersForChannelRecheckRow struct {
	UserID     pgtype.UUID `json:"user_id"`
	TelegramID pgtype.Int8 `json:"telegram_id"`
}

// Customers whose membership answer has gone stale, oldest first.
//
// A customer with no record at all is included, because "never checked" and
// "checked long ago" need the same thing done about them.
func (q *Queries) ListCustomersForChannelRecheck(ctx context.Context, arg ListCustomersForChannelRecheckParams) ([]ListCustomersForChannelRecheckRow, error) {
	rows, err := q.db.Query(ctx, listCustomersForChannelRecheck, arg.StaleBefore, arg.PageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCustomersForChannelRecheckRow{}
	for rows.Next() {
		var i ListCustomersForChannelRecheckRow
		if err := rows.Scan(&i.UserID, &i.TelegramID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEnabledChannels = `-- name: ListEnabledChannels :many
SELECT id, telegram_chat_id, username, title, invite_url, enabled, require_for_purchase, require_for_activation, sort_order, created_at, updated_at, created_by FROM required_channels WHERE enabled ORDER BY sort_order, title
`

func (q *Queries) ListEnabledChannels(ctx context.Context) ([]RequiredChannel, error) {
	rows, err := q.db.Query(ctx, listEnabledChannels)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RequiredChannel{}
	for rows.Next() {
		var i RequiredChannel
		if err := rows.Scan(
			&i.ID,
			&i.TelegramChatID,
			&i.Username,
			&i.Title,
			&i.InviteUrl,
			&i.Enabled,
			&i.RequireForPurchase,
			&i.RequireForActivation,
			&i.SortOrder,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CreatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRequiredChannels = `-- name: ListRequiredChannels :many

SELECT id, telegram_chat_id, username, title, invite_url, enabled, require_for_purchase, require_for_activation, sort_order, created_at, updated_at, created_by FROM required_channels ORDER BY sort_order, title
`

// Mandatory channel subscription.
func (q *Queries) ListRequiredChannels(ctx context.Context) ([]RequiredChannel, error) {
	rows, err := q.db.Query(ctx, listRequiredChannels)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RequiredChannel{}
	for rows.Next() {
		var i RequiredChannel
		if err := rows.Scan(
			&i.ID,
			&i.TelegramChatID,
			&i.Username,
			&i.Title,
			&i.InviteUrl,
			&i.Enabled,
			&i.RequireForPurchase,
			&i.RequireForActivation,
			&i.SortOrder,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CreatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recordMembership = `-- name: RecordMembership :one
INSERT INTO channel_memberships (user_id, channel_id, state, left_at)
VALUES (
  $1, $2, $3,
  CASE WHEN $3::text = 'absent' THEN now() ELSE NULL END
)
ON CONFLICT (user_id, channel_id) DO UPDATE SET
  state = EXCLUDED.state,
  checked_at = now(),
  left_at = CASE
    WHEN EXCLUDED.state = 'absent' THEN COALESCE(channel_memberships.left_at, now())
    WHEN EXCLUDED.state = 'member' THEN NULL
    ELSE channel_memberships.left_at
  END
RETURNING user_id, channel_id, state, checked_at, left_at
`

type RecordMembershipParams struct {
	UserID    pgtype.UUID `json:"user_id"`
	ChannelID pgtype.UUID `json:"channel_id"`
	State     string      `json:"state"`
}

// `left_at` is set the first time absence is seen and cleared on return, so the
// grace clock measures from when the customer actually left rather than from
// when a sweep noticed.
func (q *Queries) RecordMembership(ctx context.Context, arg RecordMembershipParams) (ChannelMembership, error) {
	row := q.db.QueryRow(ctx, recordMembership, arg.UserID, arg.ChannelID, arg.State)
	var i ChannelMembership
	err := row.Scan(
		&i.UserID,
		&i.ChannelID,
		&i.State,
		&i.CheckedAt,
		&i.LeftAt,
	)
	return i, err
}

const revokeChannelExemption = `-- name: RevokeChannelExemption :exec
DELETE FROM channel_exemptions WHERE user_id = $1
`

func (q *Queries) RevokeChannelExemption(ctx context.Context, userID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, revokeChannelExemption, userID)
	return err
}

const setChannelEnforcement = `-- name: SetChannelEnforcement :one
INSERT INTO channel_enforcement (user_id, state, warned_at, grace_until, suspended_at, restored_at)
VALUES (
  $1, $2,
  CASE WHEN $3::boolean THEN now() ELSE NULL END,
  $4,
  CASE WHEN $2::text = 'suspended' THEN now() ELSE NULL END,
  CASE WHEN $5::boolean THEN now() ELSE NULL END
)
ON CONFLICT (user_id) DO UPDATE SET
  state = EXCLUDED.state,
  warned_at = CASE WHEN $3::boolean THEN now() ELSE channel_enforcement.warned_at END,
  grace_until = EXCLUDED.grace_until,
  suspended_at = CASE
    WHEN EXCLUDED.state = 'suspended' THEN COALESCE(channel_enforcement.suspended_at, now())
    ELSE NULL END,
  restored_at = CASE WHEN $5::boolean THEN now() ELSE channel_enforcement.restored_at END,
  updated_at = now()
RETURNING user_id, state, warned_at, grace_until, suspended_at, restored_at, updated_at
`

type SetChannelEnforcementParams struct {
	UserID     pgtype.UUID        `json:"user_id"`
	State      string             `json:"state"`
	Warn       bool               `json:"warn"`
	GraceUntil pgtype.Timestamptz `json:"grace_until"`
	Restore    bool               `json:"restore"`
}

func (q *Queries) SetChannelEnforcement(ctx context.Context, arg SetChannelEnforcementParams) (ChannelEnforcement, error) {
	row := q.db.QueryRow(ctx, setChannelEnforcement,
		arg.UserID,
		arg.State,
		arg.Warn,
		arg.GraceUntil,
		arg.Restore,
	)
	var i ChannelEnforcement
	err := row.Scan(
		&i.UserID,
		&i.State,
		&i.WarnedAt,
		&i.GraceUntil,
		&i.SuspendedAt,
		&i.RestoredAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertRequiredChannel = `-- name: UpsertRequiredChannel :one
INSERT INTO required_channels (
  telegram_chat_id, username, title, invite_url, enabled,
  require_for_purchase, require_for_activation, sort_order, created_by
) VALUES (
  $1, $2, $3, $4,
  $5, $6, $7,
  $8, $9
)
ON CONFLICT (telegram_chat_id) DO UPDATE SET
  username = EXCLUDED.username, title = EXCLUDED.title, invite_url = EXCLUDED.invite_url,
  enabled = EXCLUDED.enabled, require_for_purchase = EXCLUDED.require_for_purchase,
  require_for_activation = EXCLUDED.require_for_activation,
  sort_order = EXCLUDED.sort_order, updated_at = now()
RETURNING id, telegram_chat_id, username, title, invite_url, enabled, require_for_purchase, require_for_activation, sort_order, created_at, updated_at, created_by
`

type UpsertRequiredChannelParams struct {
	TelegramChatID       int64       `json:"telegram_chat_id"`
	Username             pgtype.Text `json:"username"`
	Title                string      `json:"title"`
	InviteUrl            pgtype.Text `json:"invite_url"`
	Enabled              bool        `json:"enabled"`
	RequireForPurchase   bool        `json:"require_for_purchase"`
	RequireForActivation bool        `json:"require_for_activation"`
	SortOrder            int32       `json:"sort_order"`
	CreatedBy            pgtype.UUID `json:"created_by"`
}

func (q *Queries) UpsertRequiredChannel(ctx context.Context, arg UpsertRequiredChannelParams) (RequiredChannel, error) {
	row := q.db.QueryRow(ctx, upsertRequiredChannel,
		arg.TelegramChatID,
		arg.Username,
		arg.Title,
		arg.InviteUrl,
		arg.Enabled,
		arg.RequireForPurchase,
		arg.RequireForActivation,
		arg.SortOrder,
		arg.CreatedBy,
	)
	var i RequiredChannel
	err := row.Scan(
		&i.ID,
		&i.TelegramChatID,
		&i.Username,
		&i.Title,
		&i.InviteUrl,
		&i.Enabled,
		&i.RequireForPurchase,
		&i.RequireForActivation,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CreatedBy,
	)
	return i, err
}
