// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: connect.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteConnectClient = `-- name: DeleteConnectClient :execrows
DELETE FROM connect_clients WHERE id = $1
`

func (q *Queries) DeleteConnectClient(ctx context.Context, id pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteConnectClient, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteConnectPlatform = `-- name: DeleteConnectPlatform :execrows
DELETE FROM connect_platforms WHERE slug = $1
`

func (q *Queries) DeleteConnectPlatform(ctx context.Context, slug string) (int64, error) {
	result, err := q.db.Exec(ctx, deleteConnectPlatform, slug)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listConnectClients = `-- name: ListConnectClients :many
SELECT id, platform_slug, name, scheme, download_url, instructions_en, instructions_ru,
       enabled, sort_order, updated_at, updated_by
FROM connect_clients
ORDER BY platform_slug, sort_order, name
`

func (q *Queries) ListConnectClients(ctx context.Context) ([]ConnectClient, error) {
	rows, err := q.db.Query(ctx, listConnectClients)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ConnectClient{}
	for rows.Next() {
		var i ConnectClient
		if err := rows.Scan(
			&i.ID,
			&i.PlatformSlug,
			&i.Name,
			&i.Scheme,
			&i.DownloadUrl,
			&i.InstructionsEn,
			&i.InstructionsRu,
			&i.Enabled,
			&i.SortOrder,
			&i.UpdatedAt,
			&i.UpdatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listConnectPlatforms = `-- name: ListConnectPlatforms :many
SELECT slug, label_en, label_ru, enabled, sort_order, updated_at, updated_by
FROM connect_platforms
ORDER BY sort_order, slug
`

func (q *Queries) ListConnectPlatforms(ctx context.Context) ([]ConnectPlatform, error) {
	rows, err := q.db.Query(ctx, listConnectPlatforms)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ConnectPlatform{}
	for rows.Next() {
		var i ConnectPlatform
		if err := rows.Scan(
			&i.Slug,
			&i.LabelEn,
			&i.LabelRu,
			&i.Enabled,
			&i.SortOrder,
			&i.UpdatedAt,
			&i.UpdatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEnabledConnectClients = `-- name: ListEnabledConnectClients :many
SELECT id, platform_slug, name, scheme, download_url, instructions_en, instructions_ru
FROM connect_clients
WHERE enabled
  AND platform_slug = $1
  -- A client on a platform somebody disabled must not be reachable by naming
  -- the platform directly, so the join carries the platform's own flag.
  AND EXISTS (
    SELECT 1 FROM connect_platforms
    WHERE connect_platforms.slug = connect_clients.platform_slug
      AND connect_platforms.enabled
  )
ORDER BY sort_order, name
`

type ListEnabledConnectClientsRow struct {
	ID             pgtype.UUID `json:"id"`
	PlatformSlug   string      `json:"platform_slug"`
	Name           string      `json:"name"`
	Scheme         string      `json:"scheme"`
	DownloadUrl    pgtype.Text `json:"download_url"`
	InstructionsEn pgtype.Text `json:"instructions_en"`
	InstructionsRu pgtype.Text `json:"instructions_ru"`
}

func (q *Queries) ListEnabledConnectClients(ctx context.Context, platformSlug string) ([]ListEnabledConnectClientsRow, error) {
	rows, err := q.db.Query(ctx, listEnabledConnectClients, platformSlug)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListEnabledConnectClientsRow{}
	for rows.Next() {
		var i ListEnabledConnectClientsRow
		if err := rows.Scan(
			&i.ID,
			&i.PlatformSlug,
			&i.Name,
			&i.Scheme,
			&i.DownloadUrl,
			&i.InstructionsEn,
			&i.InstructionsRu,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEnabledConnectPlatforms = `-- name: ListEnabledConnectPlatforms :many

SELECT slug, label_en, label_ru
FROM connect_platforms
WHERE enabled
ORDER BY sort_order, slug
`

type ListEnabledConnectPlatformsRow struct {
	Slug    string `json:"slug"`
	LabelEn string `json:"label_en"`
	LabelRu string `json:"label_ru"`
}

// Connection guidance.
//
// The customer-facing reads select only enabled rows, so disabling a platform
// or a client removes it from the bot and the browser at the same moment. The
// operator reads select everything, because a disabled row is exactly what an
// operator came to the screen to re-enable.
func (q *Queries) ListEnabledConnectPlatforms(ctx context.Context) ([]ListEnabledConnectPlatformsRow, error) {
	rows, err := q.db.Query(ctx, listEnabledConnectPlatforms)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListEnabledConnectPlatformsRow{}
	for rows.Next() {
		var i ListEnabledConnectPlatformsRow
		if err := rows.Scan(&i.Slug, &i.LabelEn, &i.LabelRu); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertConnectClient = `-- name: UpsertConnectClient :one
INSERT INTO connect_clients (
  id, platform_slug, name, scheme, download_url,
  instructions_en, instructions_ru, enabled, sort_order, updated_by
)
VALUES (
  COALESCE($6::uuid, gen_random_uuid()), $1, $2, $3,
  $7, $8, $9,
  $4, $5, $10
)
ON CONFLICT (id) DO UPDATE
SET platform_slug = EXCLUDED.platform_slug,
    name = EXCLUDED.name,
    scheme = EXCLUDED.scheme,
    download_url = EXCLUDED.download_url,
    instructions_en = EXCLUDED.instructions_en,
    instructions_ru = EXCLUDED.instructions_ru,
    enabled = EXCLUDED.enabled,
    sort_order = EXCLUDED.sort_order,
    updated_at = now(),
    updated_by = EXCLUDED.updated_by
RETURNING id, platform_slug, name, scheme, download_url, instructions_en, instructions_ru,
          enabled, sort_order, updated_at, updated_by
`

type UpsertConnectClientParams struct {
	PlatformSlug   string      `json:"platform_slug"`
	Name           string      `json:"name"`
	Scheme         string      `json:"scheme"`
	Enabled        bool        `json:"enabled"`
	SortOrder      int32       `json:"sort_order"`
	ID             pgtype.UUID `json:"id"`
	DownloadUrl    pgtype.Text `json:"download_url"`
	InstructionsEn pgtype.Text `json:"instructions_en"`
	InstructionsRu pgtype.Text `json:"instructions_ru"`
	UpdatedBy      pgtype.UUID `json:"updated_by"`
}

// The identifier is optional: absent creates, present updates. The pairing of
// platform and name is unique, so a rename that collides is refused by the
// table rather than silently producing two rows the screen shows twice.
func (q *Queries) UpsertConnectClient(ctx context.Context, arg UpsertConnectClientParams) (ConnectClient, error) {
	row := q.db.QueryRow(ctx, upsertConnectClient,
		arg.PlatformSlug,
		arg.Name,
		arg.Scheme,
		arg.Enabled,
		arg.SortOrder,
		arg.ID,
		arg.DownloadUrl,
		arg.InstructionsEn,
		arg.InstructionsRu,
		arg.UpdatedBy,
	)
	var i ConnectClient
	err := row.Scan(
		&i.ID,
		&i.PlatformSlug,
		&i.Name,
		&i.Scheme,
		&i.DownloadUrl,
		&i.InstructionsEn,
		&i.InstructionsRu,
		&i.Enabled,
		&i.SortOrder,
		&i.UpdatedAt,
		&i.UpdatedBy,
	)
	return i, err
}

const upsertConnectPlatform = `-- name: UpsertConnectPlatform :one
INSERT INTO connect_platforms (slug, label_en, label_ru, enabled, sort_order, updated_by)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (slug) DO UPDATE
SET label_en = EXCLUDED.label_en,
    label_ru = EXCLUDED.label_ru,
    enabled = EXCLUDED.enabled,
    sort_order = EXCLUDED.sort_order,
    updated_at = now(),
    updated_by = EXCLUDED.updated_by
RETURNING slug, label_en, label_ru, enabled, sort_order, updated_at, updated_by
`

type UpsertConnectPlatformParams struct {
	Slug      string      `json:"slug"`
	LabelEn   string      `json:"label_en"`
	LabelRu   string      `json:"label_ru"`
	Enabled   bool        `json:"enabled"`
	SortOrder int32       `json:"sort_order"`
	UpdatedBy pgtype.UUID `json:"updated_by"`
}

func (q *Queries) UpsertConnectPlatform(ctx context.Context, arg UpsertConnectPlatformParams) (ConnectPlatform, error) {
	row := q.db.QueryRow(ctx, upsertConnectPlatform,
		arg.Slug,
		arg.LabelEn,
		arg.LabelRu,
		arg.Enabled,
		arg.SortOrder,
		arg.UpdatedBy,
	)
	var i ConnectPlatform
	err := row.Scan(
		&i.Slug,
		&i.LabelEn,
		&i.LabelRu,
		&i.Enabled,
		&i.SortOrder,
		&i.UpdatedAt,
		&i.UpdatedBy,
	)
	return i, err
}
