// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: customer_account.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getAccountSubscription = `-- name: GetAccountSubscription :one
SELECT s.id, s.slot, s.label, s.remnawave_user_id,
       COALESCE(l.name, p.code, '') AS plan_name,
       COALESCE(p.code, '') AS plan_code,
       COALESCE(e.status, '') AS entitlement_status,
       e.ends_at,
       -- A pause freezes the remaining time, so the customer surfaces measure
       -- "days left" from this instant rather than from now. Without it a paused
       -- subscription counts down to zero on the customer's own screen while
       -- nothing is being consumed.
       e.paused_at,
       COALESCE(v.grace_period_seconds, 0)::bigint AS grace_period_seconds,
       v.traffic_allowance_bytes,
       v.device_limit,
       v.billing_period
FROM subscriptions s
LEFT JOIN LATERAL (
  SELECT id, user_id, order_id, plan_version_id, status, starts_at, ends_at, traffic_allowance_bytes, device_limit, remnawave_squad_ids, remnawave_user_id, observed_state, reconciled_at, created_at, updated_at, subscription_id, paused_at, paused_seconds FROM entitlements ent
  WHERE ent.subscription_id = s.id AND ent.status <> 'superseded'
  ORDER BY ent.ends_at DESC LIMIT 1
) e ON true
LEFT JOIN plan_versions v ON v.id = e.plan_version_id
LEFT JOIN plans p ON p.id = v.plan_id
LEFT JOIN plan_localizations l ON l.plan_id = p.id AND l.locale = $1
WHERE s.user_id = $2 AND s.id = $3 AND s.status = 'active'
`

type GetAccountSubscriptionParams struct {
	Locale         string      `json:"locale"`
	UserID         pgtype.UUID `json:"user_id"`
	SubscriptionID pgtype.UUID `json:"subscription_id"`
}

type GetAccountSubscriptionRow struct {
	ID                    pgtype.UUID        `json:"id"`
	Slot                  int32              `json:"slot"`
	Label                 string             `json:"label"`
	RemnawaveUserID       pgtype.Int8        `json:"remnawave_user_id"`
	PlanName              string             `json:"plan_name"`
	PlanCode              string             `json:"plan_code"`
	EntitlementStatus     string             `json:"entitlement_status"`
	EndsAt                pgtype.Timestamptz `json:"ends_at"`
	PausedAt              pgtype.Timestamptz `json:"paused_at"`
	GracePeriodSeconds    int64              `json:"grace_period_seconds"`
	TrafficAllowanceBytes pgtype.Int8        `json:"traffic_allowance_bytes"`
	DeviceLimit           pgtype.Int4        `json:"device_limit"`
	BillingPeriod         pgtype.Text        `json:"billing_period"`
}

func (q *Queries) GetAccountSubscription(ctx context.Context, arg GetAccountSubscriptionParams) (GetAccountSubscriptionRow, error) {
	row := q.db.QueryRow(ctx, getAccountSubscription, arg.Locale, arg.UserID, arg.SubscriptionID)
	var i GetAccountSubscriptionRow
	err := row.Scan(
		&i.ID,
		&i.Slot,
		&i.Label,
		&i.RemnawaveUserID,
		&i.PlanName,
		&i.PlanCode,
		&i.EntitlementStatus,
		&i.EndsAt,
		&i.PausedAt,
		&i.GracePeriodSeconds,
		&i.TrafficAllowanceBytes,
		&i.DeviceLimit,
		&i.BillingPeriod,
	)
	return i, err
}

const listAccountSubscriptions = `-- name: ListAccountSubscriptions :many

SELECT s.id, s.slot, s.label, s.remnawave_user_id,
       COALESCE(l.name, p.code, '') AS plan_name,
       COALESCE(p.code, '') AS plan_code,
       COALESCE(e.status, '') AS entitlement_status,
       e.ends_at,
       -- A pause freezes the remaining time, so the customer surfaces measure
       -- "days left" from this instant rather than from now. Without it a paused
       -- subscription counts down to zero on the customer's own screen while
       -- nothing is being consumed.
       e.paused_at,
       COALESCE(v.grace_period_seconds, 0)::bigint AS grace_period_seconds,
       v.traffic_allowance_bytes,
       v.device_limit,
       v.billing_period
FROM subscriptions s
LEFT JOIN LATERAL (
  SELECT id, user_id, order_id, plan_version_id, status, starts_at, ends_at, traffic_allowance_bytes, device_limit, remnawave_squad_ids, remnawave_user_id, observed_state, reconciled_at, created_at, updated_at, subscription_id, paused_at, paused_seconds FROM entitlements ent
  WHERE ent.subscription_id = s.id AND ent.status <> 'superseded'
  ORDER BY ent.ends_at DESC LIMIT 1
) e ON true
LEFT JOIN plan_versions v ON v.id = e.plan_version_id
LEFT JOIN plans p ON p.id = v.plan_id
LEFT JOIN plan_localizations l ON l.plan_id = p.id AND l.locale = $1
WHERE s.user_id = $2 AND s.status = 'active'
ORDER BY s.slot
`

type ListAccountSubscriptionsParams struct {
	Locale string      `json:"locale"`
	UserID pgtype.UUID `json:"user_id"`
}

type ListAccountSubscriptionsRow struct {
	ID                    pgtype.UUID        `json:"id"`
	Slot                  int32              `json:"slot"`
	Label                 string             `json:"label"`
	RemnawaveUserID       pgtype.Int8        `json:"remnawave_user_id"`
	PlanName              string             `json:"plan_name"`
	PlanCode              string             `json:"plan_code"`
	EntitlementStatus     string             `json:"entitlement_status"`
	EndsAt                pgtype.Timestamptz `json:"ends_at"`
	PausedAt              pgtype.Timestamptz `json:"paused_at"`
	GracePeriodSeconds    int64              `json:"grace_period_seconds"`
	TrafficAllowanceBytes pgtype.Int8        `json:"traffic_allowance_bytes"`
	DeviceLimit           pgtype.Int4        `json:"device_limit"`
	BillingPeriod         pgtype.Text        `json:"billing_period"`
}

// The customer web panel's own read model for v0.9.
//
// Every statement is scoped by `user_id`. Ownership is part of the query rather
// than a check the caller is trusted to perform first, so an identifier lifted
// from a URL can never address somebody else's subscription.
// One row per active subscription, with the entitlement currently in force and
// the plan version it was bought under.
//
// The lateral join takes the latest entitlement that has not been superseded:
// an extension writes a new row rather than editing the old one, so "current"
// is the newest live row rather than the only row.
func (q *Queries) ListAccountSubscriptions(ctx context.Context, arg ListAccountSubscriptionsParams) ([]ListAccountSubscriptionsRow, error) {
	rows, err := q.db.Query(ctx, listAccountSubscriptions, arg.Locale, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAccountSubscriptionsRow{}
	for rows.Next() {
		var i ListAccountSubscriptionsRow
		if err := rows.Scan(
			&i.ID,
			&i.Slot,
			&i.Label,
			&i.RemnawaveUserID,
			&i.PlanName,
			&i.PlanCode,
			&i.EntitlementStatus,
			&i.EndsAt,
			&i.PausedAt,
			&i.GracePeriodSeconds,
			&i.TrafficAllowanceBytes,
			&i.DeviceLimit,
			&i.BillingPeriod,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const renameAccountSubscription = `-- name: RenameAccountSubscription :one
UPDATE subscriptions
SET label = $1, updated_at = now()
WHERE id = $2 AND user_id = $3 AND status = 'active'
RETURNING id, user_id, slot, label, status, remnawave_user_id, remnawave_username, observed_state, reconciled_at, created_at, updated_at, closed_at
`

type RenameAccountSubscriptionParams struct {
	Label          string      `json:"label"`
	SubscriptionID pgtype.UUID `json:"subscription_id"`
	UserID         pgtype.UUID `json:"user_id"`
}

// The label is what every screen and notification uses to name a subscription,
// which is what makes several concurrent ones legible.
func (q *Queries) RenameAccountSubscription(ctx context.Context, arg RenameAccountSubscriptionParams) (Subscription, error) {
	row := q.db.QueryRow(ctx, renameAccountSubscription, arg.Label, arg.SubscriptionID, arg.UserID)
	var i Subscription
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Slot,
		&i.Label,
		&i.Status,
		&i.RemnawaveUserID,
		&i.RemnawaveUsername,
		&i.ObservedState,
		&i.ReconciledAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ClosedAt,
	)
	return i, err
}

const updateAccountProfile = `-- name: UpdateAccountProfile :one
UPDATE users
SET locale = $1, timezone = $2, updated_at = now()
WHERE id = $3 AND status = 'active'
RETURNING id, status, locale, created_at, updated_at, timezone, suspended_at, deleted_at, anonymized_at, retention_until
`

type UpdateAccountProfileParams struct {
	Locale   string      `json:"locale"`
	Timezone string      `json:"timezone"`
	UserID   pgtype.UUID `json:"user_id"`
}

// The customer's own locale and timezone. Both are validated in Go against the
// supported set before they reach here.
func (q *Queries) UpdateAccountProfile(ctx context.Context, arg UpdateAccountProfileParams) (User, error) {
	row := q.db.QueryRow(ctx, updateAccountProfile, arg.Locale, arg.Timezone, arg.UserID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Status,
		&i.Locale,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Timezone,
		&i.SuspendedAt,
		&i.DeletedAt,
		&i.AnonymizedAt,
		&i.RetentionUntil,
	)
	return i, err
}
