// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: gifts.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const claimGift = `-- name: ClaimGift :one
UPDATE gifts
SET status = 'claimed',
    recipient_user_id = $1,
    claim_entitlement_id = $2,
    claim_ledger_transaction_id = $3,
    claimed_at = now(),
    updated_at = now()
WHERE id = $4
  AND status = 'deliverable'
  AND expires_at > now()
RETURNING id, order_id, sender_user_id, kind, plan_version_id, addon_version_id, credit_minor, currency, code_hash, code_hint, recipient_telegram_id, recipient_user_id, sender_message, status, claim_attempts, claim_entitlement_id, claim_ledger_transaction_id, expires_at, claimed_at, revoked_at, revoked_by, revoke_reason, created_at, updated_at
`

type ClaimGiftParams struct {
	RecipientUserID          pgtype.UUID `json:"recipient_user_id"`
	ClaimEntitlementID       pgtype.UUID `json:"claim_entitlement_id"`
	ClaimLedgerTransactionID pgtype.UUID `json:"claim_ledger_transaction_id"`
	GiftID                   pgtype.UUID `json:"gift_id"`
}

// Single redemption by construction: the predicate only matches a deliverable,
// unexpired gift, so a second claim of the same code updates no row.
func (q *Queries) ClaimGift(ctx context.Context, arg ClaimGiftParams) (Gift, error) {
	row := q.db.QueryRow(ctx, claimGift,
		arg.RecipientUserID,
		arg.ClaimEntitlementID,
		arg.ClaimLedgerTransactionID,
		arg.GiftID,
	)
	var i Gift
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.SenderUserID,
		&i.Kind,
		&i.PlanVersionID,
		&i.AddonVersionID,
		&i.CreditMinor,
		&i.Currency,
		&i.CodeHash,
		&i.CodeHint,
		&i.RecipientTelegramID,
		&i.RecipientUserID,
		&i.SenderMessage,
		&i.Status,
		&i.ClaimAttempts,
		&i.ClaimEntitlementID,
		&i.ClaimLedgerTransactionID,
		&i.ExpiresAt,
		&i.ClaimedAt,
		&i.RevokedAt,
		&i.RevokedBy,
		&i.RevokeReason,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const countGiftsByStatus = `-- name: CountGiftsByStatus :many
SELECT status, count(*)::bigint AS total FROM gifts GROUP BY status ORDER BY status
`

type CountGiftsByStatusRow struct {
	Status string `json:"status"`
	Total  int64  `json:"total"`
}

func (q *Queries) CountGiftsByStatus(ctx context.Context) ([]CountGiftsByStatusRow, error) {
	rows, err := q.db.Query(ctx, countGiftsByStatus)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CountGiftsByStatusRow{}
	for rows.Next() {
		var i CountGiftsByStatusRow
		if err := rows.Scan(&i.Status, &i.Total); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createGift = `-- name: CreateGift :one


INSERT INTO gifts (
  order_id, sender_user_id, kind, plan_version_id, addon_version_id, credit_minor,
  currency, code_hash, code_hint, recipient_telegram_id, sender_message, expires_at
) VALUES (
  $1, $2, $3,
  $4, $5, $6,
  $7, $8, $9,
  $10, $11,
  now() + $12::interval
)
ON CONFLICT (order_id) DO NOTHING
RETURNING id, order_id, sender_user_id, kind, plan_version_id, addon_version_id, credit_minor, currency, code_hash, code_hint, recipient_telegram_id, recipient_user_id, sender_message, status, claim_attempts, claim_entitlement_id, claim_ledger_transaction_id, expires_at, claimed_at, revoked_at, revoked_by, revoke_reason, created_at, updated_at
`

type CreateGiftParams struct {
	OrderID             pgtype.UUID     `json:"order_id"`
	SenderUserID        pgtype.UUID     `json:"sender_user_id"`
	Kind                string          `json:"kind"`
	PlanVersionID       pgtype.UUID     `json:"plan_version_id"`
	AddonVersionID      pgtype.UUID     `json:"addon_version_id"`
	CreditMinor         pgtype.Int8     `json:"credit_minor"`
	Currency            string          `json:"currency"`
	CodeHash            []byte          `json:"code_hash"`
	CodeHint            string          `json:"code_hint"`
	RecipientTelegramID pgtype.Int8     `json:"recipient_telegram_id"`
	SenderMessage       pgtype.Text     `json:"sender_message"`
	Lifetime            pgtype.Interval `json:"lifetime"`
}

// Gifts and personal offers.
//
// A gift is bought by one customer for another, so every query here is careful
// about which side it is answering for: the sender sees their own order and a
// code hint, the recipient sees only what they were given.
// ---------------------------------------------------------------------------
// Gifts
// ---------------------------------------------------------------------------
func (q *Queries) CreateGift(ctx context.Context, arg CreateGiftParams) (Gift, error) {
	row := q.db.QueryRow(ctx, createGift,
		arg.OrderID,
		arg.SenderUserID,
		arg.Kind,
		arg.PlanVersionID,
		arg.AddonVersionID,
		arg.CreditMinor,
		arg.Currency,
		arg.CodeHash,
		arg.CodeHint,
		arg.RecipientTelegramID,
		arg.SenderMessage,
		arg.Lifetime,
	)
	var i Gift
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.SenderUserID,
		&i.Kind,
		&i.PlanVersionID,
		&i.AddonVersionID,
		&i.CreditMinor,
		&i.Currency,
		&i.CodeHash,
		&i.CodeHint,
		&i.RecipientTelegramID,
		&i.RecipientUserID,
		&i.SenderMessage,
		&i.Status,
		&i.ClaimAttempts,
		&i.ClaimEntitlementID,
		&i.ClaimLedgerTransactionID,
		&i.ExpiresAt,
		&i.ClaimedAt,
		&i.RevokedAt,
		&i.RevokedBy,
		&i.RevokeReason,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createPersonalOffer = `-- name: CreatePersonalOffer :one

INSERT INTO personal_offers (
  user_id, promotion_id, plan_id, title_ru, title_en, terms_ru, terms_en,
  starts_at, expires_at, created_by
) VALUES (
  $1, $2, $3,
  $4, $5, $6, $7,
  $8, $9, $10
)
ON CONFLICT (user_id, promotion_id) WHERE status = 'active' DO NOTHING
RETURNING id, user_id, promotion_id, plan_id, title_ru, title_en, terms_ru, terms_en, status, starts_at, expires_at, order_id, created_by, created_at, resolved_at
`

type CreatePersonalOfferParams struct {
	UserID      pgtype.UUID        `json:"user_id"`
	PromotionID pgtype.UUID        `json:"promotion_id"`
	PlanID      pgtype.UUID        `json:"plan_id"`
	TitleRu     string             `json:"title_ru"`
	TitleEn     string             `json:"title_en"`
	TermsRu     string             `json:"terms_ru"`
	TermsEn     string             `json:"terms_en"`
	StartsAt    pgtype.Timestamptz `json:"starts_at"`
	ExpiresAt   pgtype.Timestamptz `json:"expires_at"`
	CreatedBy   pgtype.UUID        `json:"created_by"`
}

// ---------------------------------------------------------------------------
// Personal offers
// ---------------------------------------------------------------------------
// The partial unique index on active offers is what makes a re-run of a
// targeting job idempotent: the second insert conflicts and returns nothing.
func (q *Queries) CreatePersonalOffer(ctx context.Context, arg CreatePersonalOfferParams) (PersonalOffer, error) {
	row := q.db.QueryRow(ctx, createPersonalOffer,
		arg.UserID,
		arg.PromotionID,
		arg.PlanID,
		arg.TitleRu,
		arg.TitleEn,
		arg.TermsRu,
		arg.TermsEn,
		arg.StartsAt,
		arg.ExpiresAt,
		arg.CreatedBy,
	)
	var i PersonalOffer
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.PromotionID,
		&i.PlanID,
		&i.TitleRu,
		&i.TitleEn,
		&i.TermsRu,
		&i.TermsEn,
		&i.Status,
		&i.StartsAt,
		&i.ExpiresAt,
		&i.OrderID,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.ResolvedAt,
	)
	return i, err
}

const dismissPersonalOffer = `-- name: DismissPersonalOffer :one
UPDATE personal_offers
SET status = 'dismissed', resolved_at = now()
WHERE id = $1 AND user_id = $2 AND status = 'active'
RETURNING id, user_id, promotion_id, plan_id, title_ru, title_en, terms_ru, terms_en, status, starts_at, expires_at, order_id, created_by, created_at, resolved_at
`

type DismissPersonalOfferParams struct {
	OfferID pgtype.UUID `json:"offer_id"`
	UserID  pgtype.UUID `json:"user_id"`
}

func (q *Queries) DismissPersonalOffer(ctx context.Context, arg DismissPersonalOfferParams) (PersonalOffer, error) {
	row := q.db.QueryRow(ctx, dismissPersonalOffer, arg.OfferID, arg.UserID)
	var i PersonalOffer
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.PromotionID,
		&i.PlanID,
		&i.TitleRu,
		&i.TitleEn,
		&i.TermsRu,
		&i.TermsEn,
		&i.Status,
		&i.StartsAt,
		&i.ExpiresAt,
		&i.OrderID,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.ResolvedAt,
	)
	return i, err
}

const expireGifts = `-- name: ExpireGifts :many
UPDATE gifts
SET status = 'expired', updated_at = now()
WHERE status = 'deliverable' AND expires_at <= now()
RETURNING id, order_id, sender_user_id, kind, plan_version_id, addon_version_id, credit_minor, currency, code_hash, code_hint, recipient_telegram_id, recipient_user_id, sender_message, status, claim_attempts, claim_entitlement_id, claim_ledger_transaction_id, expires_at, claimed_at, revoked_at, revoked_by, revoke_reason, created_at, updated_at
`

func (q *Queries) ExpireGifts(ctx context.Context) ([]Gift, error) {
	rows, err := q.db.Query(ctx, expireGifts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Gift{}
	for rows.Next() {
		var i Gift
		if err := rows.Scan(
			&i.ID,
			&i.OrderID,
			&i.SenderUserID,
			&i.Kind,
			&i.PlanVersionID,
			&i.AddonVersionID,
			&i.CreditMinor,
			&i.Currency,
			&i.CodeHash,
			&i.CodeHint,
			&i.RecipientTelegramID,
			&i.RecipientUserID,
			&i.SenderMessage,
			&i.Status,
			&i.ClaimAttempts,
			&i.ClaimEntitlementID,
			&i.ClaimLedgerTransactionID,
			&i.ExpiresAt,
			&i.ClaimedAt,
			&i.RevokedAt,
			&i.RevokedBy,
			&i.RevokeReason,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const expirePersonalOffers = `-- name: ExpirePersonalOffers :execrows
UPDATE personal_offers
SET status = 'expired', resolved_at = now()
WHERE status = 'active' AND expires_at <= now()
`

func (q *Queries) ExpirePersonalOffers(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, expirePersonalOffers)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getActiveOfferForPromotion = `-- name: GetActiveOfferForPromotion :one
SELECT id, user_id, promotion_id, plan_id, title_ru, title_en, terms_ru, terms_en, status, starts_at, expires_at, order_id, created_by, created_at, resolved_at FROM personal_offers
WHERE user_id = $1
  AND promotion_id = $2
  AND status = 'active'
  AND starts_at <= now()
  AND expires_at > now()
`

type GetActiveOfferForPromotionParams struct {
	UserID      pgtype.UUID `json:"user_id"`
	PromotionID pgtype.UUID `json:"promotion_id"`
}

func (q *Queries) GetActiveOfferForPromotion(ctx context.Context, arg GetActiveOfferForPromotionParams) (PersonalOffer, error) {
	row := q.db.QueryRow(ctx, getActiveOfferForPromotion, arg.UserID, arg.PromotionID)
	var i PersonalOffer
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.PromotionID,
		&i.PlanID,
		&i.TitleRu,
		&i.TitleEn,
		&i.TermsRu,
		&i.TermsEn,
		&i.Status,
		&i.StartsAt,
		&i.ExpiresAt,
		&i.OrderID,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.ResolvedAt,
	)
	return i, err
}

const getGift = `-- name: GetGift :one
SELECT id, order_id, sender_user_id, kind, plan_version_id, addon_version_id, credit_minor, currency, code_hash, code_hint, recipient_telegram_id, recipient_user_id, sender_message, status, claim_attempts, claim_entitlement_id, claim_ledger_transaction_id, expires_at, claimed_at, revoked_at, revoked_by, revoke_reason, created_at, updated_at FROM gifts WHERE id = $1
`

func (q *Queries) GetGift(ctx context.Context, id pgtype.UUID) (Gift, error) {
	row := q.db.QueryRow(ctx, getGift, id)
	var i Gift
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.SenderUserID,
		&i.Kind,
		&i.PlanVersionID,
		&i.AddonVersionID,
		&i.CreditMinor,
		&i.Currency,
		&i.CodeHash,
		&i.CodeHint,
		&i.RecipientTelegramID,
		&i.RecipientUserID,
		&i.SenderMessage,
		&i.Status,
		&i.ClaimAttempts,
		&i.ClaimEntitlementID,
		&i.ClaimLedgerTransactionID,
		&i.ExpiresAt,
		&i.ClaimedAt,
		&i.RevokedAt,
		&i.RevokedBy,
		&i.RevokeReason,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getGiftByCodeHash = `-- name: GetGiftByCodeHash :one
SELECT id, order_id, sender_user_id, kind, plan_version_id, addon_version_id, credit_minor, currency, code_hash, code_hint, recipient_telegram_id, recipient_user_id, sender_message, status, claim_attempts, claim_entitlement_id, claim_ledger_transaction_id, expires_at, claimed_at, revoked_at, revoked_by, revoke_reason, created_at, updated_at FROM gifts WHERE code_hash = $1
`

// The claim path's only lookup. The plaintext code never reaches the database.
func (q *Queries) GetGiftByCodeHash(ctx context.Context, codeHash []byte) (Gift, error) {
	row := q.db.QueryRow(ctx, getGiftByCodeHash, codeHash)
	var i Gift
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.SenderUserID,
		&i.Kind,
		&i.PlanVersionID,
		&i.AddonVersionID,
		&i.CreditMinor,
		&i.Currency,
		&i.CodeHash,
		&i.CodeHint,
		&i.RecipientTelegramID,
		&i.RecipientUserID,
		&i.SenderMessage,
		&i.Status,
		&i.ClaimAttempts,
		&i.ClaimEntitlementID,
		&i.ClaimLedgerTransactionID,
		&i.ExpiresAt,
		&i.ClaimedAt,
		&i.RevokedAt,
		&i.RevokedBy,
		&i.RevokeReason,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getGiftByOrder = `-- name: GetGiftByOrder :one
SELECT id, order_id, sender_user_id, kind, plan_version_id, addon_version_id, credit_minor, currency, code_hash, code_hint, recipient_telegram_id, recipient_user_id, sender_message, status, claim_attempts, claim_entitlement_id, claim_ledger_transaction_id, expires_at, claimed_at, revoked_at, revoked_by, revoke_reason, created_at, updated_at FROM gifts WHERE order_id = $1
`

func (q *Queries) GetGiftByOrder(ctx context.Context, orderID pgtype.UUID) (Gift, error) {
	row := q.db.QueryRow(ctx, getGiftByOrder, orderID)
	var i Gift
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.SenderUserID,
		&i.Kind,
		&i.PlanVersionID,
		&i.AddonVersionID,
		&i.CreditMinor,
		&i.Currency,
		&i.CodeHash,
		&i.CodeHint,
		&i.RecipientTelegramID,
		&i.RecipientUserID,
		&i.SenderMessage,
		&i.Status,
		&i.ClaimAttempts,
		&i.ClaimEntitlementID,
		&i.ClaimLedgerTransactionID,
		&i.ExpiresAt,
		&i.ClaimedAt,
		&i.RevokedAt,
		&i.RevokedBy,
		&i.RevokeReason,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPersonalOffer = `-- name: GetPersonalOffer :one
SELECT id, user_id, promotion_id, plan_id, title_ru, title_en, terms_ru, terms_en, status, starts_at, expires_at, order_id, created_by, created_at, resolved_at FROM personal_offers WHERE id = $1
`

func (q *Queries) GetPersonalOffer(ctx context.Context, id pgtype.UUID) (PersonalOffer, error) {
	row := q.db.QueryRow(ctx, getPersonalOffer, id)
	var i PersonalOffer
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.PromotionID,
		&i.PlanID,
		&i.TitleRu,
		&i.TitleEn,
		&i.TermsRu,
		&i.TermsEn,
		&i.Status,
		&i.StartsAt,
		&i.ExpiresAt,
		&i.OrderID,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.ResolvedAt,
	)
	return i, err
}

const listActiveOffersForCustomer = `-- name: ListActiveOffersForCustomer :many
SELECT o.id, o.user_id, o.promotion_id, o.plan_id, o.title_ru, o.title_en, o.terms_ru, o.terms_en, o.status, o.starts_at, o.expires_at, o.order_id, o.created_by, o.created_at, o.resolved_at, p.id, p.code, p.kind, p.value, p.currency, p.starts_at, p.ends_at, p.redemption_limit, p.per_customer_limit, p.eligibility, p.active, p.created_at, p.stackable, p.precedence
FROM personal_offers o
JOIN promotions p ON p.id = o.promotion_id
WHERE o.user_id = $1
  AND o.status = 'active'
  AND o.starts_at <= now()
  AND o.expires_at > now()
ORDER BY o.expires_at
LIMIT $2
`

type ListActiveOffersForCustomerParams struct {
	UserID   pgtype.UUID `json:"user_id"`
	PageSize int32       `json:"page_size"`
}

type ListActiveOffersForCustomerRow struct {
	PersonalOffer PersonalOffer `json:"personal_offer"`
	Promotion     Promotion     `json:"promotion"`
}

// What the bot shows. Expired-but-not-yet-swept rows are filtered here rather
// than relying on the sweeper having run, so an offer never outlives its window
// on screen.
func (q *Queries) ListActiveOffersForCustomer(ctx context.Context, arg ListActiveOffersForCustomerParams) ([]ListActiveOffersForCustomerRow, error) {
	rows, err := q.db.Query(ctx, listActiveOffersForCustomer, arg.UserID, arg.PageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListActiveOffersForCustomerRow{}
	for rows.Next() {
		var i ListActiveOffersForCustomerRow
		if err := rows.Scan(
			&i.PersonalOffer.ID,
			&i.PersonalOffer.UserID,
			&i.PersonalOffer.PromotionID,
			&i.PersonalOffer.PlanID,
			&i.PersonalOffer.TitleRu,
			&i.PersonalOffer.TitleEn,
			&i.PersonalOffer.TermsRu,
			&i.PersonalOffer.TermsEn,
			&i.PersonalOffer.Status,
			&i.PersonalOffer.StartsAt,
			&i.PersonalOffer.ExpiresAt,
			&i.PersonalOffer.OrderID,
			&i.PersonalOffer.CreatedBy,
			&i.PersonalOffer.CreatedAt,
			&i.PersonalOffer.ResolvedAt,
			&i.Promotion.ID,
			&i.Promotion.Code,
			&i.Promotion.Kind,
			&i.Promotion.Value,
			&i.Promotion.Currency,
			&i.Promotion.StartsAt,
			&i.Promotion.EndsAt,
			&i.Promotion.RedemptionLimit,
			&i.Promotion.PerCustomerLimit,
			&i.Promotion.Eligibility,
			&i.Promotion.Active,
			&i.Promotion.CreatedAt,
			&i.Promotion.Stackable,
			&i.Promotion.Precedence,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGiftsForSender = `-- name: ListGiftsForSender :many
SELECT id, order_id, sender_user_id, kind, plan_version_id, addon_version_id, credit_minor, currency, code_hash, code_hint, recipient_telegram_id, recipient_user_id, sender_message, status, claim_attempts, claim_entitlement_id, claim_ledger_transaction_id, expires_at, claimed_at, revoked_at, revoked_by, revoke_reason, created_at, updated_at FROM gifts
WHERE sender_user_id = $1
ORDER BY created_at DESC
LIMIT $2
`

type ListGiftsForSenderParams struct {
	SenderUserID pgtype.UUID `json:"sender_user_id"`
	PageSize     int32       `json:"page_size"`
}

func (q *Queries) ListGiftsForSender(ctx context.Context, arg ListGiftsForSenderParams) ([]Gift, error) {
	rows, err := q.db.Query(ctx, listGiftsForSender, arg.SenderUserID, arg.PageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Gift{}
	for rows.Next() {
		var i Gift
		if err := rows.Scan(
			&i.ID,
			&i.OrderID,
			&i.SenderUserID,
			&i.Kind,
			&i.PlanVersionID,
			&i.AddonVersionID,
			&i.CreditMinor,
			&i.Currency,
			&i.CodeHash,
			&i.CodeHint,
			&i.RecipientTelegramID,
			&i.RecipientUserID,
			&i.SenderMessage,
			&i.Status,
			&i.ClaimAttempts,
			&i.ClaimEntitlementID,
			&i.ClaimLedgerTransactionID,
			&i.ExpiresAt,
			&i.ClaimedAt,
			&i.RevokedAt,
			&i.RevokedBy,
			&i.RevokeReason,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGiftsReceived = `-- name: ListGiftsReceived :many
SELECT id, order_id, sender_user_id, kind, plan_version_id, addon_version_id, credit_minor, currency, code_hash, code_hint, recipient_telegram_id, recipient_user_id, sender_message, status, claim_attempts, claim_entitlement_id, claim_ledger_transaction_id, expires_at, claimed_at, revoked_at, revoked_by, revoke_reason, created_at, updated_at FROM gifts
WHERE recipient_user_id = $1 AND status = 'claimed'
ORDER BY claimed_at DESC
LIMIT $2
`

type ListGiftsReceivedParams struct {
	RecipientUserID pgtype.UUID `json:"recipient_user_id"`
	PageSize        int32       `json:"page_size"`
}

func (q *Queries) ListGiftsReceived(ctx context.Context, arg ListGiftsReceivedParams) ([]Gift, error) {
	rows, err := q.db.Query(ctx, listGiftsReceived, arg.RecipientUserID, arg.PageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Gift{}
	for rows.Next() {
		var i Gift
		if err := rows.Scan(
			&i.ID,
			&i.OrderID,
			&i.SenderUserID,
			&i.Kind,
			&i.PlanVersionID,
			&i.AddonVersionID,
			&i.CreditMinor,
			&i.Currency,
			&i.CodeHash,
			&i.CodeHint,
			&i.RecipientTelegramID,
			&i.RecipientUserID,
			&i.SenderMessage,
			&i.Status,
			&i.ClaimAttempts,
			&i.ClaimEntitlementID,
			&i.ClaimLedgerTransactionID,
			&i.ExpiresAt,
			&i.ClaimedAt,
			&i.RevokedAt,
			&i.RevokedBy,
			&i.RevokeReason,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockGift = `-- name: LockGift :one
SELECT id, order_id, sender_user_id, kind, plan_version_id, addon_version_id, credit_minor, currency, code_hash, code_hint, recipient_telegram_id, recipient_user_id, sender_message, status, claim_attempts, claim_entitlement_id, claim_ledger_transaction_id, expires_at, claimed_at, revoked_at, revoked_by, revoke_reason, created_at, updated_at FROM gifts WHERE id = $1 FOR UPDATE
`

// Serialises claim, revoke, and expiry against one another. Without it two
// simultaneous claims of one code could both observe 'deliverable'.
func (q *Queries) LockGift(ctx context.Context, id pgtype.UUID) (Gift, error) {
	row := q.db.QueryRow(ctx, lockGift, id)
	var i Gift
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.SenderUserID,
		&i.Kind,
		&i.PlanVersionID,
		&i.AddonVersionID,
		&i.CreditMinor,
		&i.Currency,
		&i.CodeHash,
		&i.CodeHint,
		&i.RecipientTelegramID,
		&i.RecipientUserID,
		&i.SenderMessage,
		&i.Status,
		&i.ClaimAttempts,
		&i.ClaimEntitlementID,
		&i.ClaimLedgerTransactionID,
		&i.ExpiresAt,
		&i.ClaimedAt,
		&i.RevokedAt,
		&i.RevokedBy,
		&i.RevokeReason,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const markGiftDeliverable = `-- name: MarkGiftDeliverable :one
UPDATE gifts
SET status = 'deliverable', updated_at = now()
WHERE id = $1 AND status = 'pending'
RETURNING id, order_id, sender_user_id, kind, plan_version_id, addon_version_id, credit_minor, currency, code_hash, code_hint, recipient_telegram_id, recipient_user_id, sender_message, status, claim_attempts, claim_entitlement_id, claim_ledger_transaction_id, expires_at, claimed_at, revoked_at, revoked_by, revoke_reason, created_at, updated_at
`

// Settlement of the sender's order is what makes a gift claimable. Restricting
// the update to 'pending' means a replayed settlement changes nothing.
func (q *Queries) MarkGiftDeliverable(ctx context.Context, giftID pgtype.UUID) (Gift, error) {
	row := q.db.QueryRow(ctx, markGiftDeliverable, giftID)
	var i Gift
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.SenderUserID,
		&i.Kind,
		&i.PlanVersionID,
		&i.AddonVersionID,
		&i.CreditMinor,
		&i.Currency,
		&i.CodeHash,
		&i.CodeHint,
		&i.RecipientTelegramID,
		&i.RecipientUserID,
		&i.SenderMessage,
		&i.Status,
		&i.ClaimAttempts,
		&i.ClaimEntitlementID,
		&i.ClaimLedgerTransactionID,
		&i.ExpiresAt,
		&i.ClaimedAt,
		&i.RevokedAt,
		&i.RevokedBy,
		&i.RevokeReason,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const markGiftRefunded = `-- name: MarkGiftRefunded :one
UPDATE gifts
SET status = 'refunded', updated_at = now()
WHERE id = $1 AND status IN ('revoked', 'expired')
RETURNING id, order_id, sender_user_id, kind, plan_version_id, addon_version_id, credit_minor, currency, code_hash, code_hint, recipient_telegram_id, recipient_user_id, sender_message, status, claim_attempts, claim_entitlement_id, claim_ledger_transaction_id, expires_at, claimed_at, revoked_at, revoked_by, revoke_reason, created_at, updated_at
`

func (q *Queries) MarkGiftRefunded(ctx context.Context, giftID pgtype.UUID) (Gift, error) {
	row := q.db.QueryRow(ctx, markGiftRefunded, giftID)
	var i Gift
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.SenderUserID,
		&i.Kind,
		&i.PlanVersionID,
		&i.AddonVersionID,
		&i.CreditMinor,
		&i.Currency,
		&i.CodeHash,
		&i.CodeHint,
		&i.RecipientTelegramID,
		&i.RecipientUserID,
		&i.SenderMessage,
		&i.Status,
		&i.ClaimAttempts,
		&i.ClaimEntitlementID,
		&i.ClaimLedgerTransactionID,
		&i.ExpiresAt,
		&i.ClaimedAt,
		&i.RevokedAt,
		&i.RevokedBy,
		&i.RevokeReason,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const recordGiftClaimAttempt = `-- name: RecordGiftClaimAttempt :one
UPDATE gifts
SET claim_attempts = claim_attempts + 1, updated_at = now()
WHERE id = $1
RETURNING id, order_id, sender_user_id, kind, plan_version_id, addon_version_id, credit_minor, currency, code_hash, code_hint, recipient_telegram_id, recipient_user_id, sender_message, status, claim_attempts, claim_entitlement_id, claim_ledger_transaction_id, expires_at, claimed_at, revoked_at, revoked_by, revoke_reason, created_at, updated_at
`

// Counts a failed redemption so a code cannot be brute-forced indefinitely. The
// rate limiter in front of the endpoint is the first defence; this is the
// durable one that survives a restart.
func (q *Queries) RecordGiftClaimAttempt(ctx context.Context, giftID pgtype.UUID) (Gift, error) {
	row := q.db.QueryRow(ctx, recordGiftClaimAttempt, giftID)
	var i Gift
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.SenderUserID,
		&i.Kind,
		&i.PlanVersionID,
		&i.AddonVersionID,
		&i.CreditMinor,
		&i.Currency,
		&i.CodeHash,
		&i.CodeHint,
		&i.RecipientTelegramID,
		&i.RecipientUserID,
		&i.SenderMessage,
		&i.Status,
		&i.ClaimAttempts,
		&i.ClaimEntitlementID,
		&i.ClaimLedgerTransactionID,
		&i.ExpiresAt,
		&i.ClaimedAt,
		&i.RevokedAt,
		&i.RevokedBy,
		&i.RevokeReason,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const redeemPersonalOffer = `-- name: RedeemPersonalOffer :one
UPDATE personal_offers
SET status = 'redeemed', order_id = $1, resolved_at = now()
WHERE id = $2 AND status = 'active' AND expires_at > now()
RETURNING id, user_id, promotion_id, plan_id, title_ru, title_en, terms_ru, terms_en, status, starts_at, expires_at, order_id, created_by, created_at, resolved_at
`

type RedeemPersonalOfferParams struct {
	OrderID pgtype.UUID `json:"order_id"`
	OfferID pgtype.UUID `json:"offer_id"`
}

func (q *Queries) RedeemPersonalOffer(ctx context.Context, arg RedeemPersonalOfferParams) (PersonalOffer, error) {
	row := q.db.QueryRow(ctx, redeemPersonalOffer, arg.OrderID, arg.OfferID)
	var i PersonalOffer
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.PromotionID,
		&i.PlanID,
		&i.TitleRu,
		&i.TitleEn,
		&i.TermsRu,
		&i.TermsEn,
		&i.Status,
		&i.StartsAt,
		&i.ExpiresAt,
		&i.OrderID,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.ResolvedAt,
	)
	return i, err
}

const revokeGift = `-- name: RevokeGift :one
UPDATE gifts
SET status = 'revoked',
    revoked_at = now(),
    revoked_by = $1,
    revoke_reason = $2,
    updated_at = now()
WHERE id = $3 AND status IN ('pending', 'deliverable', 'expired')
RETURNING id, order_id, sender_user_id, kind, plan_version_id, addon_version_id, credit_minor, currency, code_hash, code_hint, recipient_telegram_id, recipient_user_id, sender_message, status, claim_attempts, claim_entitlement_id, claim_ledger_transaction_id, expires_at, claimed_at, revoked_at, revoked_by, revoke_reason, created_at, updated_at
`

type RevokeGiftParams struct {
	RevokedBy    pgtype.UUID `json:"revoked_by"`
	RevokeReason pgtype.Text `json:"revoke_reason"`
	GiftID       pgtype.UUID `json:"gift_id"`
}

// An operator may reclaim a gift that has not been redeemed. A claimed gift is
// deliberately not revocable: the recipient already holds what it bought, and
// taking it back is a refund decision with its own record.
func (q *Queries) RevokeGift(ctx context.Context, arg RevokeGiftParams) (Gift, error) {
	row := q.db.QueryRow(ctx, revokeGift, arg.RevokedBy, arg.RevokeReason, arg.GiftID)
	var i Gift
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.SenderUserID,
		&i.Kind,
		&i.PlanVersionID,
		&i.AddonVersionID,
		&i.CreditMinor,
		&i.Currency,
		&i.CodeHash,
		&i.CodeHint,
		&i.RecipientTelegramID,
		&i.RecipientUserID,
		&i.SenderMessage,
		&i.Status,
		&i.ClaimAttempts,
		&i.ClaimEntitlementID,
		&i.ClaimLedgerTransactionID,
		&i.ExpiresAt,
		&i.ClaimedAt,
		&i.RevokedAt,
		&i.RevokedBy,
		&i.RevokeReason,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const revokePersonalOffer = `-- name: RevokePersonalOffer :one
UPDATE personal_offers
SET status = 'revoked', resolved_at = now()
WHERE id = $1 AND status = 'active'
RETURNING id, user_id, promotion_id, plan_id, title_ru, title_en, terms_ru, terms_en, status, starts_at, expires_at, order_id, created_by, created_at, resolved_at
`

func (q *Queries) RevokePersonalOffer(ctx context.Context, offerID pgtype.UUID) (PersonalOffer, error) {
	row := q.db.QueryRow(ctx, revokePersonalOffer, offerID)
	var i PersonalOffer
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.PromotionID,
		&i.PlanID,
		&i.TitleRu,
		&i.TitleEn,
		&i.TermsRu,
		&i.TermsEn,
		&i.Status,
		&i.StartsAt,
		&i.ExpiresAt,
		&i.OrderID,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.ResolvedAt,
	)
	return i, err
}

const searchGifts = `-- name: SearchGifts :many
SELECT id, order_id, sender_user_id, kind, plan_version_id, addon_version_id, credit_minor, currency, code_hash, code_hint, recipient_telegram_id, recipient_user_id, sender_message, status, claim_attempts, claim_entitlement_id, claim_ledger_transaction_id, expires_at, claimed_at, revoked_at, revoked_by, revoke_reason, created_at, updated_at FROM gifts
WHERE (
    $1::timestamptz IS NULL
    OR (created_at, id) < ($1::timestamptz, $2::uuid)
  )
  AND ($3::text IS NULL OR status = $3)
  AND ($4::text IS NULL OR kind = $4)
  AND ($5::uuid IS NULL OR sender_user_id = $5)
ORDER BY created_at DESC, id DESC
LIMIT $6
`

type SearchGiftsParams struct {
	CursorCreatedAt pgtype.Timestamptz `json:"cursor_created_at"`
	CursorID        pgtype.UUID        `json:"cursor_id"`
	Status          pgtype.Text        `json:"status"`
	Kind            pgtype.Text        `json:"kind"`
	SenderUserID    pgtype.UUID        `json:"sender_user_id"`
	PageSize        int32              `json:"page_size"`
}

// The panel's gift register. Keyset pagination on (created_at, id).
func (q *Queries) SearchGifts(ctx context.Context, arg SearchGiftsParams) ([]Gift, error) {
	rows, err := q.db.Query(ctx, searchGifts,
		arg.CursorCreatedAt,
		arg.CursorID,
		arg.Status,
		arg.Kind,
		arg.SenderUserID,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Gift{}
	for rows.Next() {
		var i Gift
		if err := rows.Scan(
			&i.ID,
			&i.OrderID,
			&i.SenderUserID,
			&i.Kind,
			&i.PlanVersionID,
			&i.AddonVersionID,
			&i.CreditMinor,
			&i.Currency,
			&i.CodeHash,
			&i.CodeHint,
			&i.RecipientTelegramID,
			&i.RecipientUserID,
			&i.SenderMessage,
			&i.Status,
			&i.ClaimAttempts,
			&i.ClaimEntitlementID,
			&i.ClaimLedgerTransactionID,
			&i.ExpiresAt,
			&i.ClaimedAt,
			&i.RevokedAt,
			&i.RevokedBy,
			&i.RevokeReason,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchPersonalOffers = `-- name: SearchPersonalOffers :many
SELECT id, user_id, promotion_id, plan_id, title_ru, title_en, terms_ru, terms_en, status, starts_at, expires_at, order_id, created_by, created_at, resolved_at FROM personal_offers
WHERE (
    $1::timestamptz IS NULL
    OR (created_at, id) < ($1::timestamptz, $2::uuid)
  )
  AND ($3::text IS NULL OR status = $3)
  AND ($4::uuid IS NULL OR user_id = $4)
ORDER BY created_at DESC, id DESC
LIMIT $5
`

type SearchPersonalOffersParams struct {
	CursorCreatedAt pgtype.Timestamptz `json:"cursor_created_at"`
	CursorID        pgtype.UUID        `json:"cursor_id"`
	Status          pgtype.Text        `json:"status"`
	UserID          pgtype.UUID        `json:"user_id"`
	PageSize        int32              `json:"page_size"`
}

func (q *Queries) SearchPersonalOffers(ctx context.Context, arg SearchPersonalOffersParams) ([]PersonalOffer, error) {
	rows, err := q.db.Query(ctx, searchPersonalOffers,
		arg.CursorCreatedAt,
		arg.CursorID,
		arg.Status,
		arg.UserID,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PersonalOffer{}
	for rows.Next() {
		var i PersonalOffer
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.PromotionID,
			&i.PlanID,
			&i.TitleRu,
			&i.TitleEn,
			&i.TermsRu,
			&i.TermsEn,
			&i.Status,
			&i.StartsAt,
			&i.ExpiresAt,
			&i.OrderID,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.ResolvedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
