// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package dbgen

import (
	"net/netip"

	"github.com/jackc/pgx/v5/pgtype"
)

type Addon struct {
	ID         pgtype.UUID        `json:"id"`
	Code       string             `json:"code"`
	Kind       string             `json:"kind"`
	Visible    bool               `json:"visible"`
	SortOrder  int32              `json:"sort_order"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	ArchivedAt pgtype.Timestamptz `json:"archived_at"`
}

type AddonLocalization struct {
	AddonID     pgtype.UUID `json:"addon_id"`
	Locale      string      `json:"locale"`
	Name        string      `json:"name"`
	Description string      `json:"description"`
}

type AddonPrice struct {
	AddonVersionID pgtype.UUID `json:"addon_version_id"`
	Currency       string      `json:"currency"`
	AmountMinor    int64       `json:"amount_minor"`
}

type AddonVersion struct {
	ID                pgtype.UUID        `json:"id"`
	AddonID           pgtype.UUID        `json:"addon_id"`
	Version           int32              `json:"version"`
	TrafficBytes      pgtype.Int8        `json:"traffic_bytes"`
	DeviceSlots       pgtype.Int4        `json:"device_slots"`
	RemnawaveSquadIds []pgtype.UUID      `json:"remnawave_squad_ids"`
	MaxQuantity       int32              `json:"max_quantity"`
	Proration         string             `json:"proration"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	RetiredAt         pgtype.Timestamptz `json:"retired_at"`
}

type AdminOidcIdentity struct {
	ID          pgtype.UUID        `json:"id"`
	AdminUserID pgtype.UUID        `json:"admin_user_id"`
	ProviderID  pgtype.UUID        `json:"provider_id"`
	Subject     string             `json:"subject"`
	LinkedAt    pgtype.Timestamptz `json:"linked_at"`
	LastLoginAt pgtype.Timestamptz `json:"last_login_at"`
}

type AdminOidcProvider struct {
	ID                     pgtype.UUID        `json:"id"`
	Slug                   string             `json:"slug"`
	DisplayName            string             `json:"display_name"`
	Issuer                 string             `json:"issuer"`
	DiscoveryUrl           string             `json:"discovery_url"`
	ClientID               string             `json:"client_id"`
	ClientSecretCiphertext []byte             `json:"client_secret_ciphertext"`
	Scopes                 []string           `json:"scopes"`
	Enabled                bool               `json:"enabled"`
	RequireVerifiedEmail   bool               `json:"require_verified_email"`
	AllowAutoProvision     bool               `json:"allow_auto_provision"`
	AutoProvisionRole      pgtype.Text        `json:"auto_provision_role"`
	CreatedAt              pgtype.Timestamptz `json:"created_at"`
	UpdatedAt              pgtype.Timestamptz `json:"updated_at"`
}

type AdminPasswordReset struct {
	ID          pgtype.UUID        `json:"id"`
	AdminUserID pgtype.UUID        `json:"admin_user_id"`
	TokenHash   []byte             `json:"token_hash"`
	RequestedIp *netip.Addr        `json:"requested_ip"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	ExpiresAt   pgtype.Timestamptz `json:"expires_at"`
	UsedAt      pgtype.Timestamptz `json:"used_at"`
}

type AdminRecoveryCode struct {
	ID          pgtype.UUID        `json:"id"`
	AdminUserID pgtype.UUID        `json:"admin_user_id"`
	CodeHash    []byte             `json:"code_hash"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UsedAt      pgtype.Timestamptz `json:"used_at"`
}

type AdminSession struct {
	ID                pgtype.UUID        `json:"id"`
	AdminUserID       pgtype.UUID        `json:"admin_user_id"`
	TokenHash         []byte             `json:"token_hash"`
	CsrfSecret        []byte             `json:"csrf_secret"`
	PendingTotp       bool               `json:"pending_totp"`
	AuthMethods       []string           `json:"auth_methods"`
	Ip                *netip.Addr        `json:"ip"`
	UserAgent         pgtype.Text        `json:"user_agent"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	LastSeenAt        pgtype.Timestamptz `json:"last_seen_at"`
	RotatedAt         pgtype.Timestamptz `json:"rotated_at"`
	IdleExpiresAt     pgtype.Timestamptz `json:"idle_expires_at"`
	AbsoluteExpiresAt pgtype.Timestamptz `json:"absolute_expires_at"`
	RevokedAt         pgtype.Timestamptz `json:"revoked_at"`
	RevokedReason     pgtype.Text        `json:"revoked_reason"`
}

type AdminSetupToken struct {
	ID         pgtype.UUID        `json:"id"`
	TokenHash  []byte             `json:"token_hash"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	ExpiresAt  pgtype.Timestamptz `json:"expires_at"`
	ConsumedAt pgtype.Timestamptz `json:"consumed_at"`
	ConsumedBy pgtype.UUID        `json:"consumed_by"`
}

type AdminUser struct {
	ID                   pgtype.UUID        `json:"id"`
	Email                string             `json:"email"`
	EmailNormalized      string             `json:"email_normalized"`
	DisplayName          string             `json:"display_name"`
	PasswordHash         pgtype.Text        `json:"password_hash"`
	Status               string             `json:"status"`
	Locale               string             `json:"locale"`
	Timezone             string             `json:"timezone"`
	Preferences          []byte             `json:"preferences"`
	TotpSecretCiphertext []byte             `json:"totp_secret_ciphertext"`
	TotpConfirmedAt      pgtype.Timestamptz `json:"totp_confirmed_at"`
	FailedLoginCount     int32              `json:"failed_login_count"`
	LockedUntil          pgtype.Timestamptz `json:"locked_until"`
	PasswordChangedAt    pgtype.Timestamptz `json:"password_changed_at"`
	LastLoginAt          pgtype.Timestamptz `json:"last_login_at"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
	UpdatedAt            pgtype.Timestamptz `json:"updated_at"`
	DisabledAt           pgtype.Timestamptz `json:"disabled_at"`
}

type AdminUserRole struct {
	AdminUserID pgtype.UUID        `json:"admin_user_id"`
	Role        string             `json:"role"`
	GrantedAt   pgtype.Timestamptz `json:"granted_at"`
	GrantedBy   pgtype.UUID        `json:"granted_by"`
}

type AnomalyRule struct {
	Metric         string             `json:"metric"`
	Enabled        bool               `json:"enabled"`
	WindowSeconds  int64              `json:"window_seconds"`
	WarnThreshold  int64              `json:"warn_threshold"`
	AlertThreshold int64              `json:"alert_threshold"`
	MinimumSample  int32              `json:"minimum_sample"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
	UpdatedBy      pgtype.UUID        `json:"updated_by"`
}

type AnomalySignal struct {
	ID              pgtype.UUID        `json:"id"`
	Metric          string             `json:"metric"`
	Severity        string             `json:"severity"`
	SubjectType     string             `json:"subject_type"`
	SubjectID       string             `json:"subject_id"`
	Observed        int64              `json:"observed"`
	Threshold       int64              `json:"threshold"`
	SampleSize      int32              `json:"sample_size"`
	WindowStartedAt pgtype.Timestamptz `json:"window_started_at"`
	WindowEndedAt   pgtype.Timestamptz `json:"window_ended_at"`
	Evidence        []byte             `json:"evidence"`
	Status          string             `json:"status"`
	ReviewedBy      pgtype.UUID        `json:"reviewed_by"`
	ReviewReason    pgtype.Text        `json:"review_reason"`
	DetectedAt      pgtype.Timestamptz `json:"detected_at"`
	ReviewedAt      pgtype.Timestamptz `json:"reviewed_at"`
	DedupeKey       string             `json:"dedupe_key"`
}

type AuditEvent struct {
	ID         pgtype.UUID        `json:"id"`
	ActorType  string             `json:"actor_type"`
	ActorID    pgtype.Text        `json:"actor_id"`
	Action     string             `json:"action"`
	TargetType string             `json:"target_type"`
	TargetID   string             `json:"target_id"`
	Reason     pgtype.Text        `json:"reason"`
	RequestID  pgtype.Text        `json:"request_id"`
	Metadata   []byte             `json:"metadata"`
	OccurredAt pgtype.Timestamptz `json:"occurred_at"`
	Category   string             `json:"category"`
	Outcome    string             `json:"outcome"`
}

type AutoRenewSetting struct {
	UserID          pgtype.UUID        `json:"user_id"`
	Enabled         bool               `json:"enabled"`
	PlanVersionID   pgtype.UUID        `json:"plan_version_id"`
	Provider        pgtype.Text        `json:"provider"`
	Currency        pgtype.Text        `json:"currency"`
	CancelledAt     pgtype.Timestamptz `json:"cancelled_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
	SubscriptionID  pgtype.UUID        `json:"subscription_id"`
	PaymentMethodID pgtype.UUID        `json:"payment_method_id"`
	Funding         string             `json:"funding"`
	LeadTimeSeconds int64              `json:"lead_time_seconds"`
	ConsentAt       pgtype.Timestamptz `json:"consent_at"`
	State           string             `json:"state"`
	LastAttemptAt   pgtype.Timestamptz `json:"last_attempt_at"`
	LastFailureCode pgtype.Text        `json:"last_failure_code"`
}

type Backup struct {
	ID          pgtype.UUID        `json:"id"`
	Kind        string             `json:"kind"`
	Status      string             `json:"status"`
	FileName    string             `json:"file_name"`
	SizeBytes   int64              `json:"size_bytes"`
	Sha256      []byte             `json:"sha256"`
	Encrypted   bool               `json:"encrypted"`
	VerifiedAt  pgtype.Timestamptz `json:"verified_at"`
	ErrorCode   pgtype.Text        `json:"error_code"`
	RequestedBy pgtype.Text        `json:"requested_by"`
	StartedAt   pgtype.Timestamptz `json:"started_at"`
	CompletedAt pgtype.Timestamptz `json:"completed_at"`
	RetainUntil pgtype.Timestamptz `json:"retain_until"`
}

type BackupRestore struct {
	ID          pgtype.UUID        `json:"id"`
	BackupID    pgtype.UUID        `json:"backup_id"`
	Status      string             `json:"status"`
	OperatorID  string             `json:"operator_id"`
	Reason      string             `json:"reason"`
	ErrorCode   pgtype.Text        `json:"error_code"`
	RequestedAt pgtype.Timestamptz `json:"requested_at"`
	CompletedAt pgtype.Timestamptz `json:"completed_at"`
}

type BlocklistAllowlist struct {
	UserID    pgtype.UUID        `json:"user_id"`
	Reason    string             `json:"reason"`
	AddedBy   pgtype.UUID        `json:"added_by"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type BlocklistEntry struct {
	SourceID         pgtype.UUID        `json:"source_id"`
	ValueFingerprint []byte             `json:"value_fingerprint"`
	ReasonCode       pgtype.Text        `json:"reason_code"`
	ImportedAt       pgtype.Timestamptz `json:"imported_at"`
}

type BlocklistMatch struct {
	ID               pgtype.UUID        `json:"id"`
	UserID           pgtype.UUID        `json:"user_id"`
	SourceID         pgtype.UUID        `json:"source_id"`
	SubjectKind      string             `json:"subject_kind"`
	ValueFingerprint []byte             `json:"value_fingerprint"`
	Status           string             `json:"status"`
	DecisionReason   pgtype.Text        `json:"decision_reason"`
	DecidedBy        pgtype.UUID        `json:"decided_by"`
	DetectedAt       pgtype.Timestamptz `json:"detected_at"`
	DecidedAt        pgtype.Timestamptz `json:"decided_at"`
}

type BlocklistSource struct {
	ID                     pgtype.UUID        `json:"id"`
	Slug                   string             `json:"slug"`
	DisplayName            string             `json:"display_name"`
	SubjectKind            string             `json:"subject_kind"`
	Url                    string             `json:"url"`
	AuthHeaderCiphertext   []byte             `json:"auth_header_ciphertext"`
	Enabled                bool               `json:"enabled"`
	RefreshIntervalSeconds int64              `json:"refresh_interval_seconds"`
	EntryCount             int32              `json:"entry_count"`
	Status                 string             `json:"status"`
	LastErrorCode          pgtype.Text        `json:"last_error_code"`
	LastRefreshAt          pgtype.Timestamptz `json:"last_refresh_at"`
	NextRefreshAt          pgtype.Timestamptz `json:"next_refresh_at"`
	CreatedAt              pgtype.Timestamptz `json:"created_at"`
	UpdatedAt              pgtype.Timestamptz `json:"updated_at"`
	UpdatedBy              pgtype.UUID        `json:"updated_by"`
}

type BotCheckoutAddon struct {
	CheckoutID     pgtype.UUID `json:"checkout_id"`
	AddonVersionID pgtype.UUID `json:"addon_version_id"`
	Quantity       int32       `json:"quantity"`
}

type BotCheckoutSession struct {
	ID               pgtype.UUID        `json:"id"`
	UserID           pgtype.UUID        `json:"user_id"`
	PlanVersionID    pgtype.UUID        `json:"plan_version_id"`
	Operation        string             `json:"operation"`
	Currency         string             `json:"currency"`
	Provider         pgtype.Text        `json:"provider"`
	PromoCode        pgtype.Text        `json:"promo_code"`
	PromoRejection   pgtype.Text        `json:"promo_rejection"`
	ApplyWallet      bool               `json:"apply_wallet"`
	OrderID          pgtype.UUID        `json:"order_id"`
	IdempotencyKey   string             `json:"idempotency_key"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
	ExpiresAt        pgtype.Timestamptz `json:"expires_at"`
	SubscriptionID   pgtype.UUID        `json:"subscription_id"`
	SelectedSquadIds []pgtype.UUID      `json:"selected_squad_ids"`
}

type BotDeliveryState struct {
	UserID              pgtype.UUID        `json:"user_id"`
	Status              string             `json:"status"`
	LastErrorCode       pgtype.Text        `json:"last_error_code"`
	ConsecutiveFailures int32              `json:"consecutive_failures"`
	RetryAfter          pgtype.Timestamptz `json:"retry_after"`
	UpdatedAt           pgtype.Timestamptz `json:"updated_at"`
}

type BotPreference struct {
	UserID               pgtype.UUID        `json:"user_id"`
	Locale               string             `json:"locale"`
	ExpiryNotifications  bool               `json:"expiry_notifications"`
	TrafficNotifications bool               `json:"traffic_notifications"`
	UpdatedAt            pgtype.Timestamptz `json:"updated_at"`
	RenewalNotifications bool               `json:"renewal_notifications"`
	NewsNotifications    bool               `json:"news_notifications"`
	MarketingEnabled     bool               `json:"marketing_enabled"`
	QuietHoursStart      pgtype.Int2        `json:"quiet_hours_start"`
	QuietHoursEnd        pgtype.Int2        `json:"quiet_hours_end"`
}

type BotSession struct {
	TelegramID int64              `json:"telegram_id"`
	State      string             `json:"state"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
	ExpiresAt  pgtype.Timestamptz `json:"expires_at"`
	Context    []byte             `json:"context"`
}

type BulkOperation struct {
	ID             pgtype.UUID        `json:"id"`
	Kind           string             `json:"kind"`
	Status         string             `json:"status"`
	RequestedBy    pgtype.UUID        `json:"requested_by"`
	Reason         string             `json:"reason"`
	Parameters     []byte             `json:"parameters"`
	TotalCount     int32              `json:"total_count"`
	SucceededCount int32              `json:"succeeded_count"`
	FailedCount    int32              `json:"failed_count"`
	SkippedCount   int32              `json:"skipped_count"`
	IdempotencyKey string             `json:"idempotency_key"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
	CompletedAt    pgtype.Timestamptz `json:"completed_at"`
}

type BulkOperationItem struct {
	OperationID pgtype.UUID        `json:"operation_id"`
	Position    int32              `json:"position"`
	TargetType  string             `json:"target_type"`
	TargetID    pgtype.UUID        `json:"target_id"`
	Status      string             `json:"status"`
	ErrorCode   pgtype.Text        `json:"error_code"`
	ProcessedAt pgtype.Timestamptz `json:"processed_at"`
}

type Cart struct {
	ID               pgtype.UUID        `json:"id"`
	UserID           pgtype.UUID        `json:"user_id"`
	SubscriptionID   pgtype.UUID        `json:"subscription_id"`
	PlanVersionID    pgtype.UUID        `json:"plan_version_id"`
	Operation        string             `json:"operation"`
	Currency         string             `json:"currency"`
	PromoCode        pgtype.Text        `json:"promo_code"`
	SelectedSquadIds []pgtype.UUID      `json:"selected_squad_ids"`
	AutoPurchase     bool               `json:"auto_purchase"`
	Status           string             `json:"status"`
	IdempotencyKey   string             `json:"idempotency_key"`
	OrderID          pgtype.UUID        `json:"order_id"`
	LastFailure      pgtype.Text        `json:"last_failure"`
	AttemptCount     int32              `json:"attempt_count"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
	ExpiresAt        pgtype.Timestamptz `json:"expires_at"`
}

type CartAddon struct {
	CartID         pgtype.UUID `json:"cart_id"`
	AddonVersionID pgtype.UUID `json:"addon_version_id"`
	Quantity       int32       `json:"quantity"`
}

type CommerceSetting struct {
	Singleton                   bool               `json:"singleton"`
	TopupEnabled                bool               `json:"topup_enabled"`
	TopupCurrency               string             `json:"topup_currency"`
	TopupPresetsMinor           []int64            `json:"topup_presets_minor"`
	TopupMinimumMinor           int64              `json:"topup_minimum_minor"`
	TopupMaximumMinor           int64              `json:"topup_maximum_minor"`
	TopupWindowSeconds          int64              `json:"topup_window_seconds"`
	TopupWindowLimitMinor       int64              `json:"topup_window_limit_minor"`
	MultiSubscriptionEnabled    bool               `json:"multi_subscription_enabled"`
	MaxSubscriptionsPerCustomer int32              `json:"max_subscriptions_per_customer"`
	UpdatedAt                   pgtype.Timestamptz `json:"updated_at"`
	UpdatedBy                   pgtype.UUID        `json:"updated_by"`
}

type ConsentRecord struct {
	ID            pgtype.UUID        `json:"id"`
	UserID        pgtype.UUID        `json:"user_id"`
	Purpose       string             `json:"purpose"`
	Granted       bool               `json:"granted"`
	PolicyVersion string             `json:"policy_version"`
	Source        string             `json:"source"`
	OccurredAt    pgtype.Timestamptz `json:"occurred_at"`
	RequestID     pgtype.Text        `json:"request_id"`
}

type ContactChannel struct {
	ID                   pgtype.UUID        `json:"id"`
	UserID               pgtype.UUID        `json:"user_id"`
	Kind                 string             `json:"kind"`
	ValueCiphertext      []byte             `json:"value_ciphertext"`
	ValueFingerprint     []byte             `json:"value_fingerprint"`
	VerifiedAt           pgtype.Timestamptz `json:"verified_at"`
	TransactionalEnabled bool               `json:"transactional_enabled"`
	MarketingEnabled     bool               `json:"marketing_enabled"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
	RevokedAt            pgtype.Timestamptz `json:"revoked_at"`
}

type CustomerImport struct {
	ID            pgtype.UUID        `json:"id"`
	Source        string             `json:"source"`
	Status        string             `json:"status"`
	Cursor        pgtype.Text        `json:"cursor"`
	TotalCount    int32              `json:"total_count"`
	ValidCount    int32              `json:"valid_count"`
	ConflictCount int32              `json:"conflict_count"`
	InvalidCount  int32              `json:"invalid_count"`
	ErrorSummary  []byte             `json:"error_summary"`
	StartedAt     pgtype.Timestamptz `json:"started_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
	CompletedAt   pgtype.Timestamptz `json:"completed_at"`
}

type CustomerImportItem struct {
	ImportID         pgtype.UUID        `json:"import_id"`
	SourceID         string             `json:"source_id"`
	Status           string             `json:"status"`
	Fingerprint      []byte             `json:"fingerprint"`
	StagedData       []byte             `json:"staged_data"`
	ValidationErrors []byte             `json:"validation_errors"`
	UserID           pgtype.UUID        `json:"user_id"`
	AppliedAt        pgtype.Timestamptz `json:"applied_at"`
}

type CustomerLifecycleEvent struct {
	ID         pgtype.UUID        `json:"id"`
	UserID     pgtype.UUID        `json:"user_id"`
	Action     string             `json:"action"`
	Reason     string             `json:"reason"`
	ActorType  string             `json:"actor_type"`
	ActorID    pgtype.Text        `json:"actor_id"`
	RequestID  pgtype.Text        `json:"request_id"`
	OccurredAt pgtype.Timestamptz `json:"occurred_at"`
}

type DunningAttempt struct {
	ID              pgtype.UUID        `json:"id"`
	UserID          pgtype.UUID        `json:"user_id"`
	SubscriptionID  pgtype.UUID        `json:"subscription_id"`
	CycleKey        string             `json:"cycle_key"`
	Attempt         int32              `json:"attempt"`
	Funding         string             `json:"funding"`
	PaymentMethodID pgtype.UUID        `json:"payment_method_id"`
	OrderID         pgtype.UUID        `json:"order_id"`
	Outcome         string             `json:"outcome"`
	FailureCode     pgtype.Text        `json:"failure_code"`
	ScheduledFor    pgtype.Timestamptz `json:"scheduled_for"`
	OccurredAt      pgtype.Timestamptz `json:"occurred_at"`
	NotifiedAt      pgtype.Timestamptz `json:"notified_at"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
}

type Entitlement struct {
	ID                    pgtype.UUID        `json:"id"`
	UserID                pgtype.UUID        `json:"user_id"`
	OrderID               pgtype.UUID        `json:"order_id"`
	PlanVersionID         pgtype.UUID        `json:"plan_version_id"`
	Status                string             `json:"status"`
	StartsAt              pgtype.Timestamptz `json:"starts_at"`
	EndsAt                pgtype.Timestamptz `json:"ends_at"`
	TrafficAllowanceBytes pgtype.Int8        `json:"traffic_allowance_bytes"`
	DeviceLimit           pgtype.Int4        `json:"device_limit"`
	RemnawaveSquadIds     []pgtype.UUID      `json:"remnawave_squad_ids"`
	RemnawaveUserID       pgtype.Int8        `json:"remnawave_user_id"`
	ObservedState         []byte             `json:"observed_state"`
	ReconciledAt          pgtype.Timestamptz `json:"reconciled_at"`
	CreatedAt             pgtype.Timestamptz `json:"created_at"`
	UpdatedAt             pgtype.Timestamptz `json:"updated_at"`
	SubscriptionID        pgtype.UUID        `json:"subscription_id"`
}

type EntitlementAddon struct {
	ID                pgtype.UUID        `json:"id"`
	EntitlementID     pgtype.UUID        `json:"entitlement_id"`
	OrderID           pgtype.UUID        `json:"order_id"`
	AddonVersionID    pgtype.UUID        `json:"addon_version_id"`
	Quantity          int32              `json:"quantity"`
	TrafficBytes      pgtype.Int8        `json:"traffic_bytes"`
	DeviceSlots       pgtype.Int4        `json:"device_slots"`
	RemnawaveSquadIds []pgtype.UUID      `json:"remnawave_squad_ids"`
	AppliedAt         pgtype.Timestamptz `json:"applied_at"`
}

type EntitlementDrift struct {
	ID            pgtype.UUID        `json:"id"`
	EntitlementID pgtype.UUID        `json:"entitlement_id"`
	Kind          string             `json:"kind"`
	Expected      []byte             `json:"expected"`
	Observed      []byte             `json:"observed"`
	Status        string             `json:"status"`
	DetectedAt    pgtype.Timestamptz `json:"detected_at"`
	ResolvedAt    pgtype.Timestamptz `json:"resolved_at"`
}

type FulfillmentHistory struct {
	ID              pgtype.UUID        `json:"id"`
	OperationID     pgtype.UUID        `json:"operation_id"`
	Status          string             `json:"status"`
	CorrelationID   string             `json:"correlation_id"`
	RequestSummary  []byte             `json:"request_summary"`
	ResponseSummary []byte             `json:"response_summary"`
	ErrorCode       pgtype.Text        `json:"error_code"`
	OccurredAt      pgtype.Timestamptz `json:"occurred_at"`
}

type FulfillmentOperation struct {
	ID             pgtype.UUID        `json:"id"`
	EntitlementID  pgtype.UUID        `json:"entitlement_id"`
	Operation      string             `json:"operation"`
	Status         string             `json:"status"`
	IdempotencyKey string             `json:"idempotency_key"`
	CorrelationID  string             `json:"correlation_id"`
	DesiredState   []byte             `json:"desired_state"`
	AttemptCount   int32              `json:"attempt_count"`
	NextAttemptAt  pgtype.Timestamptz `json:"next_attempt_at"`
	LastErrorCode  pgtype.Text        `json:"last_error_code"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
	CompletedAt    pgtype.Timestamptz `json:"completed_at"`
}

type Gift struct {
	ID                       pgtype.UUID        `json:"id"`
	OrderID                  pgtype.UUID        `json:"order_id"`
	SenderUserID             pgtype.UUID        `json:"sender_user_id"`
	Kind                     string             `json:"kind"`
	PlanVersionID            pgtype.UUID        `json:"plan_version_id"`
	AddonVersionID           pgtype.UUID        `json:"addon_version_id"`
	CreditMinor              pgtype.Int8        `json:"credit_minor"`
	Currency                 string             `json:"currency"`
	CodeHash                 []byte             `json:"code_hash"`
	CodeHint                 string             `json:"code_hint"`
	RecipientTelegramID      pgtype.Int8        `json:"recipient_telegram_id"`
	RecipientUserID          pgtype.UUID        `json:"recipient_user_id"`
	SenderMessage            pgtype.Text        `json:"sender_message"`
	Status                   string             `json:"status"`
	ClaimAttempts            int32              `json:"claim_attempts"`
	ClaimEntitlementID       pgtype.UUID        `json:"claim_entitlement_id"`
	ClaimLedgerTransactionID pgtype.UUID        `json:"claim_ledger_transaction_id"`
	ExpiresAt                pgtype.Timestamptz `json:"expires_at"`
	ClaimedAt                pgtype.Timestamptz `json:"claimed_at"`
	RevokedAt                pgtype.Timestamptz `json:"revoked_at"`
	RevokedBy                pgtype.UUID        `json:"revoked_by"`
	RevokeReason             pgtype.Text        `json:"revoke_reason"`
	CreatedAt                pgtype.Timestamptz `json:"created_at"`
	UpdatedAt                pgtype.Timestamptz `json:"updated_at"`
}

type GoodsDelivery struct {
	OrderID                   pgtype.UUID        `json:"order_id"`
	ProviderSlug              string             `json:"provider_slug"`
	IdempotencyKey            string             `json:"idempotency_key"`
	ProviderReference         pgtype.Text        `json:"provider_reference"`
	Status                    string             `json:"status"`
	AttemptCount              int32              `json:"attempt_count"`
	NextAttemptAt             pgtype.Timestamptz `json:"next_attempt_at"`
	FailureClass              pgtype.Text        `json:"failure_class"`
	LastErrorCode             pgtype.Text        `json:"last_error_code"`
	RefundLedgerTransactionID pgtype.UUID        `json:"refund_ledger_transaction_id"`
	CreatedAt                 pgtype.Timestamptz `json:"created_at"`
	UpdatedAt                 pgtype.Timestamptz `json:"updated_at"`
	DeliveredAt               pgtype.Timestamptz `json:"delivered_at"`
}

type GoodsDeliveryAttempt struct {
	ID                pgtype.UUID        `json:"id"`
	OrderID           pgtype.UUID        `json:"order_id"`
	Attempt           int32              `json:"attempt"`
	Outcome           string             `json:"outcome"`
	FailureClass      pgtype.Text        `json:"failure_class"`
	ErrorCode         pgtype.Text        `json:"error_code"`
	ProviderReference pgtype.Text        `json:"provider_reference"`
	CorrelationID     string             `json:"correlation_id"`
	OccurredAt        pgtype.Timestamptz `json:"occurred_at"`
}

type GoodsOrder struct {
	OrderID           pgtype.UUID        `json:"order_id"`
	UserID            pgtype.UUID        `json:"user_id"`
	ProductID         pgtype.UUID        `json:"product_id"`
	Quantity          int32              `json:"quantity"`
	RecipientUsername string             `json:"recipient_username"`
	RecipientIsSelf   bool               `json:"recipient_is_self"`
	QuotedCostMinor   int64              `json:"quoted_cost_minor"`
	QuotedPriceMinor  int64              `json:"quoted_price_minor"`
	Currency          string             `json:"currency"`
	QuoteExpiresAt    pgtype.Timestamptz `json:"quote_expires_at"`
	Status            string             `json:"status"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
	// False when the provider publishes no cost for this product and the operator set the price directly. Margin is unknown, not zero.
	CostKnown bool `json:"cost_known"`
}

type GoodsPricing struct {
	ProductID        pgtype.UUID        `json:"product_id"`
	Currency         string             `json:"currency"`
	MarkupBps        int32              `json:"markup_bps"`
	Rounding         string             `json:"rounding"`
	FixedAmountMinor pgtype.Int8        `json:"fixed_amount_minor"`
	QuoteTtlSeconds  int32              `json:"quote_ttl_seconds"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
	UpdatedBy        pgtype.UUID        `json:"updated_by"`
}

type GoodsProduct struct {
	ID             pgtype.UUID        `json:"id"`
	Code           string             `json:"code"`
	ProviderSlug   string             `json:"provider_slug"`
	Kind           string             `json:"kind"`
	DurationMonths pgtype.Int2        `json:"duration_months"`
	StarQuantity   pgtype.Int4        `json:"star_quantity"`
	Visible        bool               `json:"visible"`
	SortOrder      int32              `json:"sort_order"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	ArchivedAt     pgtype.Timestamptz `json:"archived_at"`
}

type GoodsProductLocalization struct {
	ProductID   pgtype.UUID `json:"product_id"`
	Locale      string      `json:"locale"`
	Name        string      `json:"name"`
	Description string      `json:"description"`
}

type GoodsProvider struct {
	Slug                     string             `json:"slug"`
	Enabled                  bool               `json:"enabled"`
	CredentialsCiphertext    []byte             `json:"credentials_ciphertext"`
	BalanceMinor             pgtype.Int8        `json:"balance_minor"`
	BalanceCurrency          pgtype.Text        `json:"balance_currency"`
	LowBalanceThresholdMinor pgtype.Int8        `json:"low_balance_threshold_minor"`
	SpendLimitMinor          int64              `json:"spend_limit_minor"`
	SpendWindowSeconds       int64              `json:"spend_window_seconds"`
	Status                   string             `json:"status"`
	LastErrorCode            pgtype.Text        `json:"last_error_code"`
	LastCheckedAt            pgtype.Timestamptz `json:"last_checked_at"`
	CreatedAt                pgtype.Timestamptz `json:"created_at"`
	UpdatedAt                pgtype.Timestamptz `json:"updated_at"`
}

type Identity struct {
	ID              pgtype.UUID        `json:"id"`
	UserID          pgtype.UUID        `json:"user_id"`
	Provider        string             `json:"provider"`
	ProviderSubject string             `json:"provider_subject"`
	VerifiedAt      pgtype.Timestamptz `json:"verified_at"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	Status          string             `json:"status"`
	RevokedAt       pgtype.Timestamptz `json:"revoked_at"`
	Metadata        []byte             `json:"metadata"`
}

type LedgerEntry struct {
	ID            pgtype.UUID        `json:"id"`
	TransactionID pgtype.UUID        `json:"transaction_id"`
	AccountType   string             `json:"account_type"`
	UserID        pgtype.UUID        `json:"user_id"`
	Currency      string             `json:"currency"`
	AmountMinor   int64              `json:"amount_minor"`
	ExpiresAt     pgtype.Timestamptz `json:"expires_at"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}

type LedgerTransaction struct {
	ID             pgtype.UUID        `json:"id"`
	Type           string             `json:"type"`
	ReferenceType  string             `json:"reference_type"`
	ReferenceID    string             `json:"reference_id"`
	IdempotencyKey string             `json:"idempotency_key"`
	Reason         pgtype.Text        `json:"reason"`
	ActorID        pgtype.Text        `json:"actor_id"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

type MaintenanceEvent struct {
	ID         pgtype.UUID        `json:"id"`
	Action     string             `json:"action"`
	Source     string             `json:"source"`
	Reason     string             `json:"reason"`
	ActorType  string             `json:"actor_type"`
	ActorID    pgtype.Text        `json:"actor_id"`
	OccurredAt pgtype.Timestamptz `json:"occurred_at"`
}

type MaintenanceState struct {
	Singleton        bool               `json:"singleton"`
	Active           bool               `json:"active"`
	Source           string             `json:"source"`
	Reason           string             `json:"reason"`
	NoticeRu         string             `json:"notice_ru"`
	NoticeEn         string             `json:"notice_en"`
	ExpectedReturnAt pgtype.Timestamptz `json:"expected_return_at"`
	ActivatedAt      pgtype.Timestamptz `json:"activated_at"`
	ClearedAt        pgtype.Timestamptz `json:"cleared_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}

type ManualPaymentApproval struct {
	ID              pgtype.UUID        `json:"id"`
	PaymentIntentID pgtype.UUID        `json:"payment_intent_id"`
	Decision        string             `json:"decision"`
	OperatorID      string             `json:"operator_id"`
	Reason          string             `json:"reason"`
	IdempotencyKey  string             `json:"idempotency_key"`
	RequestID       pgtype.Text        `json:"request_id"`
	OccurredAt      pgtype.Timestamptz `json:"occurred_at"`
}

type NewsPost struct {
	ID          pgtype.UUID        `json:"id"`
	Slug        string             `json:"slug"`
	Category    string             `json:"category"`
	Class       string             `json:"class"`
	PublishedAt pgtype.Timestamptz `json:"published_at"`
	ExpiresAt   pgtype.Timestamptz `json:"expires_at"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type NewsPostLocalization struct {
	PostID pgtype.UUID `json:"post_id"`
	Locale string      `json:"locale"`
	Title  string      `json:"title"`
	Body   string      `json:"body"`
}

type NewsRead struct {
	UserID pgtype.UUID        `json:"user_id"`
	PostID pgtype.UUID        `json:"post_id"`
	ReadAt pgtype.Timestamptz `json:"read_at"`
}

type NotificationDelivery struct {
	ID             pgtype.UUID        `json:"id"`
	UserID         pgtype.UUID        `json:"user_id"`
	Kind           string             `json:"kind"`
	DedupeKey      string             `json:"dedupe_key"`
	Status         string             `json:"status"`
	ScheduledAt    pgtype.Timestamptz `json:"scheduled_at"`
	SentAt         pgtype.Timestamptz `json:"sent_at"`
	FailureCount   int32              `json:"failure_count"`
	Class          string             `json:"class"`
	ErrorCode      pgtype.Text        `json:"error_code"`
	DeferredUntil  pgtype.Timestamptz `json:"deferred_until"`
	SubscriptionID pgtype.UUID        `json:"subscription_id"`
}

type OperatorNotification struct {
	ID        pgtype.UUID        `json:"id"`
	Kind      string             `json:"kind"`
	DedupeKey string             `json:"dedupe_key"`
	Status    string             `json:"status"`
	Payload   []byte             `json:"payload"`
	ErrorCode pgtype.Text        `json:"error_code"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	SentAt    pgtype.Timestamptz `json:"sent_at"`
}

type OperatorTopic struct {
	Kind          string             `json:"kind"`
	ChatID        int64              `json:"chat_id"`
	TopicID       pgtype.Int8        `json:"topic_id"`
	Status        string             `json:"status"`
	LastErrorCode pgtype.Text        `json:"last_error_code"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

type Order struct {
	ID               pgtype.UUID        `json:"id"`
	UserID           pgtype.UUID        `json:"user_id"`
	State            string             `json:"state"`
	Operation        string             `json:"operation"`
	Currency         string             `json:"currency"`
	SubtotalMinor    int64              `json:"subtotal_minor"`
	DiscountMinor    int64              `json:"discount_minor"`
	WalletMinor      int64              `json:"wallet_minor"`
	ExternalMinor    int64              `json:"external_minor"`
	PaidMinor        int64              `json:"paid_minor"`
	RefundedMinor    int64              `json:"refunded_minor"`
	IdempotencyKey   string             `json:"idempotency_key"`
	ExpiresAt        pgtype.Timestamptz `json:"expires_at"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
	SubscriptionID   pgtype.UUID        `json:"subscription_id"`
	SelectedSquadIds []pgtype.UUID      `json:"selected_squad_ids"`
}

type OrderAddonLine struct {
	ID              pgtype.UUID `json:"id"`
	OrderID         pgtype.UUID `json:"order_id"`
	AddonID         pgtype.UUID `json:"addon_id"`
	AddonVersionID  pgtype.UUID `json:"addon_version_id"`
	Quantity        int32       `json:"quantity"`
	UnitAmountMinor int64       `json:"unit_amount_minor"`
	ChargedMinor    int64       `json:"charged_minor"`
	Proration       string      `json:"proration"`
	Snapshot        []byte      `json:"snapshot"`
}

type OrderLine struct {
	ID              pgtype.UUID `json:"id"`
	OrderID         pgtype.UUID `json:"order_id"`
	PlanID          pgtype.UUID `json:"plan_id"`
	PlanVersionID   pgtype.UUID `json:"plan_version_id"`
	Quantity        int32       `json:"quantity"`
	UnitAmountMinor int64       `json:"unit_amount_minor"`
	Snapshot        []byte      `json:"snapshot"`
}

type OrderMutation struct {
	ID             pgtype.UUID        `json:"id"`
	OrderID        pgtype.UUID        `json:"order_id"`
	Action         string             `json:"action"`
	IdempotencyKey string             `json:"idempotency_key"`
	Reason         pgtype.Text        `json:"reason"`
	OccurredAt     pgtype.Timestamptz `json:"occurred_at"`
}

type OutboxEvent struct {
	ID          pgtype.UUID        `json:"id"`
	Topic       string             `json:"topic"`
	Payload     []byte             `json:"payload"`
	OccurredAt  pgtype.Timestamptz `json:"occurred_at"`
	PublishedAt pgtype.Timestamptz `json:"published_at"`
}

type PaymentEvent struct {
	ID              pgtype.UUID        `json:"id"`
	PaymentIntentID pgtype.UUID        `json:"payment_intent_id"`
	Type            string             `json:"type"`
	PreviousStatus  pgtype.Text        `json:"previous_status"`
	Status          pgtype.Text        `json:"status"`
	AmountMinor     pgtype.Int8        `json:"amount_minor"`
	Currency        pgtype.Text        `json:"currency"`
	ProviderEventID pgtype.Text        `json:"provider_event_id"`
	Details         []byte             `json:"details"`
	OccurredAt      pgtype.Timestamptz `json:"occurred_at"`
}

type PaymentIntent struct {
	ID                pgtype.UUID        `json:"id"`
	OrderID           pgtype.UUID        `json:"order_id"`
	Provider          string             `json:"provider"`
	Status            string             `json:"status"`
	AmountMinor       int64              `json:"amount_minor"`
	Currency          string             `json:"currency"`
	ProviderReference pgtype.Text        `json:"provider_reference"`
	CheckoutUrl       pgtype.Text        `json:"checkout_url"`
	IdempotencyKey    string             `json:"idempotency_key"`
	Capabilities      []byte             `json:"capabilities"`
	ReceiptMetadata   []byte             `json:"receipt_metadata"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
}

type PaymentMethod struct {
	ID            pgtype.UUID        `json:"id"`
	UserID        pgtype.UUID        `json:"user_id"`
	Provider      string             `json:"provider"`
	MerchantID    string             `json:"merchant_id"`
	ProviderToken string             `json:"provider_token"`
	DisplayLabel  string             `json:"display_label"`
	Status        string             `json:"status"`
	IsDefault     bool               `json:"is_default"`
	ConsentAt     pgtype.Timestamptz `json:"consent_at"`
	LastUsedAt    pgtype.Timestamptz `json:"last_used_at"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
	RevokedAt     pgtype.Timestamptz `json:"revoked_at"`
}

type PaymentProviderSetting struct {
	Provider                string             `json:"provider"`
	MerchantID              string             `json:"merchant_id"`
	Enabled                 bool               `json:"enabled"`
	DisplayOrder            int32              `json:"display_order"`
	CredentialsCiphertext   []byte             `json:"credentials_ciphertext"`
	WebhookSecretCiphertext []byte             `json:"webhook_secret_ciphertext"`
	RecurringEnabled        bool               `json:"recurring_enabled"`
	RecurringTestStatus     string             `json:"recurring_test_status"`
	RecurringTestedAt       pgtype.Timestamptz `json:"recurring_tested_at"`
	ConnectionStatus        string             `json:"connection_status"`
	ConnectionCheckedAt     pgtype.Timestamptz `json:"connection_checked_at"`
	ConnectionErrorCode     pgtype.Text        `json:"connection_error_code"`
	WebhookStatus           string             `json:"webhook_status"`
	WebhookLastEventAt      pgtype.Timestamptz `json:"webhook_last_event_at"`
	WebhookLastErrorCode    pgtype.Text        `json:"webhook_last_error_code"`
	CreatedAt               pgtype.Timestamptz `json:"created_at"`
	UpdatedAt               pgtype.Timestamptz `json:"updated_at"`
	UpdatedBy               pgtype.UUID        `json:"updated_by"`
}

type PersonalOffer struct {
	ID          pgtype.UUID        `json:"id"`
	UserID      pgtype.UUID        `json:"user_id"`
	PromotionID pgtype.UUID        `json:"promotion_id"`
	PlanID      pgtype.UUID        `json:"plan_id"`
	TitleRu     string             `json:"title_ru"`
	TitleEn     string             `json:"title_en"`
	TermsRu     string             `json:"terms_ru"`
	TermsEn     string             `json:"terms_en"`
	Status      string             `json:"status"`
	StartsAt    pgtype.Timestamptz `json:"starts_at"`
	ExpiresAt   pgtype.Timestamptz `json:"expires_at"`
	OrderID     pgtype.UUID        `json:"order_id"`
	CreatedBy   pgtype.UUID        `json:"created_by"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	ResolvedAt  pgtype.Timestamptz `json:"resolved_at"`
}

type Plan struct {
	ID                       pgtype.UUID        `json:"id"`
	Code                     string             `json:"code"`
	Kind                     string             `json:"kind"`
	Visible                  bool               `json:"visible"`
	SortOrder                int32              `json:"sort_order"`
	CreatedAt                pgtype.Timestamptz `json:"created_at"`
	ArchivedAt               pgtype.Timestamptz `json:"archived_at"`
	MaxConcurrentPerCustomer pgtype.Int4        `json:"max_concurrent_per_customer"`
}

type PlanLocalization struct {
	PlanID      pgtype.UUID `json:"plan_id"`
	Locale      string      `json:"locale"`
	Name        string      `json:"name"`
	Description string      `json:"description"`
}

type PlanPrice struct {
	PlanVersionID pgtype.UUID `json:"plan_version_id"`
	Currency      string      `json:"currency"`
	AmountMinor   int64       `json:"amount_minor"`
}

type PlanVersion struct {
	ID                    pgtype.UUID        `json:"id"`
	PlanID                pgtype.UUID        `json:"plan_id"`
	Version               int32              `json:"version"`
	BillingPeriod         string             `json:"billing_period"`
	DurationSeconds       int64              `json:"duration_seconds"`
	TrafficAllowanceBytes pgtype.Int8        `json:"traffic_allowance_bytes"`
	DeviceLimit           pgtype.Int4        `json:"device_limit"`
	RemnawaveSquadIds     []pgtype.UUID      `json:"remnawave_squad_ids"`
	UpgradePolicy         string             `json:"upgrade_policy"`
	DowngradePolicy       string             `json:"downgrade_policy"`
	CancellationPolicy    string             `json:"cancellation_policy"`
	RecurringCapable      bool               `json:"recurring_capable"`
	CreatedAt             pgtype.Timestamptz `json:"created_at"`
	RetiredAt             pgtype.Timestamptz `json:"retired_at"`
	GracePeriodSeconds    int64              `json:"grace_period_seconds"`
	TrialEligibility      string             `json:"trial_eligibility"`
	SquadSelection        string             `json:"squad_selection"`
	MinSelectableSquads   int32              `json:"min_selectable_squads"`
	MaxSelectableSquads   pgtype.Int4        `json:"max_selectable_squads"`
}

type PlanVersionAddon struct {
	PlanVersionID pgtype.UUID `json:"plan_version_id"`
	AddonID       pgtype.UUID `json:"addon_id"`
}

type PlanVersionSquad struct {
	PlanVersionID pgtype.UUID `json:"plan_version_id"`
	SquadID       pgtype.UUID `json:"squad_id"`
	LabelRu       string      `json:"label_ru"`
	LabelEn       string      `json:"label_en"`
	SortOrder     int32       `json:"sort_order"`
}

type PromoCode struct {
	ID              pgtype.UUID        `json:"id"`
	PromotionID     pgtype.UUID        `json:"promotion_id"`
	NormalizedCode  string             `json:"normalized_code"`
	RedemptionLimit pgtype.Int4        `json:"redemption_limit"`
	Active          bool               `json:"active"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
}

type PromoRedemption struct {
	ID            pgtype.UUID        `json:"id"`
	PromoCodeID   pgtype.UUID        `json:"promo_code_id"`
	PromotionID   pgtype.UUID        `json:"promotion_id"`
	UserID        pgtype.UUID        `json:"user_id"`
	OrderID       pgtype.UUID        `json:"order_id"`
	DiscountMinor int64              `json:"discount_minor"`
	RedeemedAt    pgtype.Timestamptz `json:"redeemed_at"`
}

type Promotion struct {
	ID               pgtype.UUID        `json:"id"`
	Code             string             `json:"code"`
	Kind             string             `json:"kind"`
	Value            int64              `json:"value"`
	Currency         pgtype.Text        `json:"currency"`
	StartsAt         pgtype.Timestamptz `json:"starts_at"`
	EndsAt           pgtype.Timestamptz `json:"ends_at"`
	RedemptionLimit  pgtype.Int4        `json:"redemption_limit"`
	PerCustomerLimit int32              `json:"per_customer_limit"`
	Eligibility      []byte             `json:"eligibility"`
	Active           bool               `json:"active"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	Stackable        bool               `json:"stackable"`
	Precedence       int32              `json:"precedence"`
}

type PromotionPlan struct {
	PromotionID pgtype.UUID `json:"promotion_id"`
	PlanID      pgtype.UUID `json:"plan_id"`
}

type ProviderWebhookEvent struct {
	ID              pgtype.UUID        `json:"id"`
	Provider        string             `json:"provider"`
	ProviderEventID string             `json:"provider_event_id"`
	SignatureValid  bool               `json:"signature_valid"`
	BodySha256      []byte             `json:"body_sha256"`
	RawBody         []byte             `json:"raw_body"`
	Headers         []byte             `json:"headers"`
	Status          string             `json:"status"`
	ErrorCode       pgtype.Text        `json:"error_code"`
	ReceivedAt      pgtype.Timestamptz `json:"received_at"`
	ProcessedAt     pgtype.Timestamptz `json:"processed_at"`
	RetainUntil     pgtype.Timestamptz `json:"retain_until"`
}

type ReferralAttribution struct {
	ReferredUserID    pgtype.UUID        `json:"referred_user_id"`
	ReferrerUserID    pgtype.UUID        `json:"referrer_user_id"`
	Code              string             `json:"code"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	QualifiedAt       pgtype.Timestamptz `json:"qualified_at"`
	QualifyingOrderID pgtype.UUID        `json:"qualifying_order_id"`
	RejectedReason    pgtype.Text        `json:"rejected_reason"`
}

type ReferralCode struct {
	UserID    pgtype.UUID        `json:"user_id"`
	Code      string             `json:"code"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type ReferralProgram struct {
	Singleton               bool               `json:"singleton"`
	Enabled                 bool               `json:"enabled"`
	Currency                string             `json:"currency"`
	InviterRewardMinor      int64              `json:"inviter_reward_minor"`
	InviteeRewardMinor      int64              `json:"invitee_reward_minor"`
	Qualification           string             `json:"qualification"`
	InviterRewardCap        pgtype.Int4        `json:"inviter_reward_cap"`
	AttributionValidityDays int32              `json:"attribution_validity_days"`
	RewardExpiryDays        pgtype.Int4        `json:"reward_expiry_days"`
	TermsUrl                pgtype.Text        `json:"terms_url"`
	UpdatedAt               pgtype.Timestamptz `json:"updated_at"`
}

type ReferralReward struct {
	ID                  pgtype.UUID        `json:"id"`
	ReferredUserID      pgtype.UUID        `json:"referred_user_id"`
	BeneficiaryUserID   pgtype.UUID        `json:"beneficiary_user_id"`
	Role                string             `json:"role"`
	OrderID             pgtype.UUID        `json:"order_id"`
	AmountMinor         int64              `json:"amount_minor"`
	Currency            string             `json:"currency"`
	LedgerTransactionID pgtype.UUID        `json:"ledger_transaction_id"`
	GrantedAt           pgtype.Timestamptz `json:"granted_at"`
}

type Refund struct {
	ID                pgtype.UUID        `json:"id"`
	PaymentIntentID   pgtype.UUID        `json:"payment_intent_id"`
	Status            string             `json:"status"`
	AmountMinor       int64              `json:"amount_minor"`
	Currency          string             `json:"currency"`
	ProviderReference pgtype.Text        `json:"provider_reference"`
	Reason            string             `json:"reason"`
	IdempotencyKey    string             `json:"idempotency_key"`
	ReceiptMetadata   []byte             `json:"receipt_metadata"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
}

type RemnawaveUser struct {
	UserID        pgtype.UUID        `json:"user_id"`
	RemnawaveID   int64              `json:"remnawave_id"`
	TelegramID    pgtype.Int8        `json:"telegram_id"`
	ObservedState []byte             `json:"observed_state"`
	ReconciledAt  pgtype.Timestamptz `json:"reconciled_at"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}

type Subscription struct {
	ID                pgtype.UUID        `json:"id"`
	UserID            pgtype.UUID        `json:"user_id"`
	Slot              int32              `json:"slot"`
	Label             string             `json:"label"`
	Status            string             `json:"status"`
	RemnawaveUserID   pgtype.Int8        `json:"remnawave_user_id"`
	RemnawaveUsername pgtype.Text        `json:"remnawave_username"`
	ObservedState     []byte             `json:"observed_state"`
	ReconciledAt      pgtype.Timestamptz `json:"reconciled_at"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
	ClosedAt          pgtype.Timestamptz `json:"closed_at"`
}

type SupportAttachment struct {
	ID             pgtype.UUID        `json:"id"`
	MessageID      int64              `json:"message_id"`
	Kind           string             `json:"kind"`
	TelegramFileID string             `json:"telegram_file_id"`
	FileName       pgtype.Text        `json:"file_name"`
	MimeType       pgtype.Text        `json:"mime_type"`
	SizeBytes      int64              `json:"size_bytes"`
	RetainUntil    pgtype.Timestamptz `json:"retain_until"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

type SupportMessage struct {
	ID                int64              `json:"id"`
	TicketID          pgtype.UUID        `json:"ticket_id"`
	Sender            string             `json:"sender"`
	Body              string             `json:"body"`
	TelegramMessageID pgtype.Int8        `json:"telegram_message_id"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	DedupeKey         pgtype.Text        `json:"dedupe_key"`
	DeliveredAt       pgtype.Timestamptz `json:"delivered_at"`
	ReadAt            pgtype.Timestamptz `json:"read_at"`
}

type SupportTicket struct {
	ID                  pgtype.UUID        `json:"id"`
	UserID              pgtype.UUID        `json:"user_id"`
	Status              string             `json:"status"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	UpdatedAt           pgtype.Timestamptz `json:"updated_at"`
	Subject             string             `json:"subject"`
	Priority            string             `json:"priority"`
	LastMessageAt       pgtype.Timestamptz `json:"last_message_at"`
	CustomerUnreadCount int32              `json:"customer_unread_count"`
	ClosedAt            pgtype.Timestamptz `json:"closed_at"`
}

type TelemetryEvent struct {
	ID             int64              `json:"id"`
	InstallationID pgtype.UUID        `json:"installation_id"`
	Name           string             `json:"name"`
	Version        string             `json:"version"`
	Service        string             `json:"service"`
	Os             string             `json:"os"`
	Architecture   string             `json:"architecture"`
	Features       []byte             `json:"features"`
	Counters       []byte             `json:"counters"`
	OccurredAt     pgtype.Timestamptz `json:"occurred_at"`
	ReceivedAt     pgtype.Timestamptz `json:"received_at"`
}

type TelemetryInstallation struct {
	Singleton      bool               `json:"singleton"`
	InstallationID pgtype.UUID        `json:"installation_id"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

type TrialClaim struct {
	UserID    pgtype.UUID        `json:"user_id"`
	PlanID    pgtype.UUID        `json:"plan_id"`
	OrderID   pgtype.UUID        `json:"order_id"`
	ClaimedAt pgtype.Timestamptz `json:"claimed_at"`
}

type User struct {
	ID             pgtype.UUID        `json:"id"`
	Status         string             `json:"status"`
	Locale         string             `json:"locale"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
	Timezone       string             `json:"timezone"`
	SuspendedAt    pgtype.Timestamptz `json:"suspended_at"`
	DeletedAt      pgtype.Timestamptz `json:"deleted_at"`
	AnonymizedAt   pgtype.Timestamptz `json:"anonymized_at"`
	RetentionUntil pgtype.Timestamptz `json:"retention_until"`
}

type WalletTopup struct {
	OrderID             pgtype.UUID        `json:"order_id"`
	UserID              pgtype.UUID        `json:"user_id"`
	Currency            string             `json:"currency"`
	RequestedMinor      int64              `json:"requested_minor"`
	CreditedMinor       int64              `json:"credited_minor"`
	LedgerTransactionID pgtype.UUID        `json:"ledger_transaction_id"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	CreditedAt          pgtype.Timestamptz `json:"credited_at"`
}
