// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package dbgen

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Identity struct {
	ID              pgtype.UUID        `json:"id"`
	UserID          pgtype.UUID        `json:"user_id"`
	Provider        string             `json:"provider"`
	ProviderSubject string             `json:"provider_subject"`
	VerifiedAt      pgtype.Timestamptz `json:"verified_at"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
}

type OutboxEvent struct {
	ID          pgtype.UUID        `json:"id"`
	Topic       string             `json:"topic"`
	Payload     []byte             `json:"payload"`
	OccurredAt  pgtype.Timestamptz `json:"occurred_at"`
	PublishedAt pgtype.Timestamptz `json:"published_at"`
}

type RemnawaveUser struct {
	UserID        pgtype.UUID        `json:"user_id"`
	RemnawaveID   pgtype.UUID        `json:"remnawave_id"`
	TelegramID    pgtype.Int8        `json:"telegram_id"`
	ObservedState []byte             `json:"observed_state"`
	ReconciledAt  pgtype.Timestamptz `json:"reconciled_at"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}

type TelemetryEvent struct {
	ID             int64              `json:"id"`
	InstallationID pgtype.UUID        `json:"installation_id"`
	Name           string             `json:"name"`
	Version        string             `json:"version"`
	Service        string             `json:"service"`
	Os             string             `json:"os"`
	Architecture   string             `json:"architecture"`
	Features       []byte             `json:"features"`
	Counters       []byte             `json:"counters"`
	OccurredAt     pgtype.Timestamptz `json:"occurred_at"`
	ReceivedAt     pgtype.Timestamptz `json:"received_at"`
}

type TelemetryInstallation struct {
	Singleton      bool               `json:"singleton"`
	InstallationID pgtype.UUID        `json:"installation_id"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

type User struct {
	ID        pgtype.UUID        `json:"id"`
	Status    string             `json:"status"`
	Locale    string             `json:"locale"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}
