// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package dbgen

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type AuditEvent struct {
	ID         pgtype.UUID        `json:"id"`
	ActorType  string             `json:"actor_type"`
	ActorID    pgtype.Text        `json:"actor_id"`
	Action     string             `json:"action"`
	TargetType string             `json:"target_type"`
	TargetID   string             `json:"target_id"`
	Reason     pgtype.Text        `json:"reason"`
	RequestID  pgtype.Text        `json:"request_id"`
	Metadata   []byte             `json:"metadata"`
	OccurredAt pgtype.Timestamptz `json:"occurred_at"`
}

type AutoRenewSetting struct {
	UserID        pgtype.UUID        `json:"user_id"`
	Enabled       bool               `json:"enabled"`
	PlanVersionID pgtype.UUID        `json:"plan_version_id"`
	Provider      pgtype.Text        `json:"provider"`
	Currency      pgtype.Text        `json:"currency"`
	CancelledAt   pgtype.Timestamptz `json:"cancelled_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

type BotCheckoutSession struct {
	ID             pgtype.UUID        `json:"id"`
	UserID         pgtype.UUID        `json:"user_id"`
	PlanVersionID  pgtype.UUID        `json:"plan_version_id"`
	Operation      string             `json:"operation"`
	Currency       string             `json:"currency"`
	Provider       pgtype.Text        `json:"provider"`
	PromoCode      pgtype.Text        `json:"promo_code"`
	PromoRejection pgtype.Text        `json:"promo_rejection"`
	ApplyWallet    bool               `json:"apply_wallet"`
	OrderID        pgtype.UUID        `json:"order_id"`
	IdempotencyKey string             `json:"idempotency_key"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
	ExpiresAt      pgtype.Timestamptz `json:"expires_at"`
}

type BotDeliveryState struct {
	UserID              pgtype.UUID        `json:"user_id"`
	Status              string             `json:"status"`
	LastErrorCode       pgtype.Text        `json:"last_error_code"`
	ConsecutiveFailures int32              `json:"consecutive_failures"`
	RetryAfter          pgtype.Timestamptz `json:"retry_after"`
	UpdatedAt           pgtype.Timestamptz `json:"updated_at"`
}

type BotPreference struct {
	UserID               pgtype.UUID        `json:"user_id"`
	Locale               string             `json:"locale"`
	ExpiryNotifications  bool               `json:"expiry_notifications"`
	TrafficNotifications bool               `json:"traffic_notifications"`
	UpdatedAt            pgtype.Timestamptz `json:"updated_at"`
	RenewalNotifications bool               `json:"renewal_notifications"`
	NewsNotifications    bool               `json:"news_notifications"`
	MarketingEnabled     bool               `json:"marketing_enabled"`
	QuietHoursStart      pgtype.Int2        `json:"quiet_hours_start"`
	QuietHoursEnd        pgtype.Int2        `json:"quiet_hours_end"`
}

type BotSession struct {
	TelegramID int64              `json:"telegram_id"`
	State      string             `json:"state"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
	ExpiresAt  pgtype.Timestamptz `json:"expires_at"`
	Context    []byte             `json:"context"`
}

type ConsentRecord struct {
	ID            pgtype.UUID        `json:"id"`
	UserID        pgtype.UUID        `json:"user_id"`
	Purpose       string             `json:"purpose"`
	Granted       bool               `json:"granted"`
	PolicyVersion string             `json:"policy_version"`
	Source        string             `json:"source"`
	OccurredAt    pgtype.Timestamptz `json:"occurred_at"`
	RequestID     pgtype.Text        `json:"request_id"`
}

type ContactChannel struct {
	ID                   pgtype.UUID        `json:"id"`
	UserID               pgtype.UUID        `json:"user_id"`
	Kind                 string             `json:"kind"`
	ValueCiphertext      []byte             `json:"value_ciphertext"`
	ValueFingerprint     []byte             `json:"value_fingerprint"`
	VerifiedAt           pgtype.Timestamptz `json:"verified_at"`
	TransactionalEnabled bool               `json:"transactional_enabled"`
	MarketingEnabled     bool               `json:"marketing_enabled"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
	RevokedAt            pgtype.Timestamptz `json:"revoked_at"`
}

type CustomerImport struct {
	ID            pgtype.UUID        `json:"id"`
	Source        string             `json:"source"`
	Status        string             `json:"status"`
	Cursor        pgtype.Text        `json:"cursor"`
	TotalCount    int32              `json:"total_count"`
	ValidCount    int32              `json:"valid_count"`
	ConflictCount int32              `json:"conflict_count"`
	InvalidCount  int32              `json:"invalid_count"`
	ErrorSummary  []byte             `json:"error_summary"`
	StartedAt     pgtype.Timestamptz `json:"started_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
	CompletedAt   pgtype.Timestamptz `json:"completed_at"`
}

type CustomerImportItem struct {
	ImportID         pgtype.UUID        `json:"import_id"`
	SourceID         string             `json:"source_id"`
	Status           string             `json:"status"`
	Fingerprint      []byte             `json:"fingerprint"`
	StagedData       []byte             `json:"staged_data"`
	ValidationErrors []byte             `json:"validation_errors"`
	UserID           pgtype.UUID        `json:"user_id"`
	AppliedAt        pgtype.Timestamptz `json:"applied_at"`
}

type CustomerLifecycleEvent struct {
	ID         pgtype.UUID        `json:"id"`
	UserID     pgtype.UUID        `json:"user_id"`
	Action     string             `json:"action"`
	Reason     string             `json:"reason"`
	ActorType  string             `json:"actor_type"`
	ActorID    pgtype.Text        `json:"actor_id"`
	RequestID  pgtype.Text        `json:"request_id"`
	OccurredAt pgtype.Timestamptz `json:"occurred_at"`
}

type Entitlement struct {
	ID                    pgtype.UUID        `json:"id"`
	UserID                pgtype.UUID        `json:"user_id"`
	OrderID               pgtype.UUID        `json:"order_id"`
	PlanVersionID         pgtype.UUID        `json:"plan_version_id"`
	Status                string             `json:"status"`
	StartsAt              pgtype.Timestamptz `json:"starts_at"`
	EndsAt                pgtype.Timestamptz `json:"ends_at"`
	TrafficAllowanceBytes pgtype.Int8        `json:"traffic_allowance_bytes"`
	DeviceLimit           pgtype.Int4        `json:"device_limit"`
	RemnawaveSquadIds     []pgtype.UUID      `json:"remnawave_squad_ids"`
	RemnawaveUserID       pgtype.Int8        `json:"remnawave_user_id"`
	ObservedState         []byte             `json:"observed_state"`
	ReconciledAt          pgtype.Timestamptz `json:"reconciled_at"`
	CreatedAt             pgtype.Timestamptz `json:"created_at"`
	UpdatedAt             pgtype.Timestamptz `json:"updated_at"`
}

type EntitlementDrift struct {
	ID            pgtype.UUID        `json:"id"`
	EntitlementID pgtype.UUID        `json:"entitlement_id"`
	Kind          string             `json:"kind"`
	Expected      []byte             `json:"expected"`
	Observed      []byte             `json:"observed"`
	Status        string             `json:"status"`
	DetectedAt    pgtype.Timestamptz `json:"detected_at"`
	ResolvedAt    pgtype.Timestamptz `json:"resolved_at"`
}

type FulfillmentHistory struct {
	ID              pgtype.UUID        `json:"id"`
	OperationID     pgtype.UUID        `json:"operation_id"`
	Status          string             `json:"status"`
	CorrelationID   string             `json:"correlation_id"`
	RequestSummary  []byte             `json:"request_summary"`
	ResponseSummary []byte             `json:"response_summary"`
	ErrorCode       pgtype.Text        `json:"error_code"`
	OccurredAt      pgtype.Timestamptz `json:"occurred_at"`
}

type FulfillmentOperation struct {
	ID             pgtype.UUID        `json:"id"`
	EntitlementID  pgtype.UUID        `json:"entitlement_id"`
	Operation      string             `json:"operation"`
	Status         string             `json:"status"`
	IdempotencyKey string             `json:"idempotency_key"`
	CorrelationID  string             `json:"correlation_id"`
	DesiredState   []byte             `json:"desired_state"`
	AttemptCount   int32              `json:"attempt_count"`
	NextAttemptAt  pgtype.Timestamptz `json:"next_attempt_at"`
	LastErrorCode  pgtype.Text        `json:"last_error_code"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
	CompletedAt    pgtype.Timestamptz `json:"completed_at"`
}

type Identity struct {
	ID              pgtype.UUID        `json:"id"`
	UserID          pgtype.UUID        `json:"user_id"`
	Provider        string             `json:"provider"`
	ProviderSubject string             `json:"provider_subject"`
	VerifiedAt      pgtype.Timestamptz `json:"verified_at"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	Status          string             `json:"status"`
	RevokedAt       pgtype.Timestamptz `json:"revoked_at"`
	Metadata        []byte             `json:"metadata"`
}

type LedgerEntry struct {
	ID            pgtype.UUID        `json:"id"`
	TransactionID pgtype.UUID        `json:"transaction_id"`
	AccountType   string             `json:"account_type"`
	UserID        pgtype.UUID        `json:"user_id"`
	Currency      string             `json:"currency"`
	AmountMinor   int64              `json:"amount_minor"`
	ExpiresAt     pgtype.Timestamptz `json:"expires_at"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}

type LedgerTransaction struct {
	ID             pgtype.UUID        `json:"id"`
	Type           string             `json:"type"`
	ReferenceType  string             `json:"reference_type"`
	ReferenceID    string             `json:"reference_id"`
	IdempotencyKey string             `json:"idempotency_key"`
	Reason         pgtype.Text        `json:"reason"`
	ActorID        pgtype.Text        `json:"actor_id"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

type ManualPaymentApproval struct {
	ID              pgtype.UUID        `json:"id"`
	PaymentIntentID pgtype.UUID        `json:"payment_intent_id"`
	Decision        string             `json:"decision"`
	OperatorID      string             `json:"operator_id"`
	Reason          string             `json:"reason"`
	IdempotencyKey  string             `json:"idempotency_key"`
	RequestID       pgtype.Text        `json:"request_id"`
	OccurredAt      pgtype.Timestamptz `json:"occurred_at"`
}

type NewsPost struct {
	ID          pgtype.UUID        `json:"id"`
	Slug        string             `json:"slug"`
	Category    string             `json:"category"`
	Class       string             `json:"class"`
	PublishedAt pgtype.Timestamptz `json:"published_at"`
	ExpiresAt   pgtype.Timestamptz `json:"expires_at"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type NewsPostLocalization struct {
	PostID pgtype.UUID `json:"post_id"`
	Locale string      `json:"locale"`
	Title  string      `json:"title"`
	Body   string      `json:"body"`
}

type NewsRead struct {
	UserID pgtype.UUID        `json:"user_id"`
	PostID pgtype.UUID        `json:"post_id"`
	ReadAt pgtype.Timestamptz `json:"read_at"`
}

type NotificationDelivery struct {
	ID            pgtype.UUID        `json:"id"`
	UserID        pgtype.UUID        `json:"user_id"`
	Kind          string             `json:"kind"`
	DedupeKey     string             `json:"dedupe_key"`
	Status        string             `json:"status"`
	ScheduledAt   pgtype.Timestamptz `json:"scheduled_at"`
	SentAt        pgtype.Timestamptz `json:"sent_at"`
	FailureCount  int32              `json:"failure_count"`
	Class         string             `json:"class"`
	ErrorCode     pgtype.Text        `json:"error_code"`
	DeferredUntil pgtype.Timestamptz `json:"deferred_until"`
}

type Order struct {
	ID             pgtype.UUID        `json:"id"`
	UserID         pgtype.UUID        `json:"user_id"`
	State          string             `json:"state"`
	Operation      string             `json:"operation"`
	Currency       string             `json:"currency"`
	SubtotalMinor  int64              `json:"subtotal_minor"`
	DiscountMinor  int64              `json:"discount_minor"`
	WalletMinor    int64              `json:"wallet_minor"`
	ExternalMinor  int64              `json:"external_minor"`
	PaidMinor      int64              `json:"paid_minor"`
	RefundedMinor  int64              `json:"refunded_minor"`
	IdempotencyKey string             `json:"idempotency_key"`
	ExpiresAt      pgtype.Timestamptz `json:"expires_at"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

type OrderLine struct {
	ID              pgtype.UUID `json:"id"`
	OrderID         pgtype.UUID `json:"order_id"`
	PlanID          pgtype.UUID `json:"plan_id"`
	PlanVersionID   pgtype.UUID `json:"plan_version_id"`
	Quantity        int32       `json:"quantity"`
	UnitAmountMinor int64       `json:"unit_amount_minor"`
	Snapshot        []byte      `json:"snapshot"`
}

type OrderMutation struct {
	ID             pgtype.UUID        `json:"id"`
	OrderID        pgtype.UUID        `json:"order_id"`
	Action         string             `json:"action"`
	IdempotencyKey string             `json:"idempotency_key"`
	Reason         pgtype.Text        `json:"reason"`
	OccurredAt     pgtype.Timestamptz `json:"occurred_at"`
}

type OutboxEvent struct {
	ID          pgtype.UUID        `json:"id"`
	Topic       string             `json:"topic"`
	Payload     []byte             `json:"payload"`
	OccurredAt  pgtype.Timestamptz `json:"occurred_at"`
	PublishedAt pgtype.Timestamptz `json:"published_at"`
}

type PaymentEvent struct {
	ID              pgtype.UUID        `json:"id"`
	PaymentIntentID pgtype.UUID        `json:"payment_intent_id"`
	Type            string             `json:"type"`
	PreviousStatus  pgtype.Text        `json:"previous_status"`
	Status          pgtype.Text        `json:"status"`
	AmountMinor     pgtype.Int8        `json:"amount_minor"`
	Currency        pgtype.Text        `json:"currency"`
	ProviderEventID pgtype.Text        `json:"provider_event_id"`
	Details         []byte             `json:"details"`
	OccurredAt      pgtype.Timestamptz `json:"occurred_at"`
}

type PaymentIntent struct {
	ID                pgtype.UUID        `json:"id"`
	OrderID           pgtype.UUID        `json:"order_id"`
	Provider          string             `json:"provider"`
	Status            string             `json:"status"`
	AmountMinor       int64              `json:"amount_minor"`
	Currency          string             `json:"currency"`
	ProviderReference pgtype.Text        `json:"provider_reference"`
	CheckoutUrl       pgtype.Text        `json:"checkout_url"`
	IdempotencyKey    string             `json:"idempotency_key"`
	Capabilities      []byte             `json:"capabilities"`
	ReceiptMetadata   []byte             `json:"receipt_metadata"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
}

type Plan struct {
	ID         pgtype.UUID        `json:"id"`
	Code       string             `json:"code"`
	Kind       string             `json:"kind"`
	Visible    bool               `json:"visible"`
	SortOrder  int32              `json:"sort_order"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	ArchivedAt pgtype.Timestamptz `json:"archived_at"`
}

type PlanLocalization struct {
	PlanID      pgtype.UUID `json:"plan_id"`
	Locale      string      `json:"locale"`
	Name        string      `json:"name"`
	Description string      `json:"description"`
}

type PlanPrice struct {
	PlanVersionID pgtype.UUID `json:"plan_version_id"`
	Currency      string      `json:"currency"`
	AmountMinor   int64       `json:"amount_minor"`
}

type PlanVersion struct {
	ID                    pgtype.UUID        `json:"id"`
	PlanID                pgtype.UUID        `json:"plan_id"`
	Version               int32              `json:"version"`
	BillingPeriod         string             `json:"billing_period"`
	DurationSeconds       int64              `json:"duration_seconds"`
	TrafficAllowanceBytes pgtype.Int8        `json:"traffic_allowance_bytes"`
	DeviceLimit           pgtype.Int4        `json:"device_limit"`
	RemnawaveSquadIds     []pgtype.UUID      `json:"remnawave_squad_ids"`
	UpgradePolicy         string             `json:"upgrade_policy"`
	DowngradePolicy       string             `json:"downgrade_policy"`
	CancellationPolicy    string             `json:"cancellation_policy"`
	RecurringCapable      bool               `json:"recurring_capable"`
	CreatedAt             pgtype.Timestamptz `json:"created_at"`
	RetiredAt             pgtype.Timestamptz `json:"retired_at"`
	GracePeriodSeconds    int64              `json:"grace_period_seconds"`
	TrialEligibility      string             `json:"trial_eligibility"`
}

type PromoCode struct {
	ID              pgtype.UUID        `json:"id"`
	PromotionID     pgtype.UUID        `json:"promotion_id"`
	NormalizedCode  string             `json:"normalized_code"`
	RedemptionLimit pgtype.Int4        `json:"redemption_limit"`
	Active          bool               `json:"active"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
}

type PromoRedemption struct {
	ID            pgtype.UUID        `json:"id"`
	PromoCodeID   pgtype.UUID        `json:"promo_code_id"`
	PromotionID   pgtype.UUID        `json:"promotion_id"`
	UserID        pgtype.UUID        `json:"user_id"`
	OrderID       pgtype.UUID        `json:"order_id"`
	DiscountMinor int64              `json:"discount_minor"`
	RedeemedAt    pgtype.Timestamptz `json:"redeemed_at"`
}

type Promotion struct {
	ID               pgtype.UUID        `json:"id"`
	Code             string             `json:"code"`
	Kind             string             `json:"kind"`
	Value            int64              `json:"value"`
	Currency         pgtype.Text        `json:"currency"`
	StartsAt         pgtype.Timestamptz `json:"starts_at"`
	EndsAt           pgtype.Timestamptz `json:"ends_at"`
	RedemptionLimit  pgtype.Int4        `json:"redemption_limit"`
	PerCustomerLimit int32              `json:"per_customer_limit"`
	Eligibility      []byte             `json:"eligibility"`
	Active           bool               `json:"active"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
}

type PromotionPlan struct {
	PromotionID pgtype.UUID `json:"promotion_id"`
	PlanID      pgtype.UUID `json:"plan_id"`
}

type ProviderWebhookEvent struct {
	ID              pgtype.UUID        `json:"id"`
	Provider        string             `json:"provider"`
	ProviderEventID string             `json:"provider_event_id"`
	SignatureValid  bool               `json:"signature_valid"`
	BodySha256      []byte             `json:"body_sha256"`
	RawBody         []byte             `json:"raw_body"`
	Headers         []byte             `json:"headers"`
	Status          string             `json:"status"`
	ErrorCode       pgtype.Text        `json:"error_code"`
	ReceivedAt      pgtype.Timestamptz `json:"received_at"`
	ProcessedAt     pgtype.Timestamptz `json:"processed_at"`
	RetainUntil     pgtype.Timestamptz `json:"retain_until"`
}

type ReferralAttribution struct {
	ReferredUserID    pgtype.UUID        `json:"referred_user_id"`
	ReferrerUserID    pgtype.UUID        `json:"referrer_user_id"`
	Code              string             `json:"code"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	QualifiedAt       pgtype.Timestamptz `json:"qualified_at"`
	QualifyingOrderID pgtype.UUID        `json:"qualifying_order_id"`
	RejectedReason    pgtype.Text        `json:"rejected_reason"`
}

type ReferralCode struct {
	UserID    pgtype.UUID        `json:"user_id"`
	Code      string             `json:"code"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type ReferralProgram struct {
	Singleton               bool               `json:"singleton"`
	Enabled                 bool               `json:"enabled"`
	Currency                string             `json:"currency"`
	InviterRewardMinor      int64              `json:"inviter_reward_minor"`
	InviteeRewardMinor      int64              `json:"invitee_reward_minor"`
	Qualification           string             `json:"qualification"`
	InviterRewardCap        pgtype.Int4        `json:"inviter_reward_cap"`
	AttributionValidityDays int32              `json:"attribution_validity_days"`
	RewardExpiryDays        pgtype.Int4        `json:"reward_expiry_days"`
	TermsUrl                pgtype.Text        `json:"terms_url"`
	UpdatedAt               pgtype.Timestamptz `json:"updated_at"`
}

type ReferralReward struct {
	ID                  pgtype.UUID        `json:"id"`
	ReferredUserID      pgtype.UUID        `json:"referred_user_id"`
	BeneficiaryUserID   pgtype.UUID        `json:"beneficiary_user_id"`
	Role                string             `json:"role"`
	OrderID             pgtype.UUID        `json:"order_id"`
	AmountMinor         int64              `json:"amount_minor"`
	Currency            string             `json:"currency"`
	LedgerTransactionID pgtype.UUID        `json:"ledger_transaction_id"`
	GrantedAt           pgtype.Timestamptz `json:"granted_at"`
}

type Refund struct {
	ID                pgtype.UUID        `json:"id"`
	PaymentIntentID   pgtype.UUID        `json:"payment_intent_id"`
	Status            string             `json:"status"`
	AmountMinor       int64              `json:"amount_minor"`
	Currency          string             `json:"currency"`
	ProviderReference pgtype.Text        `json:"provider_reference"`
	Reason            string             `json:"reason"`
	IdempotencyKey    string             `json:"idempotency_key"`
	ReceiptMetadata   []byte             `json:"receipt_metadata"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
}

type RemnawaveUser struct {
	UserID        pgtype.UUID        `json:"user_id"`
	RemnawaveID   int64              `json:"remnawave_id"`
	TelegramID    pgtype.Int8        `json:"telegram_id"`
	ObservedState []byte             `json:"observed_state"`
	ReconciledAt  pgtype.Timestamptz `json:"reconciled_at"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}

type SupportAttachment struct {
	ID             pgtype.UUID        `json:"id"`
	MessageID      int64              `json:"message_id"`
	Kind           string             `json:"kind"`
	TelegramFileID string             `json:"telegram_file_id"`
	FileName       pgtype.Text        `json:"file_name"`
	MimeType       pgtype.Text        `json:"mime_type"`
	SizeBytes      int64              `json:"size_bytes"`
	RetainUntil    pgtype.Timestamptz `json:"retain_until"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

type SupportMessage struct {
	ID                int64              `json:"id"`
	TicketID          pgtype.UUID        `json:"ticket_id"`
	Sender            string             `json:"sender"`
	Body              string             `json:"body"`
	TelegramMessageID pgtype.Int8        `json:"telegram_message_id"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	DedupeKey         pgtype.Text        `json:"dedupe_key"`
	DeliveredAt       pgtype.Timestamptz `json:"delivered_at"`
	ReadAt            pgtype.Timestamptz `json:"read_at"`
}

type SupportTicket struct {
	ID                  pgtype.UUID        `json:"id"`
	UserID              pgtype.UUID        `json:"user_id"`
	Status              string             `json:"status"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	UpdatedAt           pgtype.Timestamptz `json:"updated_at"`
	Subject             string             `json:"subject"`
	Priority            string             `json:"priority"`
	LastMessageAt       pgtype.Timestamptz `json:"last_message_at"`
	CustomerUnreadCount int32              `json:"customer_unread_count"`
	ClosedAt            pgtype.Timestamptz `json:"closed_at"`
}

type TelemetryEvent struct {
	ID             int64              `json:"id"`
	InstallationID pgtype.UUID        `json:"installation_id"`
	Name           string             `json:"name"`
	Version        string             `json:"version"`
	Service        string             `json:"service"`
	Os             string             `json:"os"`
	Architecture   string             `json:"architecture"`
	Features       []byte             `json:"features"`
	Counters       []byte             `json:"counters"`
	OccurredAt     pgtype.Timestamptz `json:"occurred_at"`
	ReceivedAt     pgtype.Timestamptz `json:"received_at"`
}

type TelemetryInstallation struct {
	Singleton      bool               `json:"singleton"`
	InstallationID pgtype.UUID        `json:"installation_id"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

type TrialClaim struct {
	UserID    pgtype.UUID        `json:"user_id"`
	PlanID    pgtype.UUID        `json:"plan_id"`
	OrderID   pgtype.UUID        `json:"order_id"`
	ClaimedAt pgtype.Timestamptz `json:"claimed_at"`
}

type User struct {
	ID             pgtype.UUID        `json:"id"`
	Status         string             `json:"status"`
	Locale         string             `json:"locale"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
	Timezone       string             `json:"timezone"`
	SuspendedAt    pgtype.Timestamptz `json:"suspended_at"`
	DeletedAt      pgtype.Timestamptz `json:"deleted_at"`
	AnonymizedAt   pgtype.Timestamptz `json:"anonymized_at"`
	RetentionUntil pgtype.Timestamptz `json:"retention_until"`
}
