// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	// What one scope has spent, for the budget check that runs before a call.
	AIUsageForWindow(ctx context.Context, arg AIUsageForWindowParams) (AIUsageForWindowRow, error)
	// Token, request, latency, error, and estimated-cost reporting, grouped by the
	// dimensions an owner reads. No prompt content appears because none is stored.
	AIUsageReport(ctx context.Context, arg AIUsageReportParams) ([]AIUsageReportRow, error)
	AcquirePaymentMutationLock(ctx context.Context, hashtextextended string) error
	AddBlocklistAllowlistEntry(ctx context.Context, arg AddBlocklistAllowlistEntryParams) (BlocklistAllowlist, error)
	AddPromotionPlan(ctx context.Context, arg AddPromotionPlanParams) error
	AnonymizeCustomerData(ctx context.Context, targetUserID pgtype.UUID) error
	AppealBlocklistMatch(ctx context.Context, arg AppealBlocklistMatchParams) (BlocklistMatch, error)
	AppendOperatorMessage(ctx context.Context, arg AppendOperatorMessageParams) (SupportMessage, error)
	AppendSupportNote(ctx context.Context, arg AppendSupportNoteParams) (SupportNote, error)
	ApplyCustomerImportItem(ctx context.Context, arg ApplyCustomerImportItemParams) (CustomerImportItem, error)
	ApplyCustomerLifecycle(ctx context.Context, arg ApplyCustomerLifecycleParams) (User, error)
	// Add-on capacity is folded into the entitlement itself, so the existing
	// fulfillment pipeline reads one desired state and never sums add-ons again.
	ApplyEntitlementAddonTotals(ctx context.Context, arg ApplyEntitlementAddonTotalsParams) (Entitlement, error)
	ApproveManualPayment(ctx context.Context, arg ApproveManualPaymentParams) (ManualPaymentApproval, error)
	ArchiveCannedResponse(ctx context.Context, responseID pgtype.UUID) (SupportCannedResponse, error)
	ArchivePlan(ctx context.Context, arg ArchivePlanParams) (Plan, error)
	// A queue with open tickets in it cannot be archived. Archiving one would hide
	// work rather than finish it.
	ArchiveSupportQueue(ctx context.Context, queueID pgtype.UUID) (SupportQueue, error)
	// ---------------------------------------------------------------------------
	// Ticket mutations
	// ---------------------------------------------------------------------------
	// Assigning to NULL releases the ticket back to its queue, which is a normal
	// action rather than an error state: an operator who cannot finish something
	// should be able to put it down.
	AssignSupportTicket(ctx context.Context, arg AssignSupportTicketParams) (SupportTicket, error)
	AttachReferralSignal(ctx context.Context, arg AttachReferralSignalParams) error
	// A backup nobody has ever restored is a backup nobody knows works, so the last
	// restore is part of the status rather than a separate screen.
	BackupStatus(ctx context.Context) (BackupStatusRow, error)
	// Claims the next attempt and pushes the retry deadline out before any provider
	// call is made, so a worker that dies mid-request does not have the row picked
	// up again immediately.
	BeginGoodsDeliveryAttempt(ctx context.Context, arg BeginGoodsDeliveryAttemptParams) (GoodsDelivery, error)
	BindOperatorTopic(ctx context.Context, arg BindOperatorTopicParams) (OperatorTopic, error)
	// A handful of recipients a campaign would reach, for the preview.
	//
	// It is a sample rather than the list: an operator checking a segment needs to
	// see that it selected the right kind of person, and rendering ten thousand
	// customers to prove it is both slow and a disclosure nobody asked for.
	CampaignRecipientSample(ctx context.Context, sampleSize int32) ([]CampaignRecipientSampleRow, error)
	CancelBulkOperation(ctx context.Context, operationID pgtype.UUID) (BulkOperation, error)
	CancelCart(ctx context.Context, userID pgtype.UUID) (Cart, error)
	// Only an operation that has not yet succeeded may be cancelled, so a completed
	// provisioning can never be retracted by a panel click.
	CancelFulfillmentOperation(ctx context.Context, operationID pgtype.UUID) (FulfillmentOperation, error)
	CancelGoodsDelivery(ctx context.Context, orderID pgtype.UUID) (GoodsDelivery, error)
	CancelOrder(ctx context.Context, arg CancelOrderParams) (Order, error)
	ChannelGateSettings(ctx context.Context) (ChannelGateSettingsRow, error)
	CheckPromotionCustomerEligibility(ctx context.Context, arg CheckPromotionCustomerEligibilityParams) (pgtype.Bool, error)
	// Single redemption by construction: the predicate only matches a deliverable,
	// unexpired gift, so a second claim of the same code updates no row.
	ClaimGift(ctx context.Context, arg ClaimGiftParams) (Gift, error)
	ClearCartGoods(ctx context.Context, cartID pgtype.UUID) error
	ClearDefaultPaymentMethod(ctx context.Context, userID pgtype.UUID) error
	CloseSubscription(ctx context.Context, arg CloseSubscriptionParams) (Subscription, error)
	// Promotes a half-authenticated session once the second factor is proven. The
	// token is rotated in the same statement so the cookie that existed during the
	// challenge cannot be replayed as a fully authenticated one.
	CompleteAdminSessionChallenge(ctx context.Context, arg CompleteAdminSessionChallengeParams) (AdminSession, error)
	CompleteBackup(ctx context.Context, arg CompleteBackupParams) (Backup, error)
	CompleteBackupRestore(ctx context.Context, arg CompleteBackupRestoreParams) (BackupRestore, error)
	CompleteBulkOperationItem(ctx context.Context, arg CompleteBulkOperationItemParams) (BulkOperationItem, error)
	// The status guard makes this safe to call twice: a retried delivery updates
	// nothing rather than overwriting the outcome already recorded.
	CompleteCampaignTestSend(ctx context.Context, arg CompleteCampaignTestSendParams) error
	CompleteGoodsDelivery(ctx context.Context, arg CompleteGoodsDeliveryParams) (GoodsDelivery, error)
	CompleteOperatorNotification(ctx context.Context, arg CompleteOperatorNotificationParams) (OperatorNotification, error)
	CompleteWebhookEvent(ctx context.Context, arg CompleteWebhookEventParams) (ProviderWebhookEvent, error)
	ConfigureAIFeature(ctx context.Context, arg ConfigureAIFeatureParams) (AiFeature, error)
	ConfirmAdminTOTP(ctx context.Context, adminUserID pgtype.UUID) (AdminUser, error)
	ConsumeAdminPasswordReset(ctx context.Context, resetID pgtype.UUID) (AdminPasswordReset, error)
	// Single-use by construction: the `used_at IS NULL` predicate means a replay of
	// the same code updates no row and returns no result.
	ConsumeAdminRecoveryCode(ctx context.Context, arg ConsumeAdminRecoveryCodeParams) (AdminRecoveryCode, error)
	ConsumeAdminSetupToken(ctx context.Context, arg ConsumeAdminSetupTokenParams) (AdminSetupToken, error)
	// Single use is a property of this statement, not of the code around it: the
	// `consumed_at IS NULL` predicate is evaluated under the row lock the UPDATE
	// takes, so two browsers racing on one link produce exactly one winner.
	ConsumeCustomerMagicLink(ctx context.Context, arg ConsumeCustomerMagicLinkParams) (CustomerMagicLink, error)
	// Callers must hold LockCustomerSubscriptions for this count to be meaningful.
	CountActiveSubscriptions(ctx context.Context, arg CountActiveSubscriptionsParams) (CountActiveSubscriptionsRow, error)
	CountAdminOIDCIdentities(ctx context.Context, adminUserID pgtype.UUID) (int64, error)
	// Guards the "an installation always keeps one owner" invariant. Only accounts
	// that could actually sign in count, so suspending the last owner is refused
	// for the same reason revoking the role is.
	CountAdminOwners(ctx context.Context, excludingAdminUserID pgtype.UUID) (int64, error)
	// How many times this operator has signed in from an address before. Zero means
	// the current sign-in is from somewhere new, which is what makes a security
	// notice worth sending rather than noise on every successful login.
	CountAdminSessionsFromAddress(ctx context.Context, arg CountAdminSessionsFromAddressParams) (int64, error)
	// Operator identity, sessions, and the audit trail for the v0.6 admin panel.
	// ---------------------------------------------------------------------------
	// Administrator accounts
	// ---------------------------------------------------------------------------
	CountAdminUsers(ctx context.Context) (int64, error)
	CountCannedResponseUse(ctx context.Context, responseID pgtype.UUID) error
	CountDunningAttemptsForCycle(ctx context.Context, cycleKey string) (int64, error)
	CountGiftsByStatus(ctx context.Context) ([]CountGiftsByStatusRow, error)
	CountOpenAnomalySignals(ctx context.Context) (int64, error)
	CountOpenBlocklistMatches(ctx context.Context) (int64, error)
	CountPlanVersionSquads(ctx context.Context, arg CountPlanVersionSquadsParams) (int32, error)
	CountPromoRedemptions(ctx context.Context, arg CountPromoRedemptionsParams) (CountPromoRedemptionsRow, error)
	// Feeds the per-customer request limit, so asking for a link repeatedly cannot
	// be used to flood somebody's Telegram chat.
	CountRecentCustomerMagicLinks(ctx context.Context, arg CountRecentCustomerMagicLinksParams) (int64, error)
	CountRecentOperatorNotifications(ctx context.Context, arg CountRecentOperatorNotificationsParams) (int32, error)
	CountRunningBackups(ctx context.Context) (int32, error)
	CountUnpublishedOutboxEvents(ctx context.Context) (CountUnpublishedOutboxEventsRow, error)
	CountUnusedAdminRecoveryCodes(ctx context.Context, adminUserID pgtype.UUID) (int64, error)
	CreateAddonPrice(ctx context.Context, arg CreateAddonPriceParams) (AddonPrice, error)
	CreateAddonVersion(ctx context.Context, arg CreateAddonVersionParams) (AddonVersion, error)
	// ---------------------------------------------------------------------------
	// Password resets
	// ---------------------------------------------------------------------------
	// The expiry is derived from the database clock, not the application's.
	// `created_at` defaults to now(), so taking the deadline from a second clock
	// would let drift between the two violate `expires_at > created_at` and reject
	// an otherwise valid request.
	CreateAdminPasswordReset(ctx context.Context, arg CreateAdminPasswordResetParams) (AdminPasswordReset, error)
	// ---------------------------------------------------------------------------
	// Sessions
	// ---------------------------------------------------------------------------
	CreateAdminSession(ctx context.Context, arg CreateAdminSessionParams) (AdminSession, error)
	// ---------------------------------------------------------------------------
	// First-owner bootstrap
	// ---------------------------------------------------------------------------
	// Same single-clock rule as the password reset above.
	CreateAdminSetupToken(ctx context.Context, arg CreateAdminSetupTokenParams) (AdminSetupToken, error)
	CreateAdminUser(ctx context.Context, arg CreateAdminUserParams) (AdminUser, error)
	// ---------------------------------------------------------------------------
	// Backups
	// ---------------------------------------------------------------------------
	CreateBackup(ctx context.Context, arg CreateBackupParams) (Backup, error)
	CreateBackupRestore(ctx context.Context, arg CreateBackupRestoreParams) (BackupRestore, error)
	// ---------------------------------------------------------------------------
	// Bulk operator actions
	// ---------------------------------------------------------------------------
	CreateBulkOperation(ctx context.Context, arg CreateBulkOperationParams) (BulkOperation, error)
	CreateCampaign(ctx context.Context, arg CreateCampaignParams) (Campaign, error)
	CreateContactChannel(ctx context.Context, arg CreateContactChannelParams) (ContactChannel, error)
	// Used only when a sign-in route is allowed to provision. The row it creates is
	// an ordinary customer with no entitlement, no balance, and no Remnawave user.
	CreateCustomerForSignIn(ctx context.Context, arg CreateCustomerForSignInParams) (User, error)
	CreateCustomerImport(ctx context.Context) (CustomerImport, error)
	// ---------------------------------------------------------------------------
	// Magic links
	// ---------------------------------------------------------------------------
	CreateCustomerMagicLink(ctx context.Context, arg CreateCustomerMagicLinkParams) (CustomerMagicLink, error)
	// ---------------------------------------------------------------------------
	// Sessions
	// ---------------------------------------------------------------------------
	CreateCustomerSession(ctx context.Context, arg CreateCustomerSessionParams) (CustomerSession, error)
	CreateEntitlement(ctx context.Context, arg CreateEntitlementParams) (Entitlement, error)
	CreateFulfillmentOperation(ctx context.Context, arg CreateFulfillmentOperationParams) (FulfillmentOperation, error)
	// Gifts and personal offers.
	//
	// A gift is bought by one customer for another, so every query here is careful
	// about which side it is answering for: the sender sees their own order and a
	// code hint, the recipient sees only what they were given.
	// ---------------------------------------------------------------------------
	// Gifts
	// ---------------------------------------------------------------------------
	CreateGift(ctx context.Context, arg CreateGiftParams) (Gift, error)
	// ---------------------------------------------------------------------------
	// Delivery
	// ---------------------------------------------------------------------------
	// The primary key on `order_id` is the whole double-delivery guard: a second
	// insert for the same order conflicts and returns nothing, whatever caused the
	// replay.
	CreateGoodsDelivery(ctx context.Context, arg CreateGoodsDeliveryParams) (GoodsDelivery, error)
	// ---------------------------------------------------------------------------
	// Orders
	// ---------------------------------------------------------------------------
	CreateGoodsOrder(ctx context.Context, arg CreateGoodsOrderParams) (GoodsOrder, error)
	CreateGoodsProduct(ctx context.Context, arg CreateGoodsProductParams) (GoodsProduct, error)
	CreateLedgerTransaction(ctx context.Context, arg CreateLedgerTransactionParams) (LedgerTransaction, error)
	CreateLoyaltyProgram(ctx context.Context, arg CreateLoyaltyProgramParams) (LoyaltyProgram, error)
	CreateLoyaltyTier(ctx context.Context, arg CreateLoyaltyTierParams) (LoyaltyTier, error)
	CreateOrder(ctx context.Context, arg CreateOrderParams) (Order, error)
	CreatePaymentIntent(ctx context.Context, arg CreatePaymentIntentParams) (PaymentIntent, error)
	// ---------------------------------------------------------------------------
	// Personal offers
	// ---------------------------------------------------------------------------
	// The partial unique index on active offers is what makes a re-run of a
	// targeting job idempotent: the second insert conflicts and returns nothing.
	CreatePersonalOffer(ctx context.Context, arg CreatePersonalOfferParams) (PersonalOffer, error)
	CreatePlan(ctx context.Context, arg CreatePlanParams) (Plan, error)
	CreatePlanPrice(ctx context.Context, arg CreatePlanPriceParams) (PlanPrice, error)
	CreatePlanVersion(ctx context.Context, arg CreatePlanVersionParams) (PlanVersion, error)
	// ---------------------------------------------------------------------------
	// Catalogue authoring
	// ---------------------------------------------------------------------------
	// A plan version is immutable once an order references it, so the editor never
	// updates one: it creates the next version and lets the old one keep pricing
	// the orders that already used it.
	CreatePlanVersionFull(ctx context.Context, arg CreatePlanVersionFullParams) (PlanVersion, error)
	CreatePromoCode(ctx context.Context, arg CreatePromoCodeParams) (PromoCode, error)
	CreatePromotion(ctx context.Context, arg CreatePromotionParams) (Promotion, error)
	CreateRefund(ctx context.Context, arg CreateRefundParams) (Refund, error)
	CreateSubscription(ctx context.Context, arg CreateSubscriptionParams) (Subscription, error)
	// ---------------------------------------------------------------------------
	// Wallet top-up
	// ---------------------------------------------------------------------------
	CreateWalletTopup(ctx context.Context, arg CreateWalletTopupParams) (WalletTopup, error)
	CreditWalletTopup(ctx context.Context, arg CreditWalletTopupParams) (WalletTopup, error)
	// The metric a standing is evaluated on, computed from facts Omniflow already
	// records. Nothing new is tracked to support loyalty.
	CustomerLoyaltyMetric(ctx context.Context, arg CustomerLoyaltyMetricParams) (CustomerLoyaltyMetricRow, error)
	// ---------------------------------------------------------------------------
	// Dashboard
	// ---------------------------------------------------------------------------
	// Every count carries its own definition, which the panel repeats beside the
	// number: "active" is a customer record that is neither suspended nor deleted,
	// not one with a live subscription.
	//
	// `shift` moves the window back by its own length, so the same statement serves
	// both the current period and the one before it. That is what lets the panel
	// show a comparison without a second, subtly different query that could drift
	// from this one.
	DashboardCustomerTotals(ctx context.Context, arg DashboardCustomerTotalsParams) (DashboardCustomerTotalsRow, error)
	DashboardDriftTotals(ctx context.Context) (DashboardDriftTotalsRow, error)
	DashboardJobHealth(ctx context.Context, lateAfter pgtype.Interval) (DashboardJobHealthRow, error)
	// The oldest unpublished event is the honest measure of lag: a queue with a
	// thousand fresh events is healthy, and one with a single event from an hour
	// ago is not.
	DashboardOutboxLag(ctx context.Context) (DashboardOutboxLagRow, error)
	DashboardPaymentHealth(ctx context.Context, arg DashboardPaymentHealthParams) (DashboardPaymentHealthRow, error)
	// What each configured payment provider last reported. The panel shows it
	// beside the live dependency probes so an operator sees "configured but never
	// reached" as distinct from "reached and failing".
	DashboardProviderHealth(ctx context.Context) ([]DashboardProviderHealthRow, error)
	// Deliberately three separate figures rather than one "revenue": money taken
	// through a provider, wallet credit spent, and money returned are different
	// questions, and adding them together answers none of them.
	DashboardRevenue(ctx context.Context, arg DashboardRevenueParams) ([]DashboardRevenueRow, error)
	DashboardSubscriptionTotals(ctx context.Context, lookback pgtype.Interval) (DashboardSubscriptionTotalsRow, error)
	DashboardSupportTotals(ctx context.Context, staleAfter pgtype.Interval) (DashboardSupportTotalsRow, error)
	DashboardWebhookHealth(ctx context.Context, lookback pgtype.Interval) (DashboardWebhookHealthRow, error)
	// The only path that moves a match out of review. The deciding operator and
	// their reason are required by the row itself, so an adverse decision cannot be
	// recorded anonymously.
	DecideBlocklistMatch(ctx context.Context, arg DecideBlocklistMatchParams) (BlocklistMatch, error)
	// Pushes an attempt out without resolving it.
	//
	// This is what a still-pending payment gets. The provider has been asked and
	// has not answered; recording a failure would be a lie and charging again
	// would risk taking the money twice, so the attempt keeps its number and waits.
	DeferDunningAttempt(ctx context.Context, arg DeferDunningAttemptParams) (DunningAttempt, error)
	DeleteAIProvider(ctx context.Context, slug string) error
	DeleteAIUsageLimit(ctx context.Context, id pgtype.UUID) error
	DeleteAdminOIDCProvider(ctx context.Context, slug string) error
	// ---------------------------------------------------------------------------
	// Recovery codes
	// ---------------------------------------------------------------------------
	DeleteAdminRecoveryCodes(ctx context.Context, adminUserID pgtype.UUID) error
	// ---------------------------------------------------------------------------
	// Blocklist entries
	// ---------------------------------------------------------------------------
	// A refresh replaces a source's entries wholesale inside one transaction, so an
	// entry the publisher removed stops matching in the same instant the new set
	// starts.
	DeleteBlocklistEntries(ctx context.Context, sourceID pgtype.UUID) error
	DeleteBlocklistSource(ctx context.Context, id pgtype.UUID) error
	DeleteCartAddon(ctx context.Context, arg DeleteCartAddonParams) error
	DeleteCustomerOIDCProvider(ctx context.Context, slug string) (int64, error)
	// ---------------------------------------------------------------------------
	// Retention and cleanup
	// ---------------------------------------------------------------------------
	DeleteExpiredBotSessions(ctx context.Context) (int64, error)
	DeleteExpiredCheckoutSessions(ctx context.Context) (int64, error)
	DeleteExpiredCustomerMagicLinks(ctx context.Context, retention pgtype.Interval) (int64, error)
	DeleteExpiredCustomerSecurityEvents(ctx context.Context, retention pgtype.Interval) (int64, error)
	// Retention sweep. A session is removed only once it is well past any use, so
	// the security list can still explain a recent sign-out.
	DeleteExpiredCustomerSessions(ctx context.Context, retention pgtype.Interval) (int64, error)
	DeleteExpiredSupportAttachments(ctx context.Context) (int64, error)
	DeleteExpiredWebhookEvents(ctx context.Context) (int64, error)
	DeleteMCPServer(ctx context.Context, slug string) error
	DeleteOldTelemetryEvents(ctx context.Context, retentionSeconds float64) (int64, error)
	DeletePublishedOutboxEvents(ctx context.Context, retentionSeconds float64) (int64, error)
	DeleteRequiredChannel(ctx context.Context, id pgtype.UUID) error
	DeleteResolvedDrifts(ctx context.Context, retentionSeconds float64) (int64, error)
	// Row counts for the tables an operator's question usually concerns. Counts
	// rather than samples, for the obvious reason.
	DiagnosticCounts(ctx context.Context) (DiagnosticCountsRow, error)
	DisableAdminTOTP(ctx context.Context, adminUserID pgtype.UUID) (AdminUser, error)
	DismissPersonalOffer(ctx context.Context, arg DismissPersonalOfferParams) (PersonalOffer, error)
	// ---------------------------------------------------------------------------
	// Test sends
	//
	// One copy of a campaign's message, to the operator group, before the audience
	// is committed to. None of these queries touches campaign_recipients, which is
	// what keeps a test out of the counters an operator judges the campaign by.
	// ---------------------------------------------------------------------------
	EnqueueCampaignTestSend(ctx context.Context, arg EnqueueCampaignTestSendParams) (CampaignTestSend, error)
	EnqueueOperatorNotification(ctx context.Context, arg EnqueueOperatorNotificationParams) (OperatorNotification, error)
	// Retires outstanding tokens by moving their expiry into the past rather than
	// marking them consumed: `admin_setup_tokens_consumption_complete` requires a
	// consuming account, and an unredeemed token has none. Both the lookup and the
	// redemption already refuse an expired row.
	ExpireAdminSetupTokens(ctx context.Context) (int64, error)
	ExpireCarts(ctx context.Context) ([]Cart, error)
	ExpireGifts(ctx context.Context) ([]Gift, error)
	ExpirePendingOrders(ctx context.Context) ([]Order, error)
	ExpirePersonalOffers(ctx context.Context) (int64, error)
	// The export that answers "which of these were shaped by a model?".
	ExportAIDecisions(ctx context.Context, arg ExportAIDecisionsParams) ([]ExportAIDecisionsRow, error)
	// The customer export, in a stable column order.
	//
	// It carries the identifiers an operator may safely be given and the facts they
	// need to reconcile against another system. It deliberately does not carry a
	// subscription link, a payment token, or a hardware identifier: an export is a
	// file that leaves the installation, and those must not.
	ExportCustomers(ctx context.Context, arg ExportCustomersParams) ([]ExportCustomersRow, error)
	// The CSV export's source. Column order here is the column order in the file,
	// and the schema is stable: a new column is appended, never inserted, so a
	// spreadsheet or importer built against an older export keeps working.
	ExportFinanceRows(ctx context.Context, arg ExportFinanceRowsParams) ([]ExportFinanceRowsRow, error)
	FailBackup(ctx context.Context, arg FailBackupParams) (Backup, error)
	FailGoodsDelivery(ctx context.Context, arg FailGoodsDeliveryParams) (GoodsDelivery, error)
	FailOperatorTopic(ctx context.Context, arg FailOperatorTopicParams) (OperatorTopic, error)
	GetAIFeature(ctx context.Context, feature string) (AiFeature, error)
	GetAIProviderCredentials(ctx context.Context, slug string) (GetAIProviderCredentialsRow, error)
	GetAccountSubscription(ctx context.Context, arg GetAccountSubscriptionParams) (GetAccountSubscriptionRow, error)
	// Customer web sign-in, sessions, and account security for v0.9.
	// ---------------------------------------------------------------------------
	// Identity resolution
	// ---------------------------------------------------------------------------
	// The single lookup every sign-in route funnels through. Matching on the
	// (provider, subject) pair and nothing else is what makes an upstream email
	// change a non-event: the subject is the identifier, the address is a claim.
	GetActiveIdentityBySubject(ctx context.Context, arg GetActiveIdentityBySubjectParams) (GetActiveIdentityBySubjectRow, error)
	GetActiveOfferForPromotion(ctx context.Context, arg GetActiveOfferForPromotionParams) (PersonalOffer, error)
	GetAddonVersionForOrder(ctx context.Context, arg GetAddonVersionForOrderParams) (GetAddonVersionForOrderRow, error)
	GetAdminOIDCIdentity(ctx context.Context, arg GetAdminOIDCIdentityParams) (GetAdminOIDCIdentityRow, error)
	GetAdminOIDCProviderBySlug(ctx context.Context, slug string) (AdminOidcProvider, error)
	GetAdminPasswordReset(ctx context.Context, tokenHash []byte) (GetAdminPasswordResetRow, error)
	// Returns the session and its owner in one round trip. Liveness is decided in
	// Go so an expired session can be distinguished from a missing one and revoked
	// explicitly, rather than silently disappearing from the result set.
	GetAdminSessionByToken(ctx context.Context, tokenHash []byte) (GetAdminSessionByTokenRow, error)
	GetAdminSetupToken(ctx context.Context, tokenHash []byte) (AdminSetupToken, error)
	GetAdminUser(ctx context.Context, id pgtype.UUID) (AdminUser, error)
	GetAdminUserByEmail(ctx context.Context, emailNormalized string) (AdminUser, error)
	GetAnomalyRule(ctx context.Context, metric string) (AnomalyRule, error)
	GetAnomalySignal(ctx context.Context, id pgtype.UUID) (AnomalySignal, error)
	GetAudienceSegment(ctx context.Context, id pgtype.UUID) (AudienceSegment, error)
	// ---------------------------------------------------------------------------
	// Auto-renew
	// ---------------------------------------------------------------------------
	GetAutoRenewSettings(ctx context.Context, arg GetAutoRenewSettingsParams) (AutoRenewSetting, error)
	GetAvailableWalletBalance(ctx context.Context, arg GetAvailableWalletBalanceParams) (int64, error)
	GetBackup(ctx context.Context, id pgtype.UUID) (Backup, error)
	GetBlocklistMatch(ctx context.Context, id pgtype.UUID) (BlocklistMatch, error)
	GetBlocklistSource(ctx context.Context, id pgtype.UUID) (BlocklistSource, error)
	GetBlocklistSourceBySlug(ctx context.Context, slug string) (BlocklistSource, error)
	GetBulkOperation(ctx context.Context, id pgtype.UUID) (BulkOperation, error)
	GetBulkOperationByIdempotency(ctx context.Context, idempotencyKey string) (BulkOperation, error)
	// The live entitlement behind a subscription a bulk operation targets.
	//
	// Addressing a subscription without naming its customer is safe here and only
	// here: the targets were recorded by the preview, which validated them, so this
	// is reading back a decision rather than accepting one.
	GetBulkSubscriptionTarget(ctx context.Context, subscriptionID pgtype.UUID) (GetBulkSubscriptionTargetRow, error)
	GetCampaign(ctx context.Context, id pgtype.UUID) (GetCampaignRow, error)
	GetCannedResponse(ctx context.Context, id pgtype.UUID) (SupportCannedResponse, error)
	GetCartGoods(ctx context.Context, cartID pgtype.UUID) (GetCartGoodsRow, error)
	GetChannelEnforcement(ctx context.Context, userID pgtype.UUID) (ChannelEnforcement, error)
	// Operator panel queries for v0.7: settings, dashboard, customer and finance
	// operations, fulfillment and job diagnostics, and bulk actions.
	//
	// Everything here is read or operated by an authenticated operator whose
	// permissions were already checked in `internal/rbac`. The queries carry no
	// authorization of their own precisely so there is only one place that decides
	// what a role may do.
	// ---------------------------------------------------------------------------
	// Commerce settings
	// ---------------------------------------------------------------------------
	GetCommerceSettings(ctx context.Context) (CommerceSetting, error)
	GetCustomer(ctx context.Context, id pgtype.UUID) (User, error)
	GetCustomerIdentityForUnlink(ctx context.Context, arg GetCustomerIdentityForUnlinkParams) (Identity, error)
	GetCustomerImport(ctx context.Context, id pgtype.UUID) (CustomerImport, error)
	GetCustomerImportItemCounts(ctx context.Context, importID pgtype.UUID) (GetCustomerImportItemCountsRow, error)
	GetCustomerOIDCProvider(ctx context.Context, slug string) (CustomerOidcProvider, error)
	// One round trip for the profile header: the customer, their Telegram mapping,
	// and the counts the page shows before any tab is opened.
	GetCustomerOverview(ctx context.Context, id pgtype.UUID) (GetCustomerOverviewRow, error)
	GetCustomerReferralCode(ctx context.Context, userID pgtype.UUID) (GetCustomerReferralCodeRow, error)
	GetCustomerReferrer(ctx context.Context, referredUserID pgtype.UUID) (GetCustomerReferrerRow, error)
	// Resolves a cookie into a session and the customer behind it in one round trip,
	// because this runs on every authenticated request.
	GetCustomerSessionByToken(ctx context.Context, tokenHash []byte) (GetCustomerSessionByTokenRow, error)
	GetCustomerSubscription(ctx context.Context, arg GetCustomerSubscriptionParams) (Subscription, error)
	// The order a renewal cycle is settling, if one was already opened.
	//
	// All attempts on a cycle share one order — the idempotency key is derived from
	// the cycle key — so this is how a retry finds what the previous attempt
	// created instead of opening a second one.
	GetCycleOrder(ctx context.Context, arg GetCycleOrderParams) (Order, error)
	GetDefaultSupportQueue(ctx context.Context) (SupportQueue, error)
	GetDunningAttempt(ctx context.Context, arg GetDunningAttemptParams) (DunningAttempt, error)
	GetEnabledLoyaltyProgram(ctx context.Context) (LoyaltyProgram, error)
	GetEntitlement(ctx context.Context, id pgtype.UUID) (Entitlement, error)
	GetFulfillmentOperation(ctx context.Context, id pgtype.UUID) (FulfillmentOperation, error)
	GetGift(ctx context.Context, id pgtype.UUID) (Gift, error)
	// The claim path's only lookup. The plaintext code never reaches the database.
	GetGiftByCodeHash(ctx context.Context, codeHash []byte) (Gift, error)
	GetGiftByOrder(ctx context.Context, orderID pgtype.UUID) (Gift, error)
	GetGoodsDelivery(ctx context.Context, orderID pgtype.UUID) (GoodsDelivery, error)
	GetGoodsOrder(ctx context.Context, orderID pgtype.UUID) (GoodsOrder, error)
	GetGoodsPricing(ctx context.Context, productID pgtype.UUID) (GoodsPricing, error)
	GetGoodsProduct(ctx context.Context, id pgtype.UUID) (GoodsProduct, error)
	GetGoodsProductByCode(ctx context.Context, code string) (GoodsProduct, error)
	GetGoodsProvider(ctx context.Context, slug string) (GoodsProvider, error)
	GetLatestBackup(ctx context.Context) (Backup, error)
	GetLatestConsents(ctx context.Context, userID pgtype.UUID) ([]ConsentRecord, error)
	GetLatestEntitlementForChange(ctx context.Context, arg GetLatestEntitlementForChangeParams) (Entitlement, error)
	GetLedgerTransactionByIdempotency(ctx context.Context, idempotencyKey string) (LedgerTransaction, error)
	GetLoyaltyStanding(ctx context.Context, userID pgtype.UUID) (GetLoyaltyStandingRow, error)
	GetMCPServer(ctx context.Context, slug string) (GetMCPServerRow, error)
	GetMCPServerCredentials(ctx context.Context, slug string) ([]byte, error)
	GetMaintenanceState(ctx context.Context) (MaintenanceState, error)
	GetMessageTemplate(ctx context.Context, id pgtype.UUID) (MessageTemplate, error)
	GetOpenCart(ctx context.Context, userID pgtype.UUID) (Cart, error)
	GetOperatorTopic(ctx context.Context, kind string) (OperatorTopic, error)
	GetOrder(ctx context.Context, id pgtype.UUID) (Order, error)
	GetOrderByIdempotency(ctx context.Context, arg GetOrderByIdempotencyParams) (Order, error)
	GetOrderEntitlementSpec(ctx context.Context, orderID pgtype.UUID) (GetOrderEntitlementSpecRow, error)
	GetPaymentIntent(ctx context.Context, id pgtype.UUID) (PaymentIntent, error)
	GetPaymentIntentByIdempotency(ctx context.Context, arg GetPaymentIntentByIdempotencyParams) (PaymentIntent, error)
	GetPaymentIntentByOrderProvider(ctx context.Context, arg GetPaymentIntentByOrderProviderParams) (PaymentIntent, error)
	GetPaymentIntentByProviderReference(ctx context.Context, arg GetPaymentIntentByProviderReferenceParams) (PaymentIntent, error)
	GetPaymentMethod(ctx context.Context, id pgtype.UUID) (PaymentMethod, error)
	GetPaymentProviderSettings(ctx context.Context, arg GetPaymentProviderSettingsParams) (PaymentProviderSetting, error)
	GetPersonalOffer(ctx context.Context, id pgtype.UUID) (PersonalOffer, error)
	GetPlanAdmin(ctx context.Context, id pgtype.UUID) (Plan, error)
	GetPlanVersionForOrder(ctx context.Context, arg GetPlanVersionForOrderParams) (GetPlanVersionForOrderRow, error)
	GetPrimarySubscription(ctx context.Context, userID pgtype.UUID) (Subscription, error)
	GetPromoForRedemption(ctx context.Context, normalizedCode string) (GetPromoForRedemptionRow, error)
	GetPromotionAdmin(ctx context.Context, id pgtype.UUID) (Promotion, error)
	// The single referral configuration. The table is a singleton because a second
	// programme would mean two answers to "what does an invite earn?", and the
	// customer would have been told one of them.
	GetReferralProgram(ctx context.Context) (ReferralProgram, error)
	GetRefundByIdempotency(ctx context.Context, arg GetRefundByIdempotencyParams) (Refund, error)
	GetRemnawaveMappingByCustomer(ctx context.Context, userID pgtype.UUID) (RemnawaveUser, error)
	GetRemnawaveUserIDByTelegramID(ctx context.Context, telegramID pgtype.Int8) (int64, error)
	GetReservedRefundAmount(ctx context.Context, paymentIntentID pgtype.UUID) (int64, error)
	// Read by the processes that need the credential, never by a request handler
	// that answers an operator.
	GetSettingSecrets(ctx context.Context, section string) ([]byte, error)
	GetSettingSection(ctx context.Context, section string) (GetSettingSectionRow, error)
	GetSubscription(ctx context.Context, id pgtype.UUID) (Subscription, error)
	GetSubscriptionByRemnawaveUser(ctx context.Context, remnawaveUserID pgtype.Int8) (Subscription, error)
	GetSupportQueue(ctx context.Context, id pgtype.UUID) (SupportQueue, error)
	GetSupportTagByCode(ctx context.Context, code string) (SupportTag, error)
	GetSupportTicket(ctx context.Context, id pgtype.UUID) (GetSupportTicketRow, error)
	GetTelemetryInstallationID(ctx context.Context) (pgtype.UUID, error)
	GetWalletBalance(ctx context.Context, arg GetWalletBalanceParams) (int64, error)
	GetWebhookEventForReplay(ctx context.Context, id pgtype.UUID) (ProviderWebhookEvent, error)
	// ---------------------------------------------------------------------------
	// Role grants
	// ---------------------------------------------------------------------------
	GrantAdminRole(ctx context.Context, arg GrantAdminRoleParams) error
	GrantChannelExemption(ctx context.Context, arg GrantChannelExemptionParams) (ChannelExemption, error)
	InsertAdminRecoveryCode(ctx context.Context, arg InsertAdminRecoveryCodeParams) error
	// The single writer for the audit trail. `category` and `outcome` are the two
	// axes the admin panel filters and exports on, so every caller classifies its
	// event rather than letting it fall into an untyped bucket.
	InsertAuditEvent(ctx context.Context, arg InsertAuditEventParams) (AuditEvent, error)
	InsertBlocklistEntry(ctx context.Context, arg InsertBlocklistEntryParams) error
	InsertBulkOperationItem(ctx context.Context, arg InsertBulkOperationItemParams) error
	InsertConsentRecord(ctx context.Context, arg InsertConsentRecordParams) (ConsentRecord, error)
	InsertCustomerLifecycleEvent(ctx context.Context, arg InsertCustomerLifecycleEventParams) (CustomerLifecycleEvent, error)
	// ---------------------------------------------------------------------------
	// Security events
	// ---------------------------------------------------------------------------
	InsertCustomerSecurityEvent(ctx context.Context, arg InsertCustomerSecurityEventParams) (CustomerSecurityEvent, error)
	InsertEntitlementAddon(ctx context.Context, arg InsertEntitlementAddonParams) (EntitlementAddon, error)
	InsertEntitlementDrift(ctx context.Context, arg InsertEntitlementDriftParams) (EntitlementDrift, error)
	InsertFulfillmentHistory(ctx context.Context, arg InsertFulfillmentHistoryParams) (FulfillmentHistory, error)
	InsertGoodsDeliveryAttempt(ctx context.Context, arg InsertGoodsDeliveryAttemptParams) (GoodsDeliveryAttempt, error)
	InsertLedgerEntry(ctx context.Context, arg InsertLedgerEntryParams) (LedgerEntry, error)
	InsertMaintenanceEvent(ctx context.Context, arg InsertMaintenanceEventParams) (MaintenanceEvent, error)
	InsertOrderAddonLine(ctx context.Context, arg InsertOrderAddonLineParams) (OrderAddonLine, error)
	InsertOrderLine(ctx context.Context, arg InsertOrderLineParams) (OrderLine, error)
	InsertOutboxEvent(ctx context.Context, arg InsertOutboxEventParams) (OutboxEvent, error)
	InsertPaymentEvent(ctx context.Context, arg InsertPaymentEventParams) (PaymentEvent, error)
	InsertPromoRedemption(ctx context.Context, arg InsertPromoRedemptionParams) (PromoRedemption, error)
	InsertWebhookEvent(ctx context.Context, arg InsertWebhookEventParams) (ProviderWebhookEvent, error)
	InvalidateAdminPasswordResets(ctx context.Context, adminUserID pgtype.UUID) (int64, error)
	IsAddonOfferedForPlan(ctx context.Context, arg IsAddonOfferedForPlanParams) (bool, error)
	IsBlocklistAllowlisted(ctx context.Context, userID pgtype.UUID) (bool, error)
	IsChannelExempt(ctx context.Context, userID pgtype.UUID) (bool, error)
	// The same rule for the shop. Empty scoping means every visible product,
	// which is safe here in a way the applies_to default was not: an operator
	// writing a goods promotion has by definition decided goods are in scope.
	IsPromotionGoodsEligible(ctx context.Context, arg IsPromotionGoodsEligibleParams) (bool, error)
	// A promotion must name the plans catalogue to discount a plan.
	//
	// The applies_to clause is load-bearing rather than belt-and-braces: an
	// unscoped promotion has no promotion_plans rows, so without it a promotion
	// written for the shop would pass the wildcard branch and discount every plan.
	IsPromotionPlanEligible(ctx context.Context, arg IsPromotionPlanEligibleParams) (bool, error)
	IsSuppressed(ctx context.Context, userID pgtype.UUID) (bool, error)
	LinkAdminOIDCIdentity(ctx context.Context, arg LinkAdminOIDCIdentityParams) (AdminOidcIdentity, error)
	LinkCustomerIdentity(ctx context.Context, arg LinkCustomerIdentityParams) (Identity, error)
	LinkTelegramRemnawaveUser(ctx context.Context, arg LinkTelegramRemnawaveUserParams) (int64, error)
	ListAIFeatures(ctx context.Context) ([]AiFeature, error)
	ListAIProviders(ctx context.Context) ([]ListAIProvidersRow, error)
	ListAIUsageLimits(ctx context.Context) ([]AiUsageLimit, error)
	// The customer web panel's own read model for v0.9.
	//
	// Every statement is scoped by `user_id`. Ownership is part of the query rather
	// than a check the caller is trusted to perform first, so an identifier lifted
	// from a URL can never address somebody else's subscription.
	// One row per active subscription, with the entitlement currently in force and
	// the plan version it was bought under.
	//
	// The lateral join takes the latest entitlement that has not been superseded:
	// an extension writes a new row rather than editing the old one, so "current"
	// is the newest live row rather than the only row.
	ListAccountSubscriptions(ctx context.Context, arg ListAccountSubscriptionsParams) ([]ListAccountSubscriptionsRow, error)
	// What the bot shows. Expired-but-not-yet-swept rows are filtered here rather
	// than relying on the sweeper having run, so an offer never outlives its window
	// on screen.
	ListActiveOffersForCustomer(ctx context.Context, arg ListActiveOffersForCustomerParams) ([]ListActiveOffersForCustomerRow, error)
	ListActiveRetentionHolds(ctx context.Context) ([]AiRetentionHold, error)
	ListAddonPrices(ctx context.Context, addonVersionID pgtype.UUID) ([]AddonPrice, error)
	ListAddonVersions(ctx context.Context, addonID pgtype.UUID) ([]AddonVersion, error)
	ListAddonsAdmin(ctx context.Context) ([]ListAddonsAdminRow, error)
	// ---------------------------------------------------------------------------
	// Optional OIDC configuration
	// ---------------------------------------------------------------------------
	ListAdminOIDCProviders(ctx context.Context) ([]AdminOidcProvider, error)
	ListAdminRoles(ctx context.Context, adminUserID pgtype.UUID) ([]string, error)
	ListAdminRolesForUsers(ctx context.Context, adminUserIds []pgtype.UUID) ([]ListAdminRolesForUsersRow, error)
	ListAdminSessions(ctx context.Context, arg ListAdminSessionsParams) ([]AdminSession, error)
	// Keyset pagination on (created_at, id): the pair is unique, so a page boundary
	// never repeats or skips a row even when several accounts share a timestamp.
	ListAdminUsers(ctx context.Context, arg ListAdminUsersParams) ([]AdminUser, error)
	// ---------------------------------------------------------------------------
	// Anomaly rules and signals
	// ---------------------------------------------------------------------------
	ListAnomalyRules(ctx context.Context) ([]AnomalyRule, error)
	// ---------------------------------------------------------------------------
	// Segments and templates
	// ---------------------------------------------------------------------------
	ListAudienceSegments(ctx context.Context) ([]AudienceSegment, error)
	// Populates the action filter without scanning the whole table from the client.
	ListAuditEventActions(ctx context.Context) ([]string, error)
	// Only carts whose customer holds wallet history are considered, so the sweep
	// never re-prices a cart that cannot possibly be covered yet.
	ListAutoPurchaseCarts(ctx context.Context, limit int32) ([]ListAutoPurchaseCartsRow, error)
	// Subscriptions whose entitlement ends inside the configured lead time and that
	// have no renewal attempt outstanding for the cycle. The cycle key is derived
	// here, from the entitlement identity and its end instant, so the worker and
	// the dunning table agree on what "this renewal" means without a second round
	// trip.
	ListAutoRenewDue(ctx context.Context, pageSize int32) ([]ListAutoRenewDueRow, error)
	ListBackupRestores(ctx context.Context, limit int32) ([]BackupRestore, error)
	ListBackups(ctx context.Context, limit int32) ([]Backup, error)
	ListBlocklistMatchesForCustomer(ctx context.Context, userID pgtype.UUID) ([]ListBlocklistMatchesForCustomerRow, error)
	// External blocklists and anomaly detection.
	//
	// Both surfaces produce evidence for an operator, never an automatic sanction.
	// No query in this file suspends a customer, cancels an order, or moves money;
	// the panel's ordinary customer and finance mutations do that, with their own
	// permission checks and audit events, once a human has decided.
	// ---------------------------------------------------------------------------
	// Blocklist sources
	// ---------------------------------------------------------------------------
	ListBlocklistSources(ctx context.Context) ([]BlocklistSource, error)
	ListBulkOperationItems(ctx context.Context, arg ListBulkOperationItemsParams) ([]BulkOperationItem, error)
	ListBulkOperations(ctx context.Context, pageSize int32) ([]BulkOperation, error)
	ListCampaignTestSends(ctx context.Context, arg ListCampaignTestSendsParams) ([]CampaignTestSend, error)
	// ---------------------------------------------------------------------------
	// Campaigns
	// ---------------------------------------------------------------------------
	ListCampaigns(ctx context.Context, pageSize int32) ([]ListCampaignsRow, error)
	// ---------------------------------------------------------------------------
	// Canned responses
	// ---------------------------------------------------------------------------
	ListCannedResponses(ctx context.Context) ([]SupportCannedResponse, error)
	ListCartAddons(ctx context.Context, cartID pgtype.UUID) ([]CartAddon, error)
	// Warned customers whose grace has run out.
	ListChannelEnforcementDue(ctx context.Context, pageSize int32) ([]ListChannelEnforcementDueRow, error)
	ListChannelExemptions(ctx context.Context, pageSize int32) ([]ListChannelExemptionsRow, error)
	ListContactChannels(ctx context.Context, userID pgtype.UUID) ([]ListContactChannelsRow, error)
	ListCustomerConsents(ctx context.Context, userID pgtype.UUID) ([]ConsentRecord, error)
	ListCustomerIdentities(ctx context.Context, userID pgtype.UUID) ([]Identity, error)
	ListCustomerImportItems(ctx context.Context, arg ListCustomerImportItemsParams) ([]CustomerImportItem, error)
	ListCustomerImportTelegramIDs(ctx context.Context, importID pgtype.UUID) ([]ListCustomerImportTelegramIDsRow, error)
	// The import history an operator reviews. Newest first, because the question is
	// almost always about the run that just happened.
	ListCustomerImports(ctx context.Context, pageSize int32) ([]CustomerImport, error)
	ListCustomerLedgerEntries(ctx context.Context, arg ListCustomerLedgerEntriesParams) ([]ListCustomerLedgerEntriesRow, error)
	ListCustomerMemberships(ctx context.Context, userID pgtype.UUID) ([]ChannelMembership, error)
	// ---------------------------------------------------------------------------
	// Customer OIDC providers
	// ---------------------------------------------------------------------------
	ListCustomerOIDCProviders(ctx context.Context) ([]CustomerOidcProvider, error)
	ListCustomerOrders(ctx context.Context, arg ListCustomerOrdersParams) ([]Order, error)
	// Who this customer invited, and whether the invitation turned into anything.
	//
	// The invitee is named only by identifier: a referrer is entitled to know how
	// many of their invitations converted, not to a list of other people's account
	// details.
	ListCustomerReferrals(ctx context.Context, arg ListCustomerReferralsParams) ([]ListCustomerReferralsRow, error)
	ListCustomerSecurityEvents(ctx context.Context, arg ListCustomerSecurityEventsParams) ([]CustomerSecurityEvent, error)
	// The customer's own device list, live sessions first and most recent first.
	ListCustomerSessions(ctx context.Context, arg ListCustomerSessionsParams) ([]CustomerSession, error)
	// ---------------------------------------------------------------------------
	// Linked sign-in methods
	// ---------------------------------------------------------------------------
	// Everything that can currently sign this customer in. The unlink guard reads
	// this list rather than counting in SQL, so one rule in `internal/customer`
	// decides what "the last usable method" means.
	ListCustomerSignInIdentities(ctx context.Context, userID pgtype.UUID) ([]Identity, error)
	// Every concurrent subscription with the entitlement currently governing it, so
	// the panel can offer independent lifecycle actions per subscription rather
	// than assuming one per customer.
	//
	// The entitlement columns are selected individually rather than embedded: a
	// subscription that has never been provisioned has no entitlement at all, and
	// an embedded struct would have to scan those nulls into non-nullable fields.
	ListCustomerSubscriptionsDetailed(ctx context.Context, userID pgtype.UUID) ([]ListCustomerSubscriptionsDetailedRow, error)
	ListCustomerSupportTickets(ctx context.Context, arg ListCustomerSupportTicketsParams) ([]SupportTicket, error)
	// Customers whose membership answer has gone stale, oldest first.
	//
	// A customer with no record at all is included, because "never checked" and
	// "checked long ago" need the same thing done about them.
	ListCustomersForChannelRecheck(ctx context.Context, arg ListCustomersForChannelRecheckParams) ([]ListCustomersForChannelRecheckRow, error)
	ListDueBlocklistSources(ctx context.Context, pageSize int32) ([]BlocklistSource, error)
	ListDueCampaigns(ctx context.Context, pageSize int32) ([]Campaign, error)
	ListDueDunningAttempts(ctx context.Context, pageSize int32) ([]DunningAttempt, error)
	ListDueGoodsDeliveries(ctx context.Context, pageSize int32) ([]GoodsDelivery, error)
	ListDueNewsPosts(ctx context.Context, pageSize int32) ([]NewsPost, error)
	ListDunningAttemptsForCustomer(ctx context.Context, arg ListDunningAttemptsForCustomerParams) ([]DunningAttempt, error)
	ListEnabledAdminOIDCProviders(ctx context.Context) ([]AdminOidcProvider, error)
	ListEnabledChannels(ctx context.Context) ([]RequiredChannel, error)
	ListEnabledCustomerOIDCProviders(ctx context.Context) ([]CustomerOidcProvider, error)
	// What an installation actually exposes: enabled tools on enabled servers whose
	// schema this build can enforce.
	ListEnabledMCPTools(ctx context.Context) ([]McpTool, error)
	ListEntitlementsForReconciliation(ctx context.Context, limit int32) ([]Entitlement, error)
	ListExpiredBackups(ctx context.Context, limit int32) ([]Backup, error)
	ListExpiredWalletCredits(ctx context.Context, limit int32) ([]ListExpiredWalletCreditsRow, error)
	ListFulfillmentHistoryForOperation(ctx context.Context, operationID pgtype.UUID) ([]FulfillmentHistory, error)
	ListGiftsForSender(ctx context.Context, arg ListGiftsForSenderParams) ([]Gift, error)
	ListGiftsReceived(ctx context.Context, arg ListGiftsReceivedParams) ([]Gift, error)
	ListGoodsDeliveriesNeedingReview(ctx context.Context, pageSize int32) ([]ListGoodsDeliveriesNeedingReviewRow, error)
	ListGoodsDeliveryAttempts(ctx context.Context, orderID pgtype.UUID) ([]GoodsDeliveryAttempt, error)
	ListGoodsOrdersForCustomer(ctx context.Context, arg ListGoodsOrdersForCustomerParams) ([]ListGoodsOrdersForCustomerRow, error)
	ListGoodsProductLocalizations(ctx context.Context, productID pgtype.UUID) ([]GoodsProductLocalization, error)
	// ---------------------------------------------------------------------------
	// Catalogue
	// ---------------------------------------------------------------------------
	ListGoodsProducts(ctx context.Context, includeArchived pgtype.Bool) ([]GoodsProduct, error)
	// Digital goods: providers, catalogue, orders, and delivery.
	//
	// Nothing in this file touches an entitlement, a subscription, or a Remnawave
	// mapping. A digital good is sold, delivered, and refunded entirely inside its
	// own tables plus the shared order, payment, and ledger pipeline.
	// ---------------------------------------------------------------------------
	// Providers
	// ---------------------------------------------------------------------------
	ListGoodsProviders(ctx context.Context) ([]GoodsProvider, error)
	ListLedgerEntriesByTransaction(ctx context.Context, transactionID pgtype.UUID) ([]LedgerEntry, error)
	ListLoyaltyHistory(ctx context.Context, arg ListLoyaltyHistoryParams) ([]ListLoyaltyHistoryRow, error)
	// ---------------------------------------------------------------------------
	// Loyalty
	// ---------------------------------------------------------------------------
	ListLoyaltyPrograms(ctx context.Context, pageSize int32) ([]LoyaltyProgram, error)
	ListLoyaltyTiers(ctx context.Context, programID pgtype.UUID) ([]LoyaltyTier, error)
	ListMCPEvents(ctx context.Context, arg ListMCPEventsParams) ([]McpEvent, error)
	// The registry as the panel reads it. The credential column is not selected, so
	// listing servers cannot leak one.
	ListMCPServers(ctx context.Context) ([]ListMCPServersRow, error)
	ListMCPTools(ctx context.Context, serverSlug string) ([]McpTool, error)
	ListMessageTemplates(ctx context.Context) ([]MessageTemplate, error)
	ListOpenDriftsDetailed(ctx context.Context, pageSize int32) ([]ListOpenDriftsDetailedRow, error)
	ListOpenEntitlementDrifts(ctx context.Context, limit int32) ([]EntitlementDrift, error)
	// Payment attempts on an order that have neither settled nor failed.
	//
	// A renewal must not be charged again while one of these is outstanding: the
	// provider may still settle it, and a second charge would take the money twice.
	ListOpenIntentsForOrder(ctx context.Context, orderID pgtype.UUID) ([]PaymentIntent, error)
	ListOperatorTopics(ctx context.Context) ([]OperatorTopic, error)
	ListOrderAddonLines(ctx context.Context, orderID pgtype.UUID) ([]OrderAddonLine, error)
	ListOrderPaymentIntents(ctx context.Context, orderID pgtype.UUID) ([]PaymentIntent, error)
	ListPaymentEventsForIntent(ctx context.Context, paymentIntentID pgtype.UUID) ([]PaymentEvent, error)
	ListPaymentIntentsForReconciliation(ctx context.Context, limit int32) ([]PaymentIntent, error)
	// Saved payment methods, auto-renew, and the dunning schedule.
	//
	// Nothing here holds an instrument. A saved method is a provider-issued token
	// and a masked label the provider supplied; a charge is made by handing that
	// token back to the adapter that issued it.
	// ---------------------------------------------------------------------------
	// Saved payment methods
	// ---------------------------------------------------------------------------
	ListPaymentMethods(ctx context.Context, userID pgtype.UUID) ([]PaymentMethod, error)
	// ---------------------------------------------------------------------------
	// Payment provider configuration
	// ---------------------------------------------------------------------------
	ListPaymentProviderSettings(ctx context.Context) ([]PaymentProviderSetting, error)
	ListPendingBulkOperationItems(ctx context.Context, arg ListPendingBulkOperationItemsParams) ([]BulkOperationItem, error)
	ListPendingCampaignRecipients(ctx context.Context, arg ListPendingCampaignRecipientsParams) ([]ListPendingCampaignRecipientsRow, error)
	// The template is joined rather than stored on the row, so a test send always
	// renders whatever the template says now — which is the point of asking for one
	// after editing it.
	ListPendingCampaignTestSends(ctx context.Context, pageSize int32) ([]ListPendingCampaignTestSendsRow, error)
	// Failures the customer has not been told about, oldest first.
	//
	// The filter is deliberately a plain read of a stored decision. Which failures
	// deserve a message is a product rule, and it is applied by the worker that
	// resolved the attempt.
	ListPendingDunningNotifications(ctx context.Context, pageSize int32) ([]ListPendingDunningNotificationsRow, error)
	ListPendingOperatorNotifications(ctx context.Context, limit int32) ([]OperatorNotification, error)
	// ---------------------------------------------------------------------------
	// Add-ons
	// ---------------------------------------------------------------------------
	ListPlanAddons(ctx context.Context, arg ListPlanAddonsParams) ([]ListPlanAddonsRow, error)
	ListPlanLocalizations(ctx context.Context, planID pgtype.UUID) ([]PlanLocalization, error)
	ListPlanPrices(ctx context.Context, planVersionID pgtype.UUID) ([]PlanPrice, error)
	ListPlanVersionSquads(ctx context.Context, planVersionID pgtype.UUID) ([]PlanVersionSquad, error)
	ListPlanVersions(ctx context.Context, planID pgtype.UUID) ([]PlanVersion, error)
	// ---------------------------------------------------------------------------
	// Catalogue administration
	// ---------------------------------------------------------------------------
	// The catalogue as an operator sees it: archived plans included, with the
	// current version and how many orders reference the plan, so archiving
	// something in active use is a visible decision rather than a surprise.
	ListPlansAdmin(ctx context.Context) ([]ListPlansAdminRow, error)
	ListPromoCodesForPromotion(ctx context.Context, promotionID pgtype.UUID) ([]ListPromoCodesForPromotionRow, error)
	ListPromotionPlans(ctx context.Context, promotionID pgtype.UUID) ([]Plan, error)
	// The panel's review queue: failed and abandoned charges, newest first, with
	// the customer attached so the list is usable without a second lookup per row.
	ListRecentDunningFailures(ctx context.Context, arg ListRecentDunningFailuresParams) ([]ListRecentDunningFailuresRow, error)
	ListRecentMaintenanceEvents(ctx context.Context, pageSize int32) ([]MaintenanceEvent, error)
	ListReferralRewardsForPair(ctx context.Context, referredUserID pgtype.UUID) ([]ReferralReward, error)
	ListRefundsForOrder(ctx context.Context, orderID pgtype.UUID) ([]Refund, error)
	ListRemnawaveMappings(ctx context.Context) ([]ListRemnawaveMappingsRow, error)
	// Mandatory channel subscription.
	ListRequiredChannels(ctx context.Context) ([]RequiredChannel, error)
	// AI governance, MCP connections, and installation settings.
	// Every section without its secrets. This is the query the settings screens
	// read, and it cannot return a credential because the column is not selected.
	ListSettingSections(ctx context.Context) ([]ListSettingSectionsRow, error)
	// Intents that have been in flight longer than a provider should take. The
	// panel offers reconciliation and retry from this list; neither mutates money
	// directly, both go through the existing idempotent payment service.
	ListStuckPaymentIntents(ctx context.Context, arg ListStuckPaymentIntentsParams) ([]ListStuckPaymentIntentsRow, error)
	// Omniflow v0.5 queries: subscriptions, wallet top-up, carts, add-ons,
	// operator notifications, backups, maintenance mode, and retention.
	// ---------------------------------------------------------------------------
	// Subscriptions
	// ---------------------------------------------------------------------------
	ListSubscriptions(ctx context.Context, userID pgtype.UUID) ([]Subscription, error)
	ListSubscriptionsForAlerts(ctx context.Context, limit int32) ([]ListSubscriptionsForAlertsRow, error)
	// ---------------------------------------------------------------------------
	// Messages, notes, and tags
	// ---------------------------------------------------------------------------
	ListSupportMessages(ctx context.Context, arg ListSupportMessagesParams) ([]ListSupportMessagesRow, error)
	ListSupportNotes(ctx context.Context, arg ListSupportNotesParams) ([]ListSupportNotesRow, error)
	// The support desk.
	//
	// Every read here is queue-shaped: an operator's question is almost always
	// "what is waiting, and who has it", not "show me ticket X". The one lookup by
	// identifier exists for the conversation view a queue row links to.
	// ---------------------------------------------------------------------------
	// Queues
	// ---------------------------------------------------------------------------
	ListSupportQueues(ctx context.Context) ([]ListSupportQueuesRow, error)
	ListSupportTags(ctx context.Context) ([]SupportTag, error)
	// ---------------------------------------------------------------------------
	// Suppression
	// ---------------------------------------------------------------------------
	ListSuppressions(ctx context.Context, pageSize int32) ([]ListSuppressionsRow, error)
	ListTelegramIdentitySubjects(ctx context.Context) ([]string, error)
	ListUnpublishedOutboxEvents(ctx context.Context, pageSize int32) ([]ListUnpublishedOutboxEventsRow, error)
	// The customer-facing catalogue in one round trip: product, localisation for
	// the requested locale, and the pricing rule that produces the quote.
	ListVisibleGoodsProducts(ctx context.Context, locale string) ([]ListVisibleGoodsProductsRow, error)
	ListVisiblePlans(ctx context.Context, locale string) ([]ListVisiblePlansRow, error)
	ListWalletTopups(ctx context.Context, arg ListWalletTopupsParams) ([]ListWalletTopupsRow, error)
	// Serialises concurrent purchases for one customer so two taps cannot both
	// observe a stale count and both pass a concurrency limit check. It is a
	// statement of its own rather than a CTE, because a planner is free not to
	// evaluate a CTE whose rows are never needed.
	LockCustomerSubscriptions(ctx context.Context, dollar_1 string) error
	LockFulfillmentOperation(ctx context.Context, id pgtype.UUID) (FulfillmentOperation, error)
	// Serialises claim, revoke, and expiry against one another. Without it two
	// simultaneous claims of one code could both observe 'deliverable'.
	LockGift(ctx context.Context, id pgtype.UUID) (Gift, error)
	// Taken before every provider submission. Two workers racing on one order
	// serialise here, and the loser re-reads a row that is already submitted.
	LockGoodsDelivery(ctx context.Context, orderID pgtype.UUID) (GoodsDelivery, error)
	LockOpenCart(ctx context.Context, userID pgtype.UUID) (Cart, error)
	LockOrder(ctx context.Context, id pgtype.UUID) (Order, error)
	LockSupportTicket(ctx context.Context, id pgtype.UUID) (SupportTicket, error)
	LockWalletTopup(ctx context.Context, orderID pgtype.UUID) (WalletTopup, error)
	MarkBackupPruned(ctx context.Context, id pgtype.UUID) (Backup, error)
	MarkCartPurchased(ctx context.Context, arg MarkCartPurchasedParams) (Cart, error)
	MarkDunningNotified(ctx context.Context, attemptID pgtype.UUID) (DunningAttempt, error)
	// Settlement of the sender's order is what makes a gift claimable. Restricting
	// the update to 'pending' means a replayed settlement changes nothing.
	MarkGiftDeliverable(ctx context.Context, giftID pgtype.UUID) (Gift, error)
	MarkGiftRefunded(ctx context.Context, giftID pgtype.UUID) (Gift, error)
	MarkPaymentMethodStatus(ctx context.Context, arg MarkPaymentMethodStatusParams) (PaymentMethod, error)
	MarkSupportTicketRead(ctx context.Context, ticketID pgtype.UUID) (SupportTicket, error)
	// Reprocessing is replay-safe because the downstream handlers are keyed on the
	// provider event identifier, so a second pass over the same body reaches the
	// same terminal state instead of applying twice.
	MarkWebhookEventForReplay(ctx context.Context, eventID pgtype.UUID) (ProviderWebhookEvent, error)
	// Given the fingerprints of a customer's identifiers, returns every enabled
	// source that lists one of them. An exact index probe per source, so the check
	// is cheap enough to run on the sign-up and purchase paths.
	MatchBlocklistFingerprints(ctx context.Context, fingerprints [][]byte) ([]MatchBlocklistFingerprintsRow, error)
	// The absorbed ticket keeps its row and its messages and points at its
	// survivor. Deleting it would lose the customer's own words and the trail that
	// explains where they went.
	MergeSupportTicket(ctx context.Context, arg MergeSupportTicketParams) (SupportTicket, error)
	// Moves the absorbed ticket's messages onto the survivor so the conversation
	// reads as one thread.
	MoveSupportMessages(ctx context.Context, arg MoveSupportMessagesParams) error
	MoveSupportTicket(ctx context.Context, arg MoveSupportTicketParams) (SupportTicket, error)
	NextAddonVersion(ctx context.Context, addonID pgtype.UUID) (int32, error)
	NextLoyaltyVersion(ctx context.Context) (int32, error)
	NextPlanVersion(ctx context.Context, planID pgtype.UUID) (int32, error)
	// ---------------------------------------------------------------------------
	// Observations the rules are evaluated against
	// ---------------------------------------------------------------------------
	//
	// Each returns a raw aggregate. The comparison against a threshold, the
	// severity, and the dedupe key are decided in `internal/anomaly`, which is
	// where they can be unit-tested without a database.
	// Paid order value per customer inside the window. Per-customer rather than
	// installation-wide because a spike concentrated on one account is the shape
	// that matters; the installation total is on the dashboard already.
	ObservePurchaseVolume(ctx context.Context, arg ObservePurchaseVolumeParams) ([]ObservePurchaseVolumeRow, error)
	// Qualified referrals per inviter. A referral programme being farmed shows up
	// here long before it shows up in the ledger.
	ObserveReferralVolume(ctx context.Context, arg ObserveReferralVolumeParams) ([]ObserveReferralVolumeRow, error)
	ObserveRefundVolume(ctx context.Context, arg ObserveRefundVolumeParams) ([]ObserveRefundVolumeRow, error)
	// Remnawave owns traffic, and Omniflow only holds the counter it last observed.
	// That makes this a level check rather than a rate: a subscription whose
	// observed usage has passed the threshold, not one whose usage grew quickly.
	// The distinction is why the rule's window only controls how often a signal is
	// re-raised, and it is documented on the operator page as well.
	ObserveTrafficUsage(ctx context.Context, arg ObserveTrafficUsageParams) ([]ObserveTrafficUsageRow, error)
	OfferAddonWithPlanVersion(ctx context.Context, arg OfferAddonWithPlanVersionParams) error
	// Stops a delivery whose outcome nobody can safely resolve.
	//
	// It leaves the due queue — the worker's index selects only 'pending' and
	// 'submitted' — and waits for an operator. This is what an ambiguous outcome
	// becomes: the purchase may already have spent the operator's funds, so
	// retrying could deliver twice and refunding could give money back for goods
	// the recipient received.
	ParkGoodsDelivery(ctx context.Context, arg ParkGoodsDeliveryParams) (GoodsDelivery, error)
	PlaceRetentionHold(ctx context.Context, arg PlaceRetentionHoldParams) (AiRetentionHold, error)
	// Enabling one programme disables the rest, because the partial unique index
	// allows exactly one and a customer can only stand in one definition at a time.
	PublishLoyaltyProgram(ctx context.Context, programID pgtype.UUID) (LoyaltyProgram, error)
	PurgeAIUsageBefore(ctx context.Context, occurredAt pgtype.Timestamptz) (int64, error)
	PurgeExpiredAdminSessions(ctx context.Context, cutoff pgtype.Timestamptz) (int64, error)
	// The primary key is the deduplication: a paused-and-resumed campaign continues
	// rather than restarting, and a recipient cannot be queued twice.
	QueueCampaignRecipient(ctx context.Context, arg QueueCampaignRecipientParams) error
	// A condition that persists across several evaluation runs is one signal, not
	// one per run: the dedupe key collides and the existing row is refreshed with
	// the newest observation. A signal an operator already reviewed stays reviewed,
	// because the conflict clause never resets `status`.
	RaiseAnomalySignal(ctx context.Context, arg RaiseAnomalySignalParams) (AnomalySignal, error)
	// ---------------------------------------------------------------------------
	// Maintenance mode
	// ---------------------------------------------------------------------------
	// A read-only probe used on the hot purchase path. A missing row means
	// maintenance mode has never been engaged, which is the same as inactive.
	ReadMaintenanceState(ctx context.Context) (MaintenanceState, error)
	RecordAIDecision(ctx context.Context, arg RecordAIDecisionParams) (AiDecision, error)
	RecordAIProviderCheck(ctx context.Context, arg RecordAIProviderCheckParams) error
	// There is no prompt or output parameter, and there is nowhere to put one.
	RecordAIUsage(ctx context.Context, arg RecordAIUsageParams) error
	// The caller computes the lockout deadline from the resulting attempt count, so
	// the backoff curve stays in Go where it is unit-testable.
	RecordAdminLoginFailure(ctx context.Context, arg RecordAdminLoginFailureParams) (AdminUser, error)
	RecordAdminLoginSuccess(ctx context.Context, adminUserID pgtype.UUID) (AdminUser, error)
	RecordAdminOIDCLogin(ctx context.Context, id pgtype.UUID) error
	RecordBlocklistRefresh(ctx context.Context, arg RecordBlocklistRefreshParams) (BlocklistSource, error)
	RecordCartFailure(ctx context.Context, arg RecordCartFailureParams) (Cart, error)
	// Discovery refreshes the description and schemas and leaves the owner's
	// decisions alone. A rediscovery that re-enabled a tool an owner switched off
	// would make discovery a privilege escalation.
	RecordDiscoveredMCPTool(ctx context.Context, arg RecordDiscoveredMCPToolParams) (McpTool, error)
	// Counts a failed redemption so a code cannot be brute-forced indefinitely. The
	// rate limiter in front of the endpoint is the first defence; this is the
	// durable one that survives a restart.
	RecordGiftClaimAttempt(ctx context.Context, giftID pgtype.UUID) (Gift, error)
	RecordGoodsDeliveryRefund(ctx context.Context, arg RecordGoodsDeliveryRefundParams) (GoodsDelivery, error)
	RecordGoodsProviderHealth(ctx context.Context, arg RecordGoodsProviderHealthParams) (GoodsProvider, error)
	RecordLoyaltyChange(ctx context.Context, arg RecordLoyaltyChangeParams) (LoyaltyStandingHistory, error)
	RecordMCPDiscovery(ctx context.Context, arg RecordMCPDiscoveryParams) error
	RecordMCPEvent(ctx context.Context, arg RecordMCPEventParams) error
	// A failure increments; a success resets. The counter is what the panel reads to
	// explain why a connection is being skipped.
	RecordMCPHealth(ctx context.Context, arg RecordMCPHealthParams) error
	// `left_at` is set the first time absence is seen and cleared on return, so the
	// grace clock measures from when the customer actually left rather than from
	// when a sweep noticed.
	RecordMembership(ctx context.Context, arg RecordMembershipParams) (ChannelMembership, error)
	RecordProviderConnectionCheck(ctx context.Context, arg RecordProviderConnectionCheckParams) (PaymentProviderSetting, error)
	RecordProviderWebhookHealth(ctx context.Context, arg RecordProviderWebhookHealthParams) (PaymentProviderSetting, error)
	// Signals are advisory and deduplicated per pair, so a sweep that runs twice
	// records one signal rather than two.
	RecordReferralSignal(ctx context.Context, arg RecordReferralSignalParams) (ReferralSignal, error)
	// Only the first operator reply sets it, so the measure survives a
	// conversation that goes back and forth for a week.
	RecordSupportFirstResponse(ctx context.Context, ticketID pgtype.UUID) (SupportTicket, error)
	// Counters are recomputed from the items rather than incremented, so a retried
	// worker cannot double-count an outcome it already recorded.
	RecountBulkOperation(ctx context.Context, operationID pgtype.UUID) (BulkOperation, error)
	RecountCampaign(ctx context.Context, campaignID pgtype.UUID) (Campaign, error)
	RedeemPersonalOffer(ctx context.Context, arg RedeemPersonalOfferParams) (PersonalOffer, error)
	// What the programme has actually cost and produced, so an operator changing a
	// reward can see what the current one did rather than guessing.
	ReferralProgramSummary(ctx context.Context) (ReferralProgramSummaryRow, error)
	ReleasePaymentMutationLock(ctx context.Context, hashtextextended string) error
	ReleaseRetentionHold(ctx context.Context, arg ReleaseRetentionHoldParams) (AiRetentionHold, error)
	RemoveBlocklistAllowlistEntry(ctx context.Context, userID pgtype.UUID) error
	RemovePromotionPlan(ctx context.Context, arg RemovePromotionPlanParams) error
	// The label is what every screen and notification uses to name a subscription,
	// which is what makes several concurrent ones legible.
	RenameAccountSubscription(ctx context.Context, arg RenameAccountSubscriptionParams) (Subscription, error)
	RenameSubscription(ctx context.Context, arg RenameSubscriptionParams) (Subscription, error)
	// An operator retry only ever moves a terminal-looking row back into the queue.
	// It cannot skip the idempotency key, so the retried attempt is the same
	// operation the worker already knows how to make exactly once.
	RequeueFulfillmentOperation(ctx context.Context, operationID pgtype.UUID) (FulfillmentOperation, error)
	ResolveCampaignRecipient(ctx context.Context, arg ResolveCampaignRecipientParams) error
	// Only a scheduled attempt resolves, so a retried worker cannot rewrite an
	// outcome that has already been recorded.
	//
	// `notify_required` is written here rather than derived later because the rule
	// that decides it lives in `internal/recurring`, and a second expression of it
	// in SQL would be free to drift.
	ResolveDunningAttempt(ctx context.Context, arg ResolveDunningAttemptParams) (DunningAttempt, error)
	ResolveEntitlementDrifts(ctx context.Context, entitlementID pgtype.UUID) error
	// An operator's verdict on a parked delivery. 'delivered' records that the
	// goods did arrive; 'failed' releases it to the refund path.
	ResolveGoodsDeliveryReview(ctx context.Context, arg ResolveGoodsDeliveryReviewParams) (GoodsDelivery, error)
	RetireAddonVersion(ctx context.Context, addonVersionID pgtype.UUID) (AddonVersion, error)
	RetirePlanVersion(ctx context.Context, planVersionID pgtype.UUID) (PlanVersion, error)
	// Records the reversal on the reward. The compensating ledger entries are
	// written by the caller in the same transaction, so a reward can never read as
	// reversed without the money having moved back.
	ReverseReferralReward(ctx context.Context, arg ReverseReferralRewardParams) (ReferralReward, error)
	ReviewAnomalySignal(ctx context.Context, arg ReviewAnomalySignalParams) (AnomalySignal, error)
	RevokeAdminRole(ctx context.Context, arg RevokeAdminRoleParams) error
	RevokeAdminSession(ctx context.Context, arg RevokeAdminSessionParams) (AdminSession, error)
	// Logout-everywhere. `keep_session_id` lets the caller preserve the session
	// that requested it, which is what a password change should do.
	RevokeAdminSessionsForUser(ctx context.Context, arg RevokeAdminSessionsForUserParams) (int64, error)
	RevokeChannelExemption(ctx context.Context, userID pgtype.UUID) error
	RevokeCustomerIdentity(ctx context.Context, arg RevokeCustomerIdentityParams) (Identity, error)
	// Guarded by `user_id` as well as `id`, so a customer can only ever end one of
	// their own sessions even if they learn another session's identifier.
	RevokeCustomerSession(ctx context.Context, arg RevokeCustomerSessionParams) (CustomerSession, error)
	// Every session established through one OIDC provider. An operator disabling or
	// removing a provider needs the sessions it minted to end with it; leaving them
	// live would mean the provider is off but its access is not.
	RevokeCustomerSessionsForProvider(ctx context.Context, authProvider pgtype.Text) ([]pgtype.UUID, error)
	// "Sign out everywhere". `except_session_id` keeps the caller's own session
	// alive when the customer asked to end the others rather than all of them.
	RevokeCustomerSessionsForUser(ctx context.Context, arg RevokeCustomerSessionsForUserParams) ([]pgtype.UUID, error)
	// An operator may reclaim a gift that has not been redeemed. A claimed gift is
	// deliberately not revocable: the recipient already holds what it bought, and
	// taking it back is a refund decision with its own record.
	RevokeGift(ctx context.Context, arg RevokeGiftParams) (Gift, error)
	// Revocation is what a customer removing a card does. The row is kept so a
	// historical charge still resolves to the method that made it.
	RevokePaymentMethod(ctx context.Context, arg RevokePaymentMethodParams) (PaymentMethod, error)
	RevokePersonalOffer(ctx context.Context, offerID pgtype.UUID) (PersonalOffer, error)
	RotateAdminSessionToken(ctx context.Context, arg RotateAdminSessionTokenParams) (AdminSession, error)
	// Swapping the token behind a live session shortens the window in which one
	// captured from a log or a proxy stays replayable. The unique index on
	// `token_hash` means a colliding rotation fails rather than merging sessions.
	RotateCustomerSessionToken(ctx context.Context, arg RotateCustomerSessionTokenParams) (CustomerSession, error)
	// Re-presenting the same provider token is not a new method: the provider still
	// holds one binding, so the row is refreshed rather than duplicated. Consent is
	// re-stamped because the customer just granted it again.
	SavePaymentMethod(ctx context.Context, arg SavePaymentMethodParams) (PaymentMethod, error)
	SaveReferralProgram(ctx context.Context, arg SaveReferralProgramParams) (ReferralProgram, error)
	// Secrets are written on their own so a screen that did not change a token does
	// not have to re-send it, which is what makes a write-only field workable.
	SaveSettingSecrets(ctx context.Context, arg SaveSettingSecretsParams) error
	// The version guard turns two panel tabs saving the same screen into a conflict
	// rather than a silent overwrite. A caller that gets no row re-reads and retries.
	SaveSettingSection(ctx context.Context, arg SaveSettingSectionParams) (SaveSettingSectionRow, error)
	// ---------------------------------------------------------------------------
	// Dunning
	// ---------------------------------------------------------------------------
	// The (cycle_key, attempt) uniqueness is the idempotency guard: a replayed job
	// inserts nothing and the caller reads back the attempt that already exists.
	ScheduleDunningAttempt(ctx context.Context, arg ScheduleDunningAttemptParams) (DunningAttempt, error)
	SearchAnomalySignals(ctx context.Context, arg SearchAnomalySignalsParams) ([]AnomalySignal, error)
	// ---------------------------------------------------------------------------
	// Audit trail
	// ---------------------------------------------------------------------------
	// Audit events are written through `InsertAuditEvent` in commerce.sql, which is
	// the single writer for the trail. The queries below only read it.
	// Keyset pagination on (occurred_at, id) descending. Every filter is optional
	// and null-tolerant, so the panel can compose them from URL state without
	// building SQL on the client side.
	SearchAuditEvents(ctx context.Context, arg SearchAuditEventsParams) ([]AuditEvent, error)
	// The oldest-first counterpart of SearchAuditEvents.
	//
	// Direction is a separate query rather than a CASE inside one, because a CASE
	// in ORDER BY defeats the index and forces a sort of the whole matched set —
	// on an append-only trail that grows without bound, that is the difference
	// between an index scan and a full scan.
	SearchAuditEventsAscending(ctx context.Context, arg SearchAuditEventsAscendingParams) ([]AuditEvent, error)
	SearchBlocklistMatches(ctx context.Context, arg SearchBlocklistMatchesParams) ([]SearchBlocklistMatchesRow, error)
	// ---------------------------------------------------------------------------
	// Customer search and profile
	// ---------------------------------------------------------------------------
	// Search is by identifiers an operator may safely be handed: the Omniflow
	// customer identifier, a Telegram identifier, and a Remnawave username. There
	// is deliberately no free-text search over contact values — those are stored as
	// ciphertext and a fingerprint precisely so they cannot be trawled.
	SearchCustomers(ctx context.Context, arg SearchCustomersParams) ([]SearchCustomersRow, error)
	// ---------------------------------------------------------------------------
	// Fulfillment and jobs
	// ---------------------------------------------------------------------------
	SearchFulfillmentOperations(ctx context.Context, arg SearchFulfillmentOperationsParams) ([]SearchFulfillmentOperationsRow, error)
	// The panel's gift register. Keyset pagination on (created_at, id).
	SearchGifts(ctx context.Context, arg SearchGiftsParams) ([]Gift, error)
	// Delivery columns are selected individually because an order that was never
	// paid has no delivery row, and an embedded struct cannot hold that absence.
	SearchGoodsOrders(ctx context.Context, arg SearchGoodsOrdersParams) ([]SearchGoodsOrdersRow, error)
	// News authoring, segments, templates, and campaigns.
	// ---------------------------------------------------------------------------
	// News
	// ---------------------------------------------------------------------------
	SearchNewsPosts(ctx context.Context, arg SearchNewsPostsParams) ([]SearchNewsPostsRow, error)
	// ---------------------------------------------------------------------------
	// Finance
	// ---------------------------------------------------------------------------
	SearchOrders(ctx context.Context, arg SearchOrdersParams) ([]Order, error)
	SearchPersonalOffers(ctx context.Context, arg SearchPersonalOffersParams) ([]PersonalOffer, error)
	SearchPromotions(ctx context.Context, arg SearchPromotionsParams) ([]SearchPromotionsRow, error)
	// ---------------------------------------------------------------------------
	// Referral review
	// ---------------------------------------------------------------------------
	// The review queue: pairs a person may need to look at, newest first.
	SearchReferralAttributions(ctx context.Context, arg SearchReferralAttributionsParams) ([]SearchReferralAttributionsRow, error)
	// ---------------------------------------------------------------------------
	// Ticket queue view
	// ---------------------------------------------------------------------------
	// The queue. Oldest activity first, because a desk works the top of the list.
	//
	// The SLA columns are computed here rather than in the panel so that "overdue"
	// means the same thing in the list, in the counters, and in the report.
	SearchSupportTickets(ctx context.Context, arg SearchSupportTicketsParams) ([]SearchSupportTicketsRow, error)
	// The raw body is deliberately not selected: it can contain provider payloads,
	// and the panel never needs it to answer "did this arrive and was it accepted".
	SearchWebhookEvents(ctx context.Context, arg SearchWebhookEventsParams) ([]SearchWebhookEventsRow, error)
	// Written once, from the environment the installation already had. An
	// installation upgrading from v0.5 therefore keeps the limits its operator
	// configured, and every later change comes from the panel.
	SeedCommerceSettings(ctx context.Context, arg SeedCommerceSettingsParams) (CommerceSetting, error)
	SetAIProviderCredentials(ctx context.Context, arg SetAIProviderCredentialsParams) error
	// Starts enrolment. `totp_confirmed_at` is deliberately cleared: a secret that
	// has not been proven by a code cannot satisfy a login challenge.
	SetAdminTOTPSecret(ctx context.Context, arg SetAdminTOTPSecretParams) (AdminUser, error)
	SetAdminUserPassword(ctx context.Context, arg SetAdminUserPasswordParams) (AdminUser, error)
	SetAdminUserStatus(ctx context.Context, arg SetAdminUserStatusParams) (AdminUser, error)
	SetAutoRenewState(ctx context.Context, arg SetAutoRenewStateParams) (AutoRenewSetting, error)
	SetBulkOperationTotal(ctx context.Context, arg SetBulkOperationTotalParams) (BulkOperation, error)
	// The permitted transitions are enforced here rather than in the caller: a
	// campaign that could jump from draft to completed would report a reach it never
	// had.
	SetCampaignState(ctx context.Context, arg SetCampaignStateParams) (Campaign, error)
	SetCartAddon(ctx context.Context, arg SetCartAddonParams) error
	SetCartAutoPurchase(ctx context.Context, arg SetCartAutoPurchaseParams) (Cart, error)
	// The single goods line. A plan cart's add-ons are cleared alongside, because
	// a cart that changed kind must not keep the other kind's contents.
	SetCartGoods(ctx context.Context, arg SetCartGoodsParams) error
	SetChannelEnforcement(ctx context.Context, arg SetChannelEnforcementParams) (ChannelEnforcement, error)
	SetDefaultPaymentMethod(ctx context.Context, arg SetDefaultPaymentMethodParams) (PaymentMethod, error)
	// Clearing and setting run in one transaction, because the partial unique index
	// allows exactly one default: doing them apart would leave a window in which a
	// new ticket has nowhere to go.
	SetDefaultSupportQueue(ctx context.Context, queueID pgtype.UUID) error
	// The promo code a saved shop purchase carries.
	//
	// It lives on the cart rather than in a session state because the cart is
	// already the thing that survives navigating away, and a code held anywhere
	// else would be a second place a customer's intention can be lost.
	SetGoodsCartPromo(ctx context.Context, arg SetGoodsCartPromoParams) (Cart, error)
	SetGoodsOrderStatus(ctx context.Context, arg SetGoodsOrderStatusParams) (GoodsOrder, error)
	SetMCPServerCredentials(ctx context.Context, arg SetMCPServerCredentialsParams) error
	// The owner's decisions: enablement, the permission it maps to, and whether it
	// writes. Separate from discovery for the reason above.
	SetMCPToolPolicy(ctx context.Context, arg SetMCPToolPolicyParams) (McpTool, error)
	SetMaintenanceState(ctx context.Context, arg SetMaintenanceStateParams) (MaintenanceState, error)
	// Publication is recorded, not inferred. `published_at` is set once and kept, so
	// unpublishing and republishing does not rewrite when customers first saw it.
	SetNewsPostState(ctx context.Context, arg SetNewsPostStateParams) (NewsPost, error)
	SetOrderState(ctx context.Context, arg SetOrderStateParams) (Order, error)
	// Replaces the add-ons offered with a plan version. Deleting first keeps the
	// set exactly what the operator chose rather than the union of every edit.
	SetPlanVersionAddons(ctx context.Context, planVersionID pgtype.UUID) error
	SetPlanVisibility(ctx context.Context, arg SetPlanVisibilityParams) (Plan, error)
	SetPromoCodeActive(ctx context.Context, arg SetPromoCodeActiveParams) (PromoCode, error)
	// The two writes are one statement on purpose: `recurring_enabled` may only be
	// true alongside a passing test, and the table constraint refuses any pair that
	// violates it.
	SetProviderRecurring(ctx context.Context, arg SetProviderRecurringParams) (PaymentProviderSetting, error)
	SetReferralReviewState(ctx context.Context, arg SetReferralReviewStateParams) (ReferralAttribution, error)
	SetSupportTicketPriority(ctx context.Context, arg SetSupportTicketPriorityParams) (SupportTicket, error)
	// Resolution and reopening are recorded rather than inferred.
	//
	// `resolved_at` is set the first time a ticket reaches a terminal state and
	// cleared when it comes back, and `reopened_count` counts the round trips —
	// which is the signal that an answer did not actually answer the question.
	SetSupportTicketStatus(ctx context.Context, arg SetSupportTicketStatusParams) (SupportTicket, error)
	// Whether a secret exists, without returning it. It is what the panel shows in
	// place of the value: "configured" is the only safe rendering of a secret.
	SettingSecretsPresent(ctx context.Context) ([]SettingSecretsPresentRow, error)
	// Only a previewed operation may run. That is what enforces "impact preview
	// before bulk change" in the database rather than only in the panel.
	StartBulkOperation(ctx context.Context, operationID pgtype.UUID) (BulkOperation, error)
	// Provider cost, not customer price: the spend ceiling protects the operator's
	// funding source, and that is what the provider actually draws down.
	SumRecentGoodsSpend(ctx context.Context, arg SumRecentGoodsSpendParams) (int64, error)
	// The rolling window counts what was actually credited, so a failed or expired
	// attempt never consumes a customer's allowance.
	SumRecentTopups(ctx context.Context, arg SumRecentTopupsParams) (int64, error)
	// Superseding is scoped to one subscription so buying a second subscription
	// never retires the first one's entitlement.
	SupersedePreviousEntitlements(ctx context.Context, arg SupersedePreviousEntitlementsParams) error
	// The desk at a glance: what is waiting, what is overdue, and how quickly the
	// desk is answering.
	SupportDeskSummary(ctx context.Context, since pgtype.Timestamptz) (SupportDeskSummaryRow, error)
	// ---------------------------------------------------------------------------
	// Workload and response-time reporting
	// ---------------------------------------------------------------------------
	// Per-operator workload over a window.
	//
	// The definitions are deliberately narrow and are documented beside the report:
	// `replies` counts operator messages the operator actually wrote, `resolved`
	// counts tickets that reached a terminal state while assigned to them, and the
	// response measure is the median rather than the mean, because one ticket
	// answered a week late would otherwise make a good week look bad.
	SupportWorkloadReport(ctx context.Context, since pgtype.Timestamptz) ([]SupportWorkloadReportRow, error)
	SuppressCustomer(ctx context.Context, arg SuppressCustomerParams) (CommunicationSuppression, error)
	TagSupportTicket(ctx context.Context, arg TagSupportTicketParams) error
	TelemetryInstallation(ctx context.Context) (pgtype.UUID, error)
	TelemetrySummary(ctx context.Context) (TelemetrySummaryRow, error)
	// Slides the inactivity window forward. The absolute deadline is never
	// extended, so continuous activity cannot keep a session alive indefinitely.
	TouchAdminSession(ctx context.Context, arg TouchAdminSessionParams) (AdminSession, error)
	// Slides the inactivity deadline forward, clamped so it can never pass the
	// absolute one. Without the clamp a request made just before the absolute
	// horizon would extend a session the absolute limit had already ended.
	TouchCustomerSession(ctx context.Context, arg TouchCustomerSessionParams) (CustomerSession, error)
	TouchPaymentMethodUsed(ctx context.Context, id pgtype.UUID) error
	UnsuppressCustomer(ctx context.Context, userID pgtype.UUID) error
	UntagSupportTicket(ctx context.Context, arg UntagSupportTicketParams) error
	// The customer's own locale and timezone. Both are validated in Go against the
	// supported set before they reach here.
	UpdateAccountProfile(ctx context.Context, arg UpdateAccountProfileParams) (User, error)
	// Preferences are merged rather than replaced, so a panel that only knows about
	// one key cannot silently drop the others when it saves.
	UpdateAdminUserPreferences(ctx context.Context, arg UpdateAdminUserPreferencesParams) (AdminUser, error)
	UpdateAdminUserProfile(ctx context.Context, arg UpdateAdminUserProfileParams) (AdminUser, error)
	UpdateContactChannelPreferences(ctx context.Context, arg UpdateContactChannelPreferencesParams) (ContactChannel, error)
	UpdateCustomerImportProgress(ctx context.Context, arg UpdateCustomerImportProgressParams) (CustomerImport, error)
	UpdateCustomerPreferences(ctx context.Context, arg UpdateCustomerPreferencesParams) (User, error)
	UpdateEntitlementObservedState(ctx context.Context, arg UpdateEntitlementObservedStateParams) (Entitlement, error)
	UpdateFulfillmentOperation(ctx context.Context, arg UpdateFulfillmentOperationParams) (FulfillmentOperation, error)
	UpdateGoodsProduct(ctx context.Context, arg UpdateGoodsProductParams) (GoodsProduct, error)
	UpdateOrderPayment(ctx context.Context, arg UpdateOrderPaymentParams) (Order, error)
	UpdateOrderRefund(ctx context.Context, arg UpdateOrderRefundParams) (Order, error)
	UpdatePaymentIntentStatus(ctx context.Context, arg UpdatePaymentIntentStatusParams) (PaymentIntent, error)
	UpdatePlanOrdering(ctx context.Context, arg UpdatePlanOrderingParams) (Plan, error)
	UpdatePromotion(ctx context.Context, arg UpdatePromotionParams) (Promotion, error)
	UpdateSubscriptionSettings(ctx context.Context, arg UpdateSubscriptionSettingsParams) (CommerceSetting, error)
	UpdateTopUpSettings(ctx context.Context, arg UpdateTopUpSettingsParams) (CommerceSetting, error)
	UpsertAIProvider(ctx context.Context, arg UpsertAIProviderParams) (UpsertAIProviderRow, error)
	UpsertAIUsageLimit(ctx context.Context, arg UpsertAIUsageLimitParams) (AiUsageLimit, error)
	UpsertAddon(ctx context.Context, arg UpsertAddonParams) (Addon, error)
	UpsertAddonLocalization(ctx context.Context, arg UpsertAddonLocalizationParams) (AddonLocalization, error)
	UpsertAdminOIDCProvider(ctx context.Context, arg UpsertAdminOIDCProviderParams) (AdminOidcProvider, error)
	UpsertAnomalyRule(ctx context.Context, arg UpsertAnomalyRuleParams) (AnomalyRule, error)
	UpsertAudienceSegment(ctx context.Context, arg UpsertAudienceSegmentParams) (AudienceSegment, error)
	// `consent_at` is only ever written when auto-renew is being turned on, and it
	// is never cleared: a customer who disables and re-enables re-consents, and a
	// customer who disables keeps the record that they once agreed.
	UpsertAutoRenewSettings(ctx context.Context, arg UpsertAutoRenewSettingsParams) (AutoRenewSetting, error)
	// ---------------------------------------------------------------------------
	// Matches and adjudication
	// ---------------------------------------------------------------------------
	// Re-detecting a match an operator has already decided must not reopen it: the
	// conflict clause deliberately touches nothing, so an allow decision survives
	// every subsequent refresh of the source.
	UpsertBlocklistMatch(ctx context.Context, arg UpsertBlocklistMatchParams) (BlocklistMatch, error)
	// A null auth header on update means "keep the stored credential", matching the
	// write-only treatment every other secret in the schema gets.
	UpsertBlocklistSource(ctx context.Context, arg UpsertBlocklistSourceParams) (BlocklistSource, error)
	UpsertCannedResponse(ctx context.Context, arg UpsertCannedResponseParams) (SupportCannedResponse, error)
	// ---------------------------------------------------------------------------
	// Cart and deferred purchase
	// ---------------------------------------------------------------------------
	UpsertCart(ctx context.Context, arg UpsertCartParams) (Cart, error)
	UpsertCustomerImportItem(ctx context.Context, arg UpsertCustomerImportItemParams) (CustomerImportItem, error)
	// The client secret is only overwritten when a new one is supplied, so saving
	// the form without retyping it does not blank the stored credential.
	UpsertCustomerOIDCProvider(ctx context.Context, arg UpsertCustomerOIDCProviderParams) (CustomerOidcProvider, error)
	// Saving a shop purchase for later.
	//
	// It replaces whatever open cart the customer had, because there is one open
	// cart per customer and a saved plan and a saved shop item are two different
	// intentions. Silently keeping both would mean an auto-purchase charging for
	// something the customer thought they had replaced.
	//
	// auto_purchase is false and stays false. A goods price is a provider quote
	// that expires; charging one unattended means charging a number the customer
	// last saw days ago.
	UpsertGoodsCart(ctx context.Context, arg UpsertGoodsCartParams) (Cart, error)
	UpsertGoodsPricing(ctx context.Context, arg UpsertGoodsPricingParams) (GoodsPricing, error)
	UpsertGoodsProductLocalization(ctx context.Context, arg UpsertGoodsProductLocalizationParams) (GoodsProductLocalization, error)
	// A null ciphertext on update means "leave the stored credential alone", so the
	// panel can render and re-save the form without ever echoing a secret back.
	UpsertGoodsProvider(ctx context.Context, arg UpsertGoodsProviderParams) (GoodsProvider, error)
	UpsertLoyaltyStanding(ctx context.Context, arg UpsertLoyaltyStandingParams) (LoyaltyStanding, error)
	UpsertMCPServer(ctx context.Context, arg UpsertMCPServerParams) (UpsertMCPServerRow, error)
	UpsertMessageTemplate(ctx context.Context, arg UpsertMessageTemplateParams) (MessageTemplate, error)
	UpsertNewsPost(ctx context.Context, arg UpsertNewsPostParams) (NewsPost, error)
	// ---------------------------------------------------------------------------
	// Operator notifications
	// ---------------------------------------------------------------------------
	UpsertOperatorTopic(ctx context.Context, arg UpsertOperatorTopicParams) (OperatorTopic, error)
	// Null ciphertexts mean "keep what is stored". Recurring is written through the
	// separate capability-test statement below, never here, so a settings save can
	// never quietly enable it without a passing test.
	UpsertPaymentProviderSettings(ctx context.Context, arg UpsertPaymentProviderSettingsParams) (PaymentProviderSetting, error)
	UpsertPlanLocalization(ctx context.Context, arg UpsertPlanLocalizationParams) (PlanLocalization, error)
	UpsertRemnawaveMapping(ctx context.Context, arg UpsertRemnawaveMappingParams) (RemnawaveUser, error)
	UpsertRequiredChannel(ctx context.Context, arg UpsertRequiredChannelParams) (RequiredChannel, error)
	UpsertSubscriptionRemnawaveUser(ctx context.Context, arg UpsertSubscriptionRemnawaveUserParams) (Subscription, error)
	UpsertSupportQueue(ctx context.Context, arg UpsertSupportQueueParams) (SupportQueue, error)
	UpsertSupportTag(ctx context.Context, arg UpsertSupportTagParams) (SupportTag, error)
}

var _ Querier = (*Queries)(nil)
