// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: reporting.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const refundsInPeriod = `-- name: RefundsInPeriod :many
SELECT
  r.currency,
  count(*)::bigint AS refund_count,
  COALESCE(sum(r.amount_minor), 0)::bigint AS refunded_minor
FROM refunds r
WHERE r.created_at >= $1 AND r.created_at < $2
  AND r.status = 'succeeded'
  AND ($3::text IS NULL OR r.currency = $3::text)
GROUP BY r.currency
ORDER BY r.currency
`

type RefundsInPeriodParams struct {
	Since    pgtype.Timestamptz `json:"since"`
	Until    pgtype.Timestamptz `json:"until"`
	Currency pgtype.Text        `json:"currency"`
}

type RefundsInPeriodRow struct {
	Currency      string `json:"currency"`
	RefundCount   int64  `json:"refund_count"`
	RefundedMinor int64  `json:"refunded_minor"`
}

// Refunds by the date they were issued, which is the only date on which an
// operator can act.
func (q *Queries) RefundsInPeriod(ctx context.Context, arg RefundsInPeriodParams) ([]RefundsInPeriodRow, error) {
	rows, err := q.db.Query(ctx, refundsInPeriod, arg.Since, arg.Until, arg.Currency)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RefundsInPeriodRow{}
	for rows.Next() {
		var i RefundsInPeriodRow
		if err := rows.Scan(&i.Currency, &i.RefundCount, &i.RefundedMinor); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const salesByDay = `-- name: SalesByDay :many
SELECT
  (date_trunc('day', o.paid_at AT TIME ZONE $1::text))::date AS day,
  o.currency,
  count(*)::bigint AS order_count,
  COALESCE(sum(o.paid_minor), 0)::bigint AS paid_minor,
  COALESCE(sum(o.wallet_minor), 0)::bigint AS wallet_minor
FROM orders o
WHERE o.paid_at >= $2 AND o.paid_at < $3
  AND ($4::text IS NULL OR o.currency = $4::text)
GROUP BY 1, o.currency
ORDER BY 1, o.currency
`

type SalesByDayParams struct {
	Timezone string             `json:"timezone"`
	Since    pgtype.Timestamptz `json:"since"`
	Until    pgtype.Timestamptz `json:"until"`
	Currency pgtype.Text        `json:"currency"`
}

type SalesByDayRow struct {
	Day         pgtype.Date `json:"day"`
	Currency    string      `json:"currency"`
	OrderCount  int64       `json:"order_count"`
	PaidMinor   int64       `json:"paid_minor"`
	WalletMinor int64       `json:"wallet_minor"`
}

// One row per day with a sale in it.
//
// The day boundary is computed in the installation's own timezone, passed in by
// the caller, because "sales on the 3rd" means the operator's 3rd and a report
// bucketed in UTC puts an evening sale in Vladivostok on the wrong day.
func (q *Queries) SalesByDay(ctx context.Context, arg SalesByDayParams) ([]SalesByDayRow, error) {
	rows, err := q.db.Query(ctx, salesByDay,
		arg.Timezone,
		arg.Since,
		arg.Until,
		arg.Currency,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SalesByDayRow{}
	for rows.Next() {
		var i SalesByDayRow
		if err := rows.Scan(
			&i.Day,
			&i.Currency,
			&i.OrderCount,
			&i.PaidMinor,
			&i.WalletMinor,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const salesByOperation = `-- name: SalesByOperation :many

SELECT
  o.operation,
  o.currency,
  count(*)::bigint AS order_count,
  COALESCE(sum(o.subtotal_minor), 0)::bigint AS subtotal_minor,
  COALESCE(sum(o.discount_minor), 0)::bigint AS discount_minor,
  COALESCE(sum(o.paid_minor), 0)::bigint AS paid_minor,
  COALESCE(sum(o.wallet_minor), 0)::bigint AS wallet_minor
FROM orders o
WHERE o.paid_at >= $1 AND o.paid_at < $2
  AND ($3::text IS NULL OR o.currency = $3::text)
GROUP BY o.operation, o.currency
ORDER BY o.currency, o.operation
`

type SalesByOperationParams struct {
	Since    pgtype.Timestamptz `json:"since"`
	Until    pgtype.Timestamptz `json:"until"`
	Currency pgtype.Text        `json:"currency"`
}

type SalesByOperationRow struct {
	Operation     string `json:"operation"`
	Currency      string `json:"currency"`
	OrderCount    int64  `json:"order_count"`
	SubtotalMinor int64  `json:"subtotal_minor"`
	DiscountMinor int64  `json:"discount_minor"`
	PaidMinor     int64  `json:"paid_minor"`
	WalletMinor   int64  `json:"wallet_minor"`
}

// Sales reporting over a period an operator chooses.
//
// Every query here keys on `orders.paid_at` rather than `updated_at`, so the
// same closed period reports the same figures however many refunds are recorded
// afterwards. Refunds are reported on their own date for the same reason: "what
// did we refund in March" and "what did we sell in February that was later
// refunded" are different questions, and answering the first with the second is
// how a refund appears to reduce a month that had already closed.
//
// Provider money and wallet credit stay separate in every one of these, as they
// do on the dashboard. Wallet credit was already counted as revenue when the
// balance was funded, so adding the two counts it twice.
// What was sold, by what kind of sale. This is the breakdown that separates a
// new purchase from a renewal, an add-on, and a wallet top-up.
func (q *Queries) SalesByOperation(ctx context.Context, arg SalesByOperationParams) ([]SalesByOperationRow, error) {
	rows, err := q.db.Query(ctx, salesByOperation, arg.Since, arg.Until, arg.Currency)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SalesByOperationRow{}
	for rows.Next() {
		var i SalesByOperationRow
		if err := rows.Scan(
			&i.Operation,
			&i.Currency,
			&i.OrderCount,
			&i.SubtotalMinor,
			&i.DiscountMinor,
			&i.PaidMinor,
			&i.WalletMinor,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const salesByPlan = `-- name: SalesByPlan :many
SELECT
  p.code AS plan_code,
  pv.version AS plan_version,
  pv.billing_period,
  o.currency,
  count(DISTINCT o.id)::bigint AS order_count,
  COALESCE(sum(ol.unit_amount_minor * ol.quantity), 0)::bigint AS gross_minor
FROM orders o
JOIN order_lines ol ON ol.order_id = o.id
JOIN plan_versions pv ON pv.id = ol.plan_version_id
JOIN plans p ON p.id = pv.plan_id
WHERE o.paid_at >= $1 AND o.paid_at < $2
  AND ($3::text IS NULL OR o.currency = $3::text)
GROUP BY p.code, pv.version, pv.billing_period, o.currency
ORDER BY gross_minor DESC, p.code, pv.version
`

type SalesByPlanParams struct {
	Since    pgtype.Timestamptz `json:"since"`
	Until    pgtype.Timestamptz `json:"until"`
	Currency pgtype.Text        `json:"currency"`
}

type SalesByPlanRow struct {
	PlanCode      string `json:"plan_code"`
	PlanVersion   int32  `json:"plan_version"`
	BillingPeriod string `json:"billing_period"`
	Currency      string `json:"currency"`
	OrderCount    int64  `json:"order_count"`
	GrossMinor    int64  `json:"gross_minor"`
}

// What was sold, by plan and billing period.
//
// It reads the plan code and the period off the version the order actually
// referenced rather than off the plan's current state, which is the whole
// reason plan versions exist: a price change last week must not re-price a sale
// from last month.
func (q *Queries) SalesByPlan(ctx context.Context, arg SalesByPlanParams) ([]SalesByPlanRow, error) {
	rows, err := q.db.Query(ctx, salesByPlan, arg.Since, arg.Until, arg.Currency)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SalesByPlanRow{}
	for rows.Next() {
		var i SalesByPlanRow
		if err := rows.Scan(
			&i.PlanCode,
			&i.PlanVersion,
			&i.BillingPeriod,
			&i.Currency,
			&i.OrderCount,
			&i.GrossMinor,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const trialConversion = `-- name: TrialConversion :one
WITH claims AS (
  SELECT tc.user_id, tc.claimed_at
  FROM trial_claims tc
  WHERE tc.claimed_at >= $1 AND tc.claimed_at < $2
)
SELECT
  count(*)::bigint AS trials,
  count(*) FILTER (
    WHERE EXISTS (
      SELECT 1 FROM orders o
      WHERE o.user_id = claims.user_id
        AND o.paid_at IS NOT NULL
        AND o.paid_at > claims.claimed_at
        AND o.operation IN ('purchase', 'renewal', 'extension', 'upgrade')
        -- A zero-value order is a free grant rather than a conversion. Counting
        -- one would make a promotion that gives a month away look like revenue.
        AND o.subtotal_minor - o.discount_minor > 0
    )
  )::bigint AS converted
FROM claims
`

type TrialConversionParams struct {
	Since pgtype.Timestamptz `json:"since"`
	Until pgtype.Timestamptz `json:"until"`
}

type TrialConversionRow struct {
	Trials    int64 `json:"trials"`
	Converted int64 `json:"converted"`
}

// Of the trials claimed in this period, how many of those customers have since
// paid for something.
//
// It is a cohort measure and reads low for a window that ends today, because a
// trial claimed yesterday has had a day to convert. That is a property of the
// question rather than a fault in the query, and the panel says so beside the
// figure rather than quietly excluding recent trials.
func (q *Queries) TrialConversion(ctx context.Context, arg TrialConversionParams) (TrialConversionRow, error) {
	row := q.db.QueryRow(ctx, trialConversion, arg.Since, arg.Until)
	var i TrialConversionRow
	err := row.Scan(&i.Trials, &i.Converted)
	return i, err
}
